//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class AKIRA
    {
        public double KIRA_NO { get; set; }
        public string CARIKOD { get; set; }
        public string SASE_NO { get; set; }
        public string PLAKA { get; set; }
        public string MODEL_KOD { get; set; }
        public string BELGE_NO { get; set; }
        public Nullable<System.DateTime> ISLEM_TRH { get; set; }
        public Nullable<System.DateTime> KIRA_BAS_TRH { get; set; }
        public Nullable<System.DateTime> KIRA_BIT_TRH { get; set; }
        public string TES_YERI { get; set; }
        public Nullable<double> TES_KM { get; set; }
        public Nullable<int> TES_YAKIT { get; set; }
        public string KIRALANDI { get; set; }
        public string REZERVASYON { get; set; }
        public string ACIKLAMA { get; set; }
        public string KIRA_TURU { get; set; }
        public Nullable<double> KIRA_SURE { get; set; }
        public Nullable<double> KIRA_FYT { get; set; }
        public string KDV_DAHIL { get; set; }
        public Nullable<double> BRUT_TUT { get; set; }
        public Nullable<double> ISK_ORAN { get; set; }
        public Nullable<double> ISK_TUT { get; set; }
        public Nullable<double> ARA_TOP { get; set; }
        public Nullable<double> KDV { get; set; }
        public Nullable<double> KDV_TUT { get; set; }
        public Nullable<double> KDVSIZ_TUT { get; set; }
        public Nullable<double> NET_TUT { get; set; }
    }
}
