//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class AKSESUAR
    {
        public string AKSESUAR_KODU { get; set; }
        public string AKSESUAR_ADI { get; set; }
        public Nullable<bool> SEC { get; set; }
        public string TIP { get; set; }
        public Nullable<double> ALIS_TL { get; set; }
        public Nullable<double> ALIS_DOV { get; set; }
        public Nullable<double> SATIS_TL { get; set; }
        public Nullable<double> SATIS_DOV { get; set; }
        public string DOVIZ_KOD { get; set; }
        public Nullable<double> KDV { get; set; }
        public string STOK_KOD { get; set; }
        public string AKS_KISA_KOD { get; set; }
    }
}
