//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class AKUCTRL
    {
        public string SASI_NO { get; set; }
        public System.DateTime TARIH { get; set; }
        public string AKUMARAKA { get; set; }
        public Nullable<double> KM { get; set; }
        public string MARKA { get; set; }
        public string MODEL { get; set; }
        public string ARAC_TIP { get; set; }
        public Nullable<double> KAPASITE { get; set; }
        public string PLAKA_NO { get; set; }
        public string AKUGOVDEDRM { get; set; }
        public string KUTUPBASARTI { get; set; }
        public string KUTUPBASEKSI { get; set; }
        public string ELKSEVGOZ1 { get; set; }
        public string ELKSEVGOZ2 { get; set; }
        public string ELKSEVGOZ3 { get; set; }
        public string ELKSEVGOZ4 { get; set; }
        public string ELKSEVGOZ5 { get; set; }
        public string ELKSEVGOZ6 { get; set; }
        public Nullable<double> SARJOYGOZ1 { get; set; }
        public Nullable<double> SARJOYGOZ2 { get; set; }
        public Nullable<double> SARJOYGOZ3 { get; set; }
        public Nullable<double> SARJOYGOZ4 { get; set; }
        public Nullable<double> SARJOYGOZ5 { get; set; }
        public Nullable<double> SARJOYGOZ6 { get; set; }
        public Nullable<double> SARJSYGOZ1 { get; set; }
        public Nullable<double> SARJSYGOZ2 { get; set; }
        public Nullable<double> SARJSYGOZ3 { get; set; }
        public Nullable<double> SARJSYGOZ4 { get; set; }
        public Nullable<double> SARJSYGOZ5 { get; set; }
        public Nullable<double> SARJSYGOZ6 { get; set; }
        public Nullable<double> SARJAKIMI { get; set; }
        public Nullable<double> SARJZAMAN { get; set; }
        public string KONTROL_PERSON_KOD { get; set; }
        public string YETKILI_PERSON_KOD { get; set; }
    }
}
