//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALISAYR
    {
        public double ALIS_NO { get; set; }
        public int SIRANO { get; set; }
        public Nullable<System.DateTime> KAYIT_TRH { get; set; }
        public Nullable<double> STOK_NO { get; set; }
        public string STOK_KODU { get; set; }
        public string STOK_ADI { get; set; }
        public string SAT_TIP { get; set; }
        public Nullable<double> KDV { get; set; }
        public Nullable<double> FIYAT_USD { get; set; }
        public Nullable<double> FIYAT_TL { get; set; }
        public Nullable<double> FIYAT_DOVIZ { get; set; }
        public string DOVIZ_KODU { get; set; }
        public Nullable<double> MIKTAR { get; set; }
        public Nullable<System.DateTime> KURTARIH { get; set; }
        public Nullable<double> SIP_NO { get; set; }
        public string DEPO_KODU { get; set; }
        public Nullable<double> GER_TUT { get; set; }
        public Nullable<double> ISK_TUT { get; set; }
        public Nullable<double> ISK_ORAN { get; set; }
        public Nullable<double> IRS_NO { get; set; }
        public Nullable<int> IRS_SIRA { get; set; }
        public Nullable<double> FAT_NO { get; set; }
        public Nullable<double> MASRAF_TL { get; set; }
        public string KDV_DAHIL { get; set; }
        public Nullable<double> TL_KURDEGER { get; set; }
        public string SIP_KOD { get; set; }
        public Nullable<int> SIP_SIRA { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_USER { get; set; }
        public string SERINO { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<double> ISK_ORAN2 { get; set; }
    }
}
