//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALSIPTIP
    {
        public string SIPTIP_KOD { get; set; }
        public string SIPTIP_AD { get; set; }
        public Nullable<double> SIPTIP_ISKA { get; set; }
        public Nullable<double> SIPTIP_ISKB { get; set; }
        public Nullable<double> SIPTIP_ISKC { get; set; }
        public Nullable<double> SIPTIP_ISKD { get; set; }
        public Nullable<byte> ONC { get; set; }
        public string GARANTI { get; set; }
    }
}
