//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALSIPDET
    {
        public double SIP_NO { get; set; }
        public int SIRA_NO { get; set; }
        public string STOK_KODU { get; set; }
        public string STOK_ADI { get; set; }
        public Nullable<double> STOK_NO { get; set; }
        public Nullable<System.DateTime> TESLIM_TRH { get; set; }
        public Nullable<double> SIP_MIK { get; set; }
        public Nullable<double> REZERV_MIK { get; set; }
        public Nullable<double> BRM_FYT { get; set; }
        public Nullable<double> SIP_TUTAR { get; set; }
        public Nullable<double> KDV { get; set; }
        public Nullable<double> FYT_USD { get; set; }
        public Nullable<double> FYT_DOVIZ { get; set; }
        public string DOVIZ_KODU { get; set; }
        public Nullable<double> TL_KURDEGER { get; set; }
        public Nullable<double> ISK_ORAN { get; set; }
        public string ACIKLAMA { get; set; }
        public string KDV_DAHIL { get; set; }
        public Nullable<double> GER_TUT { get; set; }
        public Nullable<double> ISK_TUT { get; set; }
    }
}
