//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALSIPMAS
    {
        public double SIPARIS_NO { get; set; }
        public Nullable<System.DateTime> SIPARIS_TRH { get; set; }
        public string SIPARIS_TURU { get; set; }
        public string CARI_KODU { get; set; }
        public Nullable<double> TOPLAM_TUTAR { get; set; }
        public Nullable<double> KDV_TUTAR { get; set; }
        public Nullable<double> GENEL_TOPLAM { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<double> WEB_SIPNO { get; set; }
        public string ODE_KOD { get; set; }
        public string PLAKA { get; set; }
        public Nullable<byte> STATU { get; set; }
        public Nullable<double> ISKONTO { get; set; }
        public Nullable<double> ISK_TUTAR { get; set; }
        public Nullable<System.DateTime> SAAT { get; set; }
        public string DOSYA_NO { get; set; }
        public string PER_KOD { get; set; }
        public string HAZIRLAYAN { get; set; }
        public string SEVK_CARI { get; set; }
        public string KARGO_NO { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_USER { get; set; }
    }
}
