//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARACMAS
    {
        public string SASE_NO { get; set; }
        public short SIRA_NO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string PER_KOD { get; set; }
        public string ISLEM_KOD { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<double> TUTAR { get; set; }
    }
}
