//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARACPLAN
    {
        public int PLAN_ID { get; set; }
        public string SASE_NO { get; set; }
        public string ISLEM_TUR { get; set; }
        public string ISLEM_ACIKLAMA { get; set; }
        public Nullable<int> PER_ID { get; set; }
        public Nullable<System.DateTime> PLAN_TARIH { get; set; }
        public Nullable<decimal> PLAN_SAYAC { get; set; }
        public string PLAN_PERSON { get; set; }
        public Nullable<System.DateTime> ISLEM_TARIH { get; set; }
        public Nullable<decimal> ISLEM_SAYAC { get; set; }
        public string ISLEM_PERSON { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public string REF_TIP { get; set; }
        public string REF_IENO { get; set; }
        public Nullable<decimal> REF_NO { get; set; }
        public Nullable<byte> STATU { get; set; }
        public Nullable<double> GECIKME_BEDEL { get; set; }
        public string ALT_TIP { get; set; }
    }
}
