//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARACTES
    {
        public double SATIS_NO { get; set; }
        public System.DateTime TESLIM_TRH { get; set; }
        public string PER_KOD { get; set; }
        public string CARI_KOD { get; set; }
        public bool TESLIM_EDILDI { get; set; }
        public bool KONT_1 { get; set; }
        public bool KONT_2 { get; set; }
        public bool KONT_3 { get; set; }
        public bool KONT_4 { get; set; }
        public bool KONT_5 { get; set; }
        public bool KONT_6 { get; set; }
        public bool KONT_7 { get; set; }
        public bool KONT_8 { get; set; }
        public bool KONT_9 { get; set; }
        public bool KONT_10 { get; set; }
        public bool KONT_11 { get; set; }
        public bool KONT_12 { get; set; }
        public bool KONT_13 { get; set; }
        public bool KONT_14 { get; set; }
        public bool KONT_15 { get; set; }
        public bool KONT_16 { get; set; }
        public bool KONT_17 { get; set; }
        public bool KONT_18 { get; set; }
        public bool KONT_19 { get; set; }
        public bool KONT_20 { get; set; }
        public bool KONT_21 { get; set; }
        public bool KONT_22 { get; set; }
        public bool KONT_23 { get; set; }
        public bool KONT_24 { get; set; }
        public bool KONT_25 { get; set; }
        public bool KONT_26 { get; set; }
        public bool KONT_27 { get; set; }
        public bool KONT_28 { get; set; }
        public bool KONT_29 { get; set; }
        public string ACIKLAMA { get; set; }
    }
}
