//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARACHESAP
    {
        public int ROW_ID { get; set; }
        public string SASE_NO { get; set; }
        public string PLAKA_NO { get; set; }
        public string KART_ID { get; set; }
        public string PER_KOD { get; set; }
        public string CARI_KOD { get; set; }
        public Nullable<int> SUBEKODU { get; set; }
        public string REF_TIP { get; set; }
        public Nullable<double> REF_NO { get; set; }
        public string ISLEM_TIP { get; set; }
        public Nullable<System.DateTime> ISLEM_TRH { get; set; }
        public string ISLEM_GRUP { get; set; }
        public string BA_TUR { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> BIRIM_FYT { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public string ACIKLAMA { get; set; }
        public string ACIKLAMA2 { get; set; }
        public Nullable<decimal> KM { get; set; }
        public Nullable<decimal> MESAFE { get; set; }
        public Nullable<System.DateTime> SURE { get; set; }
        public string PER_ADI { get; set; }
        public Nullable<System.DateTime> GIRIS_TRH { get; set; }
        public Nullable<decimal> GIRIS_KM { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_USER { get; set; }
    }
}
