//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARAMAPER
    {
        public string MUS_TIP { get; set; }
        public string ARA_TIP { get; set; }
        public Nullable<double> SATIS_NO { get; set; }
        public string IE_NO { get; set; }
        public Nullable<int> PERIYOT { get; set; }
        public Nullable<System.DateTime> REF_TRH { get; set; }
        public System.DateTime ARAMA_TRH { get; set; }
        public string CARI_KOD { get; set; }
        public string DURUM { get; set; }
        public Nullable<System.DateTime> GORUS_TRH { get; set; }
        public string PER_KOD { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> ANKET_ID { get; set; }
        public Nullable<int> RAP_NO { get; set; }
        public string SASE_NO { get; set; }
    }
}
