//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCAKS
    {
        public string SASE_NO { get; set; }
        public string AKS_KOD { get; set; }
        public double ALIS_FYT { get; set; }
        public double SATIS_FYT { get; set; }
        public float KDV { get; set; }
        public bool ALISTA_VAR { get; set; }
        public bool SATISTA_VAR { get; set; }
        public Nullable<double> OTV { get; set; }
    }
}
