//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCALSIP
    {
        public double SIP_NO { get; set; }
        public string SATIS_PER { get; set; }
        public Nullable<System.DateTime> SIP_TARIH { get; set; }
        public string CARI_KOD { get; set; }
        public string CARI_AD { get; set; }
        public string ADRES1 { get; set; }
        public string ADRES2 { get; set; }
        public string PK { get; set; }
        public string SEMT { get; set; }
        public string ILI { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string FAX { get; set; }
        public string VD { get; set; }
        public string VN { get; set; }
        public string MOD_KOD1 { get; set; }
        public string MOD_KOD2 { get; set; }
        public string RENK1 { get; set; }
        public string RENK2 { get; set; }
        public string DOSEME { get; set; }
        public string SASE_NO { get; set; }
        public string MOTOR_NO { get; set; }
        public string ODEME_SEK { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<double> SATIS_NO { get; set; }
        public Nullable<System.DateTime> SAT_TARIH { get; set; }
        public Nullable<double> ARAC_BEDEL { get; set; }
        public Nullable<double> KDV { get; set; }
        public Nullable<double> KDV_TUT { get; set; }
        public Nullable<double> FAT_TOPLAM { get; set; }
        public string TAV_KOD { get; set; }
        public Nullable<double> TAV_TOPLAM { get; set; }
        public Nullable<double> GNL_TOPLAM { get; set; }
        public Nullable<double> KAPORA { get; set; }
        public Nullable<double> KALAN { get; set; }
        public bool AKTARILDI { get; set; }
        public Nullable<double> OTV { get; set; }
        public Nullable<double> OTV_TUTARI { get; set; }
        public Nullable<double> OTV_INDIR { get; set; }
        public string YETKILI_AD { get; set; }
        public string YETKILI_SOY { get; set; }
        public string TEL3 { get; set; }
        public string EMAIL { get; set; }
        public string URL { get; set; }
        public string CINSIYET { get; set; }
        public string MUS_TIP { get; set; }
        public string TEL4 { get; set; }
        public string KIMLIKNO { get; set; }
        public Nullable<double> PMNO { get; set; }
        public string STATU { get; set; }
        public string CARI_AD2 { get; set; }
        public string SIP_TIP { get; set; }
        public string MAKBUZ_NO { get; set; }
        public Nullable<double> ISK_ORAN { get; set; }
        public Nullable<double> ISK_TUTAR { get; set; }
        public Nullable<double> ARA_TOPLAM { get; set; }
        public Nullable<byte> BEYAN { get; set; }
        public Nullable<byte> FOY { get; set; }
        public Nullable<double> KAMPISK1 { get; set; }
        public Nullable<double> KAMPISK2 { get; set; }
        public Nullable<double> FILOISK1 { get; set; }
        public Nullable<double> KOMISK1 { get; set; }
        public Nullable<double> EKISK1 { get; set; }
        public Nullable<double> TOPLAM_KK { get; set; }
        public Nullable<double> ARA_TOPLAMKK { get; set; }
        public Nullable<int> KK_ID { get; set; }
        public string RENK3 { get; set; }
        public string RENK4 { get; set; }
        public string RENK5 { get; set; }
        public string RENK6 { get; set; }
        public Nullable<double> OTV_MATRAH { get; set; }
        public string IND_DOVIZ { get; set; }
        public Nullable<double> IND_KUR { get; set; }
        public Nullable<double> TAHMINI_PRIM { get; set; }
    }
}
