//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCPRTFY
    {
        public string SASE_NO { get; set; }
        public string MOTOR_NO { get; set; }
        public string MODEL_KOD { get; set; }
        public Nullable<short> MODEL_YIL { get; set; }
        public string RENK_KOD { get; set; }
        public Nullable<double> ALIS_NO { get; set; }
        public Nullable<System.DateTime> ALIS_TRH { get; set; }
        public Nullable<bool> REZERV { get; set; }
        public Nullable<double> SATIS_NO { get; set; }
        public Nullable<System.DateTime> SATIS_TRH { get; set; }
        public string SATIS_CARI { get; set; }
        public string PLAKA { get; set; }
        public Nullable<double> SIP_NO { get; set; }
        public Nullable<System.DateTime> SIP_TRH { get; set; }
        public string SIP_CARI { get; set; }
        public string NOTLAR { get; set; }
        public string BEYAN_ONAY { get; set; }
        public string ALIS_TIP { get; set; }
        public string AKSESUAR { get; set; }
        public string OTPA { get; set; }
        public string IC_RENK { get; set; }
    }
}
