//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCVRSIP
    {
        public int SIP_NO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string PER_KOD { get; set; }
        public Nullable<short> POQ_YIL { get; set; }
        public Nullable<short> POQ_AY { get; set; }
        public string POQ_MARKA { get; set; }
        public string POQ_MODEL { get; set; }
        public string POQ_TIP { get; set; }
        public Nullable<double> AL_SIP_NO { get; set; }
        public string SIP_MARKA { get; set; }
        public string SIP_MODEL { get; set; }
        public string SIP_TIP { get; set; }
        public Nullable<short> SIP_MYIL { get; set; }
        public string SIP_RENK1 { get; set; }
        public string SIP_RENK2 { get; set; }
        public string SIP_RENK3 { get; set; }
        public Nullable<short> SIP_ADET { get; set; }
        public string SIP_DURUM { get; set; }
        public bool SIP_ONAY { get; set; }
        public string SIP_ONAY_PER { get; set; }
        public Nullable<System.DateTime> GON_TRH { get; set; }
        public string GON_NOT { get; set; }
        public Nullable<System.DateTime> CEVAP_TRH { get; set; }
        public string CEVAP_KOD { get; set; }
        public string CEVAP_PER { get; set; }
        public string CEVAP_NOT { get; set; }
        public string ONAY_MARKA { get; set; }
        public string ONAY_MODEL { get; set; }
        public string ONAY_TIP { get; set; }
        public Nullable<short> ONAY_MYIL { get; set; }
        public string ONAY_RENK { get; set; }
        public Nullable<short> ONAY_ADET { get; set; }
        public string OPS_ORDERNO { get; set; }
        public string OPS_SASE { get; set; }
        public string OPS_MOTOR { get; set; }
        public string OPS_MARKA { get; set; }
        public string OPS_MODEL { get; set; }
        public string OPS_TIP { get; set; }
        public Nullable<short> OPS_MYIL { get; set; }
        public string OPS_RENK { get; set; }
        public string OPS_DURUM { get; set; }
        public Nullable<System.DateTime> OPS_TRH1 { get; set; }
        public Nullable<System.DateTime> OPS_TRH2 { get; set; }
        public Nullable<System.DateTime> OPS_TRH3 { get; set; }
        public Nullable<System.DateTime> OPS_TRH4 { get; set; }
        public bool AKTARILDI { get; set; }
        public Nullable<int> OPS_ARCNO { get; set; }
        public Nullable<System.DateTime> UPDATE_TRH { get; set; }
        public string SIP_RENK4 { get; set; }
        public string SIP_RENK5 { get; set; }
        public string SIP_RENK6 { get; set; }
        public string ONAY_RENK2 { get; set; }
        public string OPS_RENK2 { get; set; }
    }
}
