//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASATKKM
    {
        public int KK_ID { get; set; }
        public string KK_MODEL { get; set; }
        public Nullable<double> ISK1 { get; set; }
        public Nullable<double> ISK2 { get; set; }
        public Nullable<double> ISK3 { get; set; }
        public Nullable<double> ISK4 { get; set; }
        public Nullable<double> ISK5 { get; set; }
        public Nullable<double> ISK6 { get; set; }
    }
}
