//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASATIS
    {
        public double SATIS_NO { get; set; }
        public string CARIKOD { get; set; }
        public Nullable<double> BRUTTUT { get; set; }
        public string TIP { get; set; }
        public Nullable<double> INDIRIM { get; set; }
        public Nullable<double> YUZDE { get; set; }
        public Nullable<double> INR_YUZD { get; set; }
        public Nullable<double> MASRAF { get; set; }
        public Nullable<double> KDVTUT { get; set; }
        public Nullable<double> NETTUT { get; set; }
        public Nullable<System.DateTime> FATARIH { get; set; }
        public Nullable<System.DateTime> SAAT { get; set; }
        public Nullable<System.DateTime> VADETRH { get; set; }
        public string FATIRSNO { get; set; }
        public Nullable<double> USD_KUR { get; set; }
        public Nullable<double> USD_TUTAR { get; set; }
        public string ODEME_SEKLI { get; set; }
        public string SIP_NO { get; set; }
        public Nullable<System.DateTime> SIP_TRH { get; set; }
        public string IRS_NO { get; set; }
        public Nullable<System.DateTime> IRS_TRH { get; set; }
        public string ITH_MUS_NO { get; set; }
        public Nullable<System.DateTime> ITH_MUS_TRH { get; set; }
        public string GUM_BEY_NO { get; set; }
        public Nullable<System.DateTime> GUM_BEY_TRH { get; set; }
        public string GUM_MAK_NO { get; set; }
        public Nullable<System.DateTime> GUM_MAK_TRH { get; set; }
        public string AL_FAT_NO { get; set; }
        public Nullable<System.DateTime> AL_FAT_TRH { get; set; }
        public string ODE_BEL_NO { get; set; }
        public Nullable<System.DateTime> ODE_BEL_TRH { get; set; }
        public string MAKBUZ_NO { get; set; }
        public Nullable<System.DateTime> MAKBUZ_TRH { get; set; }
        public string BANDROL_NO { get; set; }
        public string SASE_NO { get; set; }
        public string MOTOR_NO { get; set; }
        public string MODEL_KOD { get; set; }
        public string AYRINTILI { get; set; }
        public Nullable<double> FIS_NO { get; set; }
        public Nullable<double> GER_TUT { get; set; }
        public string ODE_KOD { get; set; }
        public Nullable<double> OTV_TUTARI { get; set; }
        public Nullable<double> OTV { get; set; }
        public Nullable<double> OTV_INDIR { get; set; }
        public string OTV_MAK_NO { get; set; }
        public Nullable<System.DateTime> OTV_MAK_TRH { get; set; }
        public string OTPA { get; set; }
        public string GUMRUK { get; set; }
        public Nullable<short> VADEGUN { get; set; }
        public string EK1 { get; set; }
        public string EK2 { get; set; }
        public string EK3 { get; set; }
        public string SAT_TIP { get; set; }
        public string MUS_TIP { get; set; }
        public Nullable<double> ALSIPNO { get; set; }
        public Nullable<double> KAMPISK1 { get; set; }
        public Nullable<double> KAMPISK2 { get; set; }
        public Nullable<double> FILOISK1 { get; set; }
        public Nullable<double> KOMISK1 { get; set; }
        public Nullable<double> EKISK1 { get; set; }
        public Nullable<double> TOPLAM_KK { get; set; }
        public Nullable<double> ARA_TOPLAMKK { get; set; }
        public Nullable<int> KK_ID { get; set; }
        public Nullable<double> KAMP1FATNO { get; set; }
        public Nullable<double> KAMP2FATNO { get; set; }
        public Nullable<double> FILOFATNO { get; set; }
        public Nullable<double> KOMFATNO { get; set; }
        public Nullable<double> OTV_MATRAH { get; set; }
        public string IND_DOVIZ { get; set; }
        public Nullable<double> IND_KUR { get; set; }
        public string EK4 { get; set; }
        public string EK5 { get; set; }
        public string EK6 { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_USER { get; set; }
        public Nullable<byte> EF_STATU { get; set; }
        public string EF_GUID { get; set; }
        public string EF_POSTAKUTUSU { get; set; }
        public string ISTISNA_CODE { get; set; }
        public string TEVKIFAT_CODE { get; set; }
        public Nullable<byte> EXCEL_AKTAR { get; set; }
    }
}
