//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class AY1
    {
        public short AYLAR { get; set; }
        public Nullable<short> OCAK1 { get; set; }
        public Nullable<short> SUBAT1 { get; set; }
        public Nullable<short> MART1 { get; set; }
        public Nullable<short> NISAN1 { get; set; }
        public Nullable<short> MAYIS1 { get; set; }
        public Nullable<short> HAZIRAN1 { get; set; }
        public Nullable<short> TEMMUZ1 { get; set; }
        public Nullable<short> AGUSTOS1 { get; set; }
        public Nullable<short> EYLUL1 { get; set; }
        public Nullable<short> EKIM1 { get; set; }
        public Nullable<short> KASIM1 { get; set; }
        public Nullable<short> ARALIK1 { get; set; }
    }
}
