//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class AYLARAOGIBORDRO
    {
        public double ISYERINO { get; set; }
        public string DEPNO { get; set; }
        public double PERSNO { get; set; }
        public string ADISOYADI { get; set; }
        public Nullable<double> SUBAT { get; set; }
        public Nullable<double> MART { get; set; }
        public Nullable<double> NISAN { get; set; }
        public Nullable<double> MAYIS { get; set; }
        public Nullable<double> HAZIRAN { get; set; }
        public Nullable<double> TEMMUZ { get; set; }
        public Nullable<double> AGUSTOS { get; set; }
        public Nullable<double> EYLUL { get; set; }
        public Nullable<double> DV { get; set; }
        public Nullable<double> ODENENTUTAR { get; set; }
        public Nullable<double> DEVIR3 { get; set; }
        public Nullable<double> DEVIR4 { get; set; }
        public Nullable<double> DEVIR5 { get; set; }
        public Nullable<double> DEVIR6 { get; set; }
        public Nullable<double> DEVIR7 { get; set; }
        public Nullable<double> DEVIR8 { get; set; }
        public Nullable<double> DEVIR9 { get; set; }
        public Nullable<double> DMV2 { get; set; }
        public Nullable<double> DMV3 { get; set; }
        public Nullable<double> DMV4 { get; set; }
        public Nullable<double> DMV5 { get; set; }
        public Nullable<double> DMV6 { get; set; }
        public Nullable<double> DMV7 { get; set; }
        public Nullable<double> DMV8 { get; set; }
        public Nullable<double> DMV9 { get; set; }
        public Nullable<short> YIL { get; set; }
    }
}
