//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class AYLIKOGI
    {
        public double ISYERINO { get; set; }
        public double PERSNO { get; set; }
        public string CAY { get; set; }
        public string DEPKOD { get; set; }
        public string ISSICNO { get; set; }
        public string ADISOYADI { get; set; }
        public Nullable<double> DEVREDEN { get; set; }
        public Nullable<double> BUAY { get; set; }
        public Nullable<double> KALAN { get; set; }
        public Nullable<double> DMV { get; set; }
        public Nullable<double> FIS_NO { get; set; }
    }
}
