//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANKHRKA
    {
        public Nullable<double> HRK_NO { get; set; }
        public Nullable<double> SIRANO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string BANKA_KOD { get; set; }
        public string HESAP_NO { get; set; }
        public string TIP { get; set; }
        public Nullable<double> ALACAK { get; set; }
        public Nullable<double> ALACAK_USD { get; set; }
        public Nullable<double> ALACAK_DVZ { get; set; }
        public Nullable<double> BORC { get; set; }
        public Nullable<double> BORC_USD { get; set; }
        public Nullable<double> BORC_DVZ { get; set; }
        public Nullable<double> TL_KURDEGER { get; set; }
        public Nullable<double> TL_USDEGER { get; set; }
        public string DOVIZ_KODU { get; set; }
        public string PARA_BAZ { get; set; }
        public string CARI_KOD { get; set; }
        public Nullable<double> REF_NO { get; set; }
        public Nullable<double> PORTFOYNO { get; set; }
        public string CS_TIP { get; set; }
        public string BELGE_NO { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<short> AY { get; set; }
        public Nullable<short> YIL { get; set; }
        public string MUH_KOMISYON { get; set; }
        public Nullable<double> KOMISYON { get; set; }
        public string MUH_KOD { get; set; }
        public string MUH_KARSI { get; set; }
        public string KASAKOD { get; set; }
        public int TAKSIT_SAY { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_USER { get; set; }
        public string REF_TIP { get; set; }
        public string ALT_TIP { get; set; }
    }
}
