//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANKAYR
    {
        public string BANKA_KOD { get; set; }
        public string HESAP_NO { get; set; }
        public string HESAP_ADI { get; set; }
        public string DOVIZ_KODU { get; set; }
        public string HESAR_TURU { get; set; }
        public string MUH_CHES { get; set; }
        public string MUH_TAHSEN { get; set; }
        public string MUH_TAKCEK { get; set; }
        public string MUH_KESCEK { get; set; }
        public string MUH_TEMSEN { get; set; }
        public string MUH_TEMCEK { get; set; }
        public string MUH_SENKRED { get; set; }
        public string MUH_CEKREDI { get; set; }
        public string MUH_KOMISYON { get; set; }
        public Nullable<double> KOMISYON { get; set; }
        public int VALOR { get; set; }
        public string IBAN { get; set; }
    }
}
