//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAYIMSG
    {
        public int MSG_ID { get; set; }
        public string MSG_USR { get; set; }
        public Nullable<byte> MSG_TIP { get; set; }
        public string MSG_KONU { get; set; }
        public string MSG_TEXT { get; set; }
        public Nullable<System.DateTime> MSG_BDATE { get; set; }
        public Nullable<System.DateTime> MSG_EDATE { get; set; }
        public Nullable<System.DateTime> MSG_LOGDATE { get; set; }
        public string MSG_PERS_NAME { get; set; }
    }
}
