//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAYISTOK
    {
        public string SER_KOD { get; set; }
        public string STOK_KOD { get; set; }
        public Nullable<double> MIKTAR { get; set; }
        public string ATIL { get; set; }
        public Nullable<System.DateTime> UPTRH { get; set; }
        public Nullable<double> ATILSTK_ISK { get; set; }
    }
}
