//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAYIPOZ
    {
        public short POZ_ID { get; set; }
        public string POZ_KOD { get; set; }
        public string POZ_TANIM { get; set; }
        public Nullable<short> POZ_IMG { get; set; }
        public Nullable<short> POZ_PARENT { get; set; }
        public string GRUP { get; set; }
        public string BOLUM { get; set; }
        public string POZISYON { get; set; }
    }
}
