//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAYIDATA
    {
        public int DATA_ID { get; set; }
        public string TIP { get; set; }
        public int KEY1 { get; set; }
        public int KEY2 { get; set; }
        public int KEY3 { get; set; }
        public string KEY4 { get; set; }
        public Nullable<double> NUM1 { get; set; }
        public Nullable<double> NUM2 { get; set; }
        public Nullable<double> NUM3 { get; set; }
        public Nullable<double> NUM4 { get; set; }
        public Nullable<double> NUM5 { get; set; }
        public Nullable<double> NUM6 { get; set; }
        public Nullable<double> NUM7 { get; set; }
        public Nullable<double> NUM8 { get; set; }
        public Nullable<double> NUM9 { get; set; }
        public Nullable<double> NUM10 { get; set; }
        public Nullable<double> NUM11 { get; set; }
        public Nullable<double> NUM12 { get; set; }
        public string TEXT1 { get; set; }
        public string TEXT2 { get; set; }
        public string TEXT3 { get; set; }
        public Nullable<System.DateTime> DATE1 { get; set; }
        public Nullable<System.DateTime> DATE2 { get; set; }
        public Nullable<System.DateTime> DATE3 { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    }
}
