//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class BEYAN
    {
        public string SASE_NO { get; set; }
        public string VD { get; set; }
        public string VD_IL { get; set; }
        public string VD_KOD { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string TRH_GUN { get; set; }
        public string TRH_AY { get; set; }
        public string TRH_YIL { get; set; }
        public string CINS { get; set; }
        public string MARKA { get; set; }
        public string TIP { get; set; }
        public string MODEL { get; set; }
        public string MOTOR_NO { get; set; }
        public string MOTOR_GUC { get; set; }
        public string AGIRLIK { get; set; }
        public string RENK { get; set; }
        public string SIL_HACIM { get; set; }
        public string ISTIHAP { get; set; }
        public string MUK_VKN { get; set; }
        public string MUK_UNVAN { get; set; }
        public string MUK_ADI { get; set; }
        public string MUK_TIP_1 { get; set; }
        public string MUK_TIP_2 { get; set; }
        public string MUK_TIP_3 { get; set; }
        public string MUK_TIP_4 { get; set; }
        public string MUK_TIP_5 { get; set; }
        public string IST_1 { get; set; }
        public string IST_2 { get; set; }
        public string IST_3 { get; set; }
        public string IST_4 { get; set; }
        public string IST_5 { get; set; }
        public string OTV_MAT { get; set; }
        public string OTV { get; set; }
        public string OTV_TUT { get; set; }
        public Nullable<double> OTV_IST_TUT { get; set; }
        public string OTV_IST { get; set; }
        public string AL_VKN { get; set; }
        public string AL_UNVAN { get; set; }
        public string AL_ADI { get; set; }
        public string AL_BABAADI { get; set; }
        public string AL_ANAADI { get; set; }
        public string AL_DYERI { get; set; }
        public Nullable<System.DateTime> AL_DTAR { get; set; }
        public string AL_DT_GUN { get; set; }
        public string AL_DT_AY { get; set; }
        public string AL_DT_YIL { get; set; }
        public string AL_UYRUGU { get; set; }
        public string AL_IKADR1 { get; set; }
        public string AL_IKADR2 { get; set; }
        public string AL_IKPK { get; set; }
        public string AL_ISADR1 { get; set; }
        public string AL_ISADR2 { get; set; }
        public string AL_ISPK { get; set; }
        public string AL_IKTEL { get; set; }
        public string AL_ISTEL { get; set; }
        public string VEREN_1 { get; set; }
        public string VEREN_2 { get; set; }
        public string VEREN_3 { get; set; }
        public string VEREN_4 { get; set; }
        public string VEREN_5 { get; set; }
        public string VEREN_UNVAN { get; set; }
        public string TEXT_1 { get; set; }
        public string TEXT_2 { get; set; }
        public string TEXT_3 { get; set; }
        public string TEXT_4 { get; set; }
        public string TEXT_5 { get; set; }
        public Nullable<double> NUM_1 { get; set; }
        public Nullable<double> NUM_2 { get; set; }
        public Nullable<double> NUM_3 { get; set; }
        public Nullable<double> NUM_4 { get; set; }
        public Nullable<double> NUM_5 { get; set; }
        public Nullable<System.DateTime> DATE_1 { get; set; }
        public Nullable<System.DateTime> DATE_2 { get; set; }
        public Nullable<System.DateTime> DATE_3 { get; set; }
        public string MUK_TEL { get; set; }
        public string TIK_1 { get; set; }
        public string TIK_2 { get; set; }
        public string TIK_3 { get; set; }
        public string TIK_4 { get; set; }
        public string TIK_5 { get; set; }
        public string TIK_6 { get; set; }
        public string TIK_7 { get; set; }
        public string TIK_8 { get; set; }
        public string TIK_9 { get; set; }
        public string TIK_10 { get; set; }
        public string TEXT_6 { get; set; }
        public string TEXT_7 { get; set; }
        public string TEXT_8 { get; set; }
        public string TEXT_9 { get; set; }
        public string TEXT_10 { get; set; }
        public Nullable<double> NUM_6 { get; set; }
        public Nullable<double> NUM_7 { get; set; }
        public Nullable<double> NUM_8 { get; set; }
        public Nullable<double> NUM_9 { get; set; }
        public Nullable<double> NUM_10 { get; set; }
        public string KANGRUBU { get; set; }
        public string SINIFI { get; set; }
        public string TIP_ONAYNO { get; set; }
        public string AZAMI_YUKLU_KUTLE { get; set; }
        public string KATAR_YUKLU_KUTLE { get; set; }
        public string ARAC_GRUP { get; set; }
        public string OTURMA_YERI { get; set; }
    }
}
