//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIRIM
    {
        public string BIRIM_ADI { get; set; }
        public string EF_BIRIM_ADI { get; set; }
        public string ISO_KOD { get; set; }
    }
}
