//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLUM
    {
        public double ISYERINO { get; set; }
        public double DEPNO { get; set; }
        public string BOLUM_NO { get; set; }
        public string BOLUM_ADI { get; set; }
    }
}
