//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class BORDRO
    {
        public double ISYERINO { get; set; }
        public double BORDRONO { get; set; }
        public string AY { get; set; }
        public double PERSNO { get; set; }
        public string PERSSICNO { get; set; }
        public Nullable<double> FIILICG { get; set; }
        public string EKSIKGUNNED { get; set; }
        public Nullable<double> HFTSN { get; set; }
        public Nullable<double> GNLTATIL { get; set; }
        public Nullable<double> KLNIZIN { get; set; }
        public Nullable<double> KLNMIZIN { get; set; }
        public Nullable<double> ZRNTATIL { get; set; }
        public Nullable<double> SIGRTGUN { get; set; }
        public Nullable<double> FAZLAM1 { get; set; }
        public Nullable<double> FAZLAM2 { get; set; }
        public Nullable<double> FAZLAM3 { get; set; }
        public Nullable<double> AVANS1 { get; set; }
        public Nullable<double> AVANS2 { get; set; }
        public Nullable<double> KESINTI1 { get; set; }
        public Nullable<double> KESINTI2 { get; set; }
        public Nullable<double> IKRAMIYE { get; set; }
        public Nullable<double> IZINUCRET { get; set; }
        public Nullable<double> VERGIGUN { get; set; }
        public Nullable<short> YIL { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string ASGARI_UCRETLI { get; set; }
    }
}
