//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class BORD_EKI
    {
        public double ISYERINO { get; set; }
        public double BORDRONO { get; set; }
        public string AY { get; set; }
        public string PERSSICNO { get; set; }
        public string EKKOD { get; set; }
        public Nullable<double> PERSNO { get; set; }
        public string EKODEME { get; set; }
        public string SSK { get; set; }
        public string DP { get; set; }
        public string GV { get; set; }
        public Nullable<double> GVSINIRI { get; set; }
        public Nullable<double> TUTAR { get; set; }
        public string BRUTMU { get; set; }
        public string M_EKGELIR { get; set; }
        public Nullable<short> YIL { get; set; }
    }
}
