//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class BORDRODETAY
    {
        public double ISYERINO { get; set; }
        public string CAY { get; set; }
        public string DEPKOD { get; set; }
        public string BOLUMKOD { get; set; }
        public double PERSNO { get; set; }
        public string DEPARTMANADI { get; set; }
        public string PERSICNO { get; set; }
        public string ADISOYADI { get; set; }
        public Nullable<double> SIGGUN { get; set; }
        public string CINSIYET { get; set; }
        public Nullable<double> SIGMATRAH { get; set; }
        public Nullable<double> YILLIKIZIN { get; set; }
        public Nullable<double> KAZASIGMAT { get; set; }
        public Nullable<double> HAS1 { get; set; }
        public Nullable<double> HAS2 { get; set; }
        public Nullable<double> IHTIYAR1 { get; set; }
        public Nullable<double> IHTIYAR2 { get; set; }
        public Nullable<double> ANALIK { get; set; }
        public Nullable<double> KAZA { get; set; }
        public Nullable<double> ISSIZLIK1 { get; set; }
        public Nullable<double> ISSIZLIK2 { get; set; }
        public Nullable<double> TOPLAM1 { get; set; }
        public Nullable<double> TOPLAM2 { get; set; }
        public string OZELDURUMKOD { get; set; }
        public Nullable<short> CYIL { get; set; }
        public Nullable<decimal> MATDEVIR1 { get; set; }
        public Nullable<decimal> MATDEVIR2 { get; set; }
        public Nullable<decimal> MATFAZLA1 { get; set; }
        public Nullable<decimal> MATFAZLA2 { get; set; }
    }
}
