//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRD_HES
    {
        public double ISYERINO { get; set; }
        public double BORDRONO { get; set; }
        public string AY { get; set; }
        public string PERSSICNO { get; set; }
        public Nullable<double> PERSNO { get; set; }
        public Nullable<double> BRUTUCRET { get; set; }
        public Nullable<double> FAZLAMESAI { get; set; }
        public Nullable<double> EKODEMELER { get; set; }
        public Nullable<double> TOPLAMUCRET { get; set; }
        public Nullable<double> OZELGIDERIND { get; set; }
        public Nullable<double> OZELDP { get; set; }
        public Nullable<double> SSKMATRAH { get; set; }
        public Nullable<double> SSKISCI { get; set; }
        public Nullable<double> SSKISVEREN { get; set; }
        public Nullable<double> ISSIZLIKISCI { get; set; }
        public Nullable<double> ISSIZLIKISVEREN { get; set; }
        public Nullable<double> GVM { get; set; }
        public Nullable<double> GV { get; set; }
        public Nullable<double> DPV { get; set; }
        public Nullable<double> RKT { get; set; }
        public Nullable<double> OKT { get; set; }
        public Nullable<double> NETMAAS { get; set; }
        public Nullable<double> SSKGORUNEN { get; set; }
        public Nullable<double> FIS_NO { get; set; }
        public Nullable<double> KUMVERGIMAT { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<double> OZEL_SIG_PRM { get; set; }
        public Nullable<double> ASG_GEC_IND { get; set; }
        public Nullable<short> YIL { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
    }
}
