//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARIPK
    {
        public int ID { get; set; }
        public string CARI_KOD { get; set; }
        public string EF_POSTAKUTUSU { get; set; }
        public string PK_ISIM { get; set; }
        public Nullable<byte> PK_DEFAULT { get; set; }
        public Nullable<byte> EF_MUKELLEF { get; set; }
        public Nullable<byte> EI_MUKELLEF { get; set; }
    }
}
