//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARIPER
    {
        public string CP_CARI_KOD { get; set; }
        public string CP_PER_AD { get; set; }
        public string CP_GOREV { get; set; }
        public string CP_TEL_DAHILI { get; set; }
        public string CP_GSM1 { get; set; }
        public string CP_GSM2 { get; set; }
        public string CP_PLAKA { get; set; }
        public string CP_ACIKLAMA { get; set; }
    }
}
