//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARIBANKA
    {
        public string CARI_KOD { get; set; }
        public short CB_NO { get; set; }
        public string CB_BANKA { get; set; }
        public string CB_SUBE { get; set; }
        public string CB_HESAP_NO { get; set; }
        public string CB_HESAP_DVZ { get; set; }
        public string CB_HESAP_TUR { get; set; }
        public string CB_IBAN { get; set; }
        public string CB_ACIKLAMA { get; set; }
    }
}
