//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARIHRK_BAK
    {
        public double CARI_NO { get; set; }
        public Nullable<int> SIRANO { get; set; }
        public string CARI_KOD { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string CRHRK_TUR { get; set; }
        public Nullable<double> REF_NO { get; set; }
        public Nullable<double> PORTFOYNO { get; set; }
        public Nullable<System.DateTime> VADE_TRH { get; set; }
        public Nullable<double> BORC { get; set; }
        public Nullable<double> ALACAK { get; set; }
        public Nullable<double> BORC_USD { get; set; }
        public Nullable<double> ALACAK_USD { get; set; }
        public Nullable<double> BORC_DVZ { get; set; }
        public Nullable<double> ALACAK_DVZ { get; set; }
        public string DOVIZ_KODU { get; set; }
        public string PARA_BAZ { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<double> TL_KURDEGER { get; set; }
        public Nullable<double> TL_USDEGER { get; set; }
        public string BELGE_NO { get; set; }
        public string ODE_KOD { get; set; }
        public Nullable<double> FIS_NO { get; set; }
        public string KASAKOD { get; set; }
        public string ALT_TIP { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public string LOG_USER { get; set; }
        public string LOG_SQL_USER { get; set; }
        public Nullable<byte> LOG_STATE { get; set; }
    }
}
