//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHFIFO
    {
        public int ROW_ID { get; set; }
        public double CARI_NO { get; set; }
        public int SIRANO { get; set; }
        public double KCARI_NO { get; set; }
        public int KSIRANO { get; set; }
        public string CARI_KOD { get; set; }
        public Nullable<double> BORC { get; set; }
        public Nullable<double> ALACAK { get; set; }
        public Nullable<System.DateTime> VADE_TRH { get; set; }
        public Nullable<System.DateTime> KVADE_TRH { get; set; }
    }
}
