//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLAIMD
    {
        public double CD_CLAIMNO { get; set; }
        public short CD_SIRANO { get; set; }
        public string CD_HATAKOD { get; set; }
        public string CD_HATAACIK { get; set; }
        public string CD_TAMIRKOD { get; set; }
        public string CD_ONARKOD { get; set; }
        public Nullable<double> CD_TPLISCILIK { get; set; }
        public Nullable<double> CD_TPLPARCA { get; set; }
        public string CD_IMALATCI { get; set; }
        public string CD_ISLEMTIP { get; set; }
        public Nullable<double> CS_METCOST { get; set; }
    }
}
