//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLAIMI
    {
        public double CI_CLAIMNO { get; set; }
        public short CI_HATANO { get; set; }
        public short CI_TIP { get; set; }
        public short CI_SIRANO { get; set; }
        public Nullable<System.DateTime> CI_TARIH { get; set; }
        public string CI_KOD { get; set; }
        public string CI_AD { get; set; }
        public Nullable<double> CI_FIYAT { get; set; }
        public Nullable<double> CI_SURE { get; set; }
        public Nullable<double> CI_MIKTAR { get; set; }
        public string CI_EKKOD { get; set; }
        public Nullable<double> CI_EKSURE { get; set; }
        public Nullable<double> CI_KM { get; set; }
        public Nullable<double> CI_TUTAR { get; set; }
        public string CI_ISLEMTIP { get; set; }
        public string CI_ONARKOD { get; set; }
        public string CI_TEMIN { get; set; }
        public string CI_ANA { get; set; }
        public Nullable<double> CI_TORAN { get; set; }
        public Nullable<double> CI_TTUTAR { get; set; }
        public Nullable<double> CI_KORAN { get; set; }
        public Nullable<double> CI_KTUTAR { get; set; }
        public string CI_FATNO { get; set; }
        public Nullable<System.DateTime> CI_FATARIH { get; set; }
        public string CI_FATFIRM { get; set; }
        public string CI_ODEKOD { get; set; }
        public string CI_ACIKLA { get; set; }
        public Nullable<double> CI_UORAN { get; set; }
        public Nullable<double> CI_GUNTUTAR { get; set; }
        public Nullable<byte> CI_BODE { get; set; }
        public Nullable<short> CI_REFSIRA { get; set; }
        public string CI_PURETKOD { get; set; }
    }
}
