//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLAIMEXM
    {
        public double EX_NO { get; set; }
        public Nullable<System.DateTime> EX_TARIH { get; set; }
        public Nullable<System.DateTime> EX_TARIH2 { get; set; }
        public Nullable<short> EX_CLADET { get; set; }
        public Nullable<double> EX_TUTAR { get; set; }
        public Nullable<byte> EX_STATU { get; set; }
        public string EX_DONEM { get; set; }
        public Nullable<System.DateTime> EX_FATRH { get; set; }
        public string EX_FATNO { get; set; }
        public Nullable<System.DateTime> EX_ALTRH { get; set; }
        public Nullable<System.DateTime> EX_VERTRH { get; set; }
    }
}
