//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLAIMM
    {
        public double CL_CLAIMNO { get; set; }
        public Nullable<short> CL_SAYFA { get; set; }
        public string CL_ISEMRI { get; set; }
        public Nullable<System.DateTime> CL_TAMIRTRH { get; set; }
        public Nullable<System.DateTime> CL_TESLIMTRH { get; set; }
        public string CL_SASE { get; set; }
        public string CL_CARI { get; set; }
        public string CL_PLAKA { get; set; }
        public Nullable<double> CL_KM { get; set; }
        public string CL_ARACTIP { get; set; }
        public string CL_GARTIP { get; set; }
        public Nullable<System.DateTime> CL_BASTRH { get; set; }
        public Nullable<System.DateTime> CL_BASSAAT { get; set; }
        public Nullable<System.DateTime> CL_BITTRH { get; set; }
        public Nullable<System.DateTime> CL_BITSAAT { get; set; }
        public string CL_ACIKLA { get; set; }
        public string CL_ONAY { get; set; }
        public bool CL_AKTARILDI { get; set; }
        public string CL_MER_ONAY { get; set; }
        public string CL_FATURA { get; set; }
        public string CL_DURUM { get; set; }
        public Nullable<double> CL_TPLISSURE { get; set; }
        public Nullable<double> CL_TPLISCILIK { get; set; }
        public Nullable<double> CL_TPLPARCA { get; set; }
        public string CL_MOTOR { get; set; }
        public Nullable<System.DateTime> CL_GONTRH { get; set; }
        public string CL_DONUSKOD { get; set; }
        public string CL_DONUSNOT { get; set; }
        public Nullable<System.DateTime> CL_DONUSTRH { get; set; }
        public string CL_PERKOD { get; set; }
        public string CL_MUDKOD { get; set; }
        public Nullable<System.DateTime> CL_ARIZATRH { get; set; }
        public Nullable<double> CL_ARIZAKM { get; set; }
        public Nullable<System.DateTime> CL_PARTRH { get; set; }
        public Nullable<double> CL_PARKM { get; set; }
        public string CL_SIKAYETKOD { get; set; }
        public string CL_GERNDNKOD { get; set; }
        public string CL_ONAYTIP1 { get; set; }
        public string CL_ONAYTIP2 { get; set; }
        public string CL_ONAYKOD { get; set; }
        public string CL_TG { get; set; }
        public string CL_HARICITIP1 { get; set; }
        public string CL_HARICITIP2 { get; set; }
        public string CL_KAMPNO { get; set; }
        public string CL_ZIYARET { get; set; }
        public string CL_YP { get; set; }
        public string CL_YPNO { get; set; }
        public Nullable<System.DateTime> CL_YPOOTRH { get; set; }
        public Nullable<double> CL_YPOKM { get; set; }
        public string CL_YPOIE { get; set; }
        public string CL_YPFIRMA { get; set; }
        public string CL_YPFIRKOD { get; set; }
        public string CL_NKOD { get; set; }
        public string CL_CKOD { get; set; }
        public string CL_OZELNOT { get; set; }
        public Nullable<double> CL_TPLNORISC { get; set; }
        public Nullable<double> CL_TPLHARICI { get; set; }
        public Nullable<double> CL_TPLKDV { get; set; }
        public Nullable<double> CL_TPL { get; set; }
        public Nullable<double> CL_TPLISK_ISC { get; set; }
        public Nullable<double> CL_TPLISK_PRC { get; set; }
        public string CL_DISSNO { get; set; }
        public Nullable<double> CL_VERSIP_NO { get; set; }
        public string CL_AKOD { get; set; }
        public string CL_BKOD { get; set; }
        public string CL_OPERKOD { get; set; }
        public string CL_MERPER { get; set; }
        public string CL_SANZIMAN { get; set; }
        public Nullable<System.DateTime> CL_FORMTRH { get; set; }
        public string CL_SIKAYET1 { get; set; }
        public string CL_SIKAYET2 { get; set; }
        public string CL_TESHIS1 { get; set; }
        public string CL_TESHIS2 { get; set; }
        public string CL_TAMIR1 { get; set; }
        public string CL_TAMIR2 { get; set; }
        public string CL_MUSAD { get; set; }
        public string CL_ADR1 { get; set; }
        public string CL_ADR2 { get; set; }
        public string CL_PK { get; set; }
        public string CL_SEMT { get; set; }
        public string CL_IL { get; set; }
        public string CL_TEL1 { get; set; }
        public string CL_TEL2 { get; set; }
        public string CL_TEL3 { get; set; }
        public string CL_CINSIYET { get; set; }
        public Nullable<System.DateTime> CL_GELTRH { get; set; }
        public Nullable<double> CL_TET1 { get; set; }
        public Nullable<double> CL_TET2 { get; set; }
        public Nullable<double> CL_TET3 { get; set; }
        public Nullable<double> CL_TET4 { get; set; }
        public Nullable<double> CL_TET5 { get; set; }
        public Nullable<double> CL_TET6 { get; set; }
        public Nullable<double> CL_TTT { get; set; }
        public Nullable<double> CL_KET1 { get; set; }
        public Nullable<double> CL_KET2 { get; set; }
        public Nullable<double> CL_KET3 { get; set; }
        public Nullable<double> CL_KET4 { get; set; }
        public Nullable<double> CL_KET5 { get; set; }
        public Nullable<double> CL_KET6 { get; set; }
        public Nullable<double> CL_KTT { get; set; }
        public string CL_ONAYPER { get; set; }
        public Nullable<System.DateTime> CL_ONAYTRH { get; set; }
        public string CL_ONAYNOT { get; set; }
        public string CL_RAPKOD { get; set; }
        public string CL_RAPPER { get; set; }
        public Nullable<System.DateTime> CL_RAPTRH { get; set; }
        public string CL_RAPNOT { get; set; }
        public string CL_FATFORM { get; set; }
        public Nullable<double> CL_FATFORMNO { get; set; }
        public string CL_FATNO { get; set; }
        public Nullable<System.DateTime> CL_FATTRH { get; set; }
        public string CL_FATTIP { get; set; }
        public Nullable<double> CL_FATTUTAR { get; set; }
        public Nullable<short> CL_MODELYIL { get; set; }
        public string CL_TRBLNO { get; set; }
        public string CL_TRIENO { get; set; }
        public string CL_TRSPNO { get; set; }
        public Nullable<double> CL_EKSTRENO { get; set; }
        public Nullable<System.DateTime> CL_ILETTRH { get; set; }
        public string CL_ILETDRM { get; set; }
    }
}
