//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLAIMDI
    {
        public double CS_CLAIMNO { get; set; }
        public short CS_SIRANO { get; set; }
        public string CS_ISCILIK { get; set; }
        public Nullable<double> CS_MIKTAR { get; set; }
        public Nullable<double> CS_FIYAT { get; set; }
        public Nullable<double> CS_ISKONTO { get; set; }
        public string CS_ANA { get; set; }
        public Nullable<double> CS_SURE { get; set; }
        public string CS_SAGSOL { get; set; }
        public Nullable<short> CS_REFSIRA { get; set; }
        public string CS_BOYAKOD { get; set; }
        public string CS_HARICI { get; set; }
        public string CS_HARICIKOD { get; set; }
        public Nullable<byte> CS_STATU { get; set; }
    }
}
