//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLGARTIP
    {
        public string GT_KOD { get; set; }
        public string GT_AD { get; set; }
        public string GT_SINIF { get; set; }
        public Nullable<double> GT_LIMIT { get; set; }
    }
}
