//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPO
    {
        public string DEPO_KODU { get; set; }
        public string DEPO_ADI { get; set; }
        public string DEPO_YERI { get; set; }
        public string DEPO_TIP { get; set; }
        public Nullable<short> SIRA { get; set; }
        public Nullable<short> DEP1 { get; set; }
        public Nullable<short> DEP2 { get; set; }
        public Nullable<short> DEP3 { get; set; }
        public Nullable<short> DEP4 { get; set; }
        public Nullable<short> DEP5 { get; set; }
        public Nullable<short> DEP6 { get; set; }
        public Nullable<short> DEP7 { get; set; }
        public Nullable<short> DEP8 { get; set; }
        public Nullable<short> DEP9 { get; set; }
        public Nullable<short> DEP10 { get; set; }
    }
}
