//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISALIS
    {
        public double ALIS_NO { get; set; }
        public string CARIKOD { get; set; }
        public Nullable<double> BRUTTUT { get; set; }
        public string TIP { get; set; }
        public Nullable<double> INDIRIM { get; set; }
        public Nullable<double> YUZDE { get; set; }
        public Nullable<double> INR_YUZD { get; set; }
        public Nullable<double> KDVTUT { get; set; }
        public Nullable<double> NETTUT { get; set; }
        public Nullable<System.DateTime> FATARIH { get; set; }
        public Nullable<System.DateTime> SAAT { get; set; }
        public Nullable<System.DateTime> VADETRH { get; set; }
        public string FATIRSNO { get; set; }
        public Nullable<double> MASRAF { get; set; }
        public Nullable<double> MERKEZ_SNO { get; set; }
        public Nullable<double> FIS_NO { get; set; }
        public string ODE_KOD { get; set; }
        public Nullable<System.DateTime> IRSTARIH { get; set; }
        public string IRS_NO { get; set; }
        public Nullable<byte> ENT_KOD { get; set; }
        public string MERKEZ_BAYI { get; set; }
        public string MBEL_NO { get; set; }
        public string KONTROL { get; set; }
        public byte AKTARILDI { get; set; }
        public string KDVTEV { get; set; }
        public Nullable<double> KDVTEV_TUT { get; set; }
        public Nullable<double> MASRAFTUT_TL { get; set; }
        public string DOVIZ_KODU { get; set; }
        public Nullable<double> TL_KURDEGER { get; set; }
        public Nullable<double> NETTUT_DVZ { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_USER { get; set; }
        public string PER_KOD { get; set; }
        public string ODE_TIP { get; set; }
        public string ACIKLAMA { get; set; }
        public string SASE_NO { get; set; }
        public string DA_CARI_KOD { get; set; }
        public Nullable<short> SUBEKODU { get; set; }
        public string PLAKA_NO { get; set; }
        public Nullable<byte> PRO_FATURA { get; set; }
        public Nullable<System.DateTime> PRO_FATURA_TRH { get; set; }
        public string PRO_FATURA_PER { get; set; }
    }
}
