//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPRTMAN
    {
        public double ISYERINO { get; set; }
        public double DEPNO { get; set; }
        public string DEPRT_KOD { get; set; }
        public string VAR_KODU { get; set; }
        public string DEPARTMAN_ISMI { get; set; }
        public Nullable<double> KAZA_OR { get; set; }
        public string ADRES1 { get; set; }
        public string TAS_TES_SIC_NO { get; set; }
        public string TAS_TES_KES { get; set; }
        public string TEHDER { get; set; }
        public string TEHSINI { get; set; }
        public string HSICNO { get; set; }
        public string ISKOLKODSICNO { get; set; }
        public string BOLKODSICNO { get; set; }
        public string SIRASICNO { get; set; }
        public string ILKODSICNO { get; set; }
        public string ILCEKODSICNO { get; set; }
        public string Il { get; set; }
        public string YAPILANIS { get; set; }
        public string TELNO { get; set; }
        public string UCRET_TIPI { get; set; }
        public Nullable<double> HCG { get; set; }
        public Nullable<double> GCS { get; set; }
        public Nullable<double> HCS { get; set; }
        public string M_BRUT { get; set; }
        public string M_SSK_ISVER_PR { get; set; }
        public string M_SSK_ODE_PR { get; set; }
        public string M_DAMGAV { get; set; }
        public string M_GELIRV { get; set; }
        public string M_NET { get; set; }
        public string M_EK_KESINTI { get; set; }
        public string M_ODE_ISIZ_SG_PR { get; set; }
        public string M_ISIZ_SG_ISV_KES { get; set; }
        public string M_ODESSKP_ISVER { get; set; }
        public string M_ODESSKP_ISCI { get; set; }
        public string M_ODE_ISIZ_P_ISCI { get; set; }
        public string M_ODE_ISIZ_P_ISVER { get; set; }
        public string M_EKGELIR { get; set; }
        public string M_IHBAR { get; set; }
        public string M_KIDEM { get; set; }
        public string M_TTF_ISVER { get; set; }
        public string M_ODETAS { get; set; }
        public string M_OGI { get; set; }
        public string M_OGIDAMGAV { get; set; }
        public string M_ODEOGI { get; set; }
        public string M_FAZLAMESAI { get; set; }
        public string M_AGI { get; set; }
        public Nullable<short> ANADEP { get; set; }
        public string M_AVANS { get; set; }
        public string M_EK_KESINTI2 { get; set; }
    }
}
