//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRTAYBLD
    {
        public double ISYERINO { get; set; }
        public double DONEM { get; set; }
        public double PERSNO { get; set; }
        public string IS_SICNO { get; set; }
        public string ADI { get; set; }
        public string SOYADI { get; set; }
        public string GIRISTAR { get; set; }
        public Nullable<double> TOPGUN { get; set; }
        public Nullable<double> TOPKAZANC { get; set; }
        public string CIKISTAR { get; set; }
        public Nullable<double> GUN1 { get; set; }
        public Nullable<double> KAZANC1 { get; set; }
        public Nullable<double> GUN2 { get; set; }
        public Nullable<double> KAZANC2 { get; set; }
        public Nullable<double> GUN3 { get; set; }
        public Nullable<double> KAZANC3 { get; set; }
        public Nullable<double> GUN4 { get; set; }
        public Nullable<double> KAZANC4 { get; set; }
    }
}
