//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class EF_LOG
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> IslemTarih { get; set; }
        public string Islem { get; set; }
        public string ReferansNo { get; set; }
        public string FaturaNo { get; set; }
        public string ZarfETTN { get; set; }
        public string FaturaETTN { get; set; }
        public string Aciklama { get; set; }
    }
}
