//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class EI_MUKELLEF
    {
        public int ID { get; set; }
        public string VERGI_NO { get; set; }
        public string POSTA_KUTUSU { get; set; }
        public string UNVAN { get; set; }
        public string MUKELLEF_TIPI { get; set; }
        public Nullable<System.DateTime> KAYIT_TARIH { get; set; }
    }
}
