//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class EKIM
    {
        public string FIRMA_ADI { get; set; }
        public string YETKILI_ADI { get; set; }
        public string YETKILI_SOYAD { get; set; }
        public string ADR1 { get; set; }
        public string ADR2 { get; set; }
        public string ADR3 { get; set; }
        public string TLF { get; set; }
        public string FAX { get; set; }
        public string VERGINO { get; set; }
        public string VERGIDAIRE { get; set; }
        public Nullable<short> SUBESAY { get; set; }
        public Nullable<System.DateTime> KURULUS_TRH { get; set; }
        public string TICSICNO { get; set; }
        public Nullable<System.DateTime> TIC_GAZTRH { get; set; }
        public string TIC_GAZ_NUM { get; set; }
        public string XXX { get; set; }
        public string OZEL { get; set; }
        public string ACE { get; set; }
        public string UYRUKLUGU { get; set; }
        public string IL { get; set; }
        public string ILCE { get; set; }
        public string ULKE { get; set; }
        public string SOKAK { get; set; }
        public string KAPI_NO { get; set; }
        public string DAIRE_NO { get; set; }
        public string WEB { get; set; }
        public byte[] FIRMALOGO { get; set; }
        public string TS { get; set; }
        public Nullable<double> KO { get; set; }
        public string TD { get; set; }
        public Nullable<double> GCS { get; set; }
        public Nullable<double> HCG { get; set; }
        public string MERKEZSSKSICNO { get; set; }
        public Nullable<double> YUVARLAMA { get; set; }
        public string KIMLIKNO { get; set; }
        public string WEB_ADRES { get; set; }
    }
}
