//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class EKODE_MUH
    {
        public double ISYERINO { get; set; }
        public string DEPARTMAN_KOD { get; set; }
        public string EKODE_KOD { get; set; }
        public string M_EKGELIR { get; set; }
    }
}
