//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAILSETTING
    {
        public int ROW_ID { get; set; }
        public string SMTP_HOST { get; set; }
        public Nullable<int> SMTP_PORT { get; set; }
        public string SMTP_SECURE { get; set; }
        public string SMTP_AUTH { get; set; }
        public string SMTP_USER { get; set; }
        public string SMTP_PW { get; set; }
    }
}
