//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENFHES
    {
        public string HKOD { get; set; }
        public string AKTIF { get; set; }
        public string FHKOD { get; set; }
        public Nullable<double> BIL_BAKIYE { get; set; }
        public Nullable<byte> HSP_SEKLI { get; set; }
    }
}
