//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENFISM
    {
        public byte DONEM_NO { get; set; }
        public string HKOD { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<byte> ONCEKI_DN { get; set; }
        public Nullable<System.DateTime> BAS_TRH { get; set; }
        public Nullable<System.DateTime> BIT_TRH { get; set; }
        public Nullable<double> BAKIYE { get; set; }
        public Nullable<double> TUTAR { get; set; }
        public Nullable<double> FISNO { get; set; }
        public Nullable<double> ENDEX { get; set; }
        public Nullable<byte> HSP_SEKLI { get; set; }
        public Nullable<double> DB_TUT { get; set; }
        public Nullable<double> DS_TUT { get; set; }
        public string SMM_HKOD { get; set; }
        public Nullable<double> SMM_TUT { get; set; }
        public Nullable<double> DUZ_TUTAR { get; set; }
        public Nullable<double> ENF_FARK { get; set; }
    }
}
