//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENFISD
    {
        public byte DONEM_NO { get; set; }
        public string MHKOD { get; set; }
        public short SIRANO { get; set; }
        public string HKOD { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<double> FISFISNO { get; set; }
        public Nullable<int> FISSIRANO { get; set; }
        public Nullable<double> TUTAR { get; set; }
        public Nullable<double> ENDEKS { get; set; }
        public Nullable<double> KATSAYI { get; set; }
        public Nullable<double> ROFM { get; set; }
        public Nullable<double> ESAS_TUTAR { get; set; }
        public Nullable<double> DUZ_TUTAR { get; set; }
        public Nullable<double> ENF_FARK { get; set; }
        public string FARK_HKOD { get; set; }
        public string ACIKLAMA { get; set; }
    }
}
