//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENVAN
    {
        public double STOK_NO { get; set; }
        public Nullable<double> GIR_FYT { get; set; }
        public Nullable<double> CIK_BFYT { get; set; }
        public Nullable<double> GIR_BFYTUSD { get; set; }
        public Nullable<double> CIK_BFYTUSD { get; set; }
        public Nullable<double> CIKMIK { get; set; }
        public Nullable<double> GIRMIK { get; set; }
        public Nullable<double> TUT { get; set; }
        public Nullable<double> TUTUSD { get; set; }
        public Nullable<double> AGIRFIYAT { get; set; }
        public Nullable<double> AGIRFIYAT_USD { get; set; }
        public Nullable<double> AGIRTUT { get; set; }
        public Nullable<double> AGIRTUT_USD { get; set; }
        public Nullable<double> TOPGUN { get; set; }
    }
}
