//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETKBPR
    {
        public string STOK_KOD_NO { get; set; }
        public string STOK_ADI_TR { get; set; }
        public string BARKOD { get; set; }
        public string BARK_TIP { get; set; }
        public Nullable<int> ADET { get; set; }
    }
}
