//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETKSEVK
    {
        public string ETIKETADI { get; set; }
        public Nullable<short> YBYukardan { get; set; }
        public Nullable<short> YBSoldan { get; set; }
        public Nullable<short> SKacSutun { get; set; }
        public Nullable<short> SKacSatir { get; set; }
        public Nullable<short> EtiketBoyu { get; set; }
        public Nullable<short> EtiketEni { get; set; }
        public Nullable<short> EtkAraUzEn { get; set; }
        public Nullable<short> EtkAraUzBoy { get; set; }
        public Nullable<short> YaziSOL { get; set; }
        public Nullable<short> YaziUST { get; set; }
        public string PROrien { get; set; }
        public Nullable<short> SayfaGenislik { get; set; }
        public Nullable<short> SayfaYukseklik { get; set; }
        public string FONTADI { get; set; }
        public Nullable<short> FONTSIZE { get; set; }
        public Nullable<int> COLOR { get; set; }
        public string STYLE { get; set; }
        public string SAYFA_TIPI { get; set; }
    }
}
