//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPER
    {
        public string IS_EMRI_NO { get; set; }
        public string SERVIS_KODU { get; set; }
        public Nullable<System.DateTime> HASAR_TRH { get; set; }
        public string SASE_NO { get; set; }
        public string PLAKA_NO { get; set; }
        public string MOTOR_NO { get; set; }
        public Nullable<double> KM { get; set; }
        public Nullable<System.DateTime> GARANTI_BAS { get; set; }
        public Nullable<short> GARANTI_YUZ { get; set; }
        public Nullable<short> KALAN_GRN_YUZ { get; set; }
        public Nullable<short> YPTUT_IKELDEGER { get; set; }
        public Nullable<double> KALAN_GRN_PUAN { get; set; }
        public Nullable<double> HASAR_PUANI { get; set; }
        public Nullable<double> DEVIR_MASRAFI { get; set; }
        public Nullable<double> IKI_EL_DEGERI { get; set; }
        public Nullable<double> SATIS_FYT { get; set; }
        public Nullable<double> YP_HARC_YUZDE { get; set; }
        public Nullable<double> YED_PAR_KYUZDE { get; set; }
        public Nullable<double> NET_KALAN_GPUAN { get; set; }
        public Nullable<double> T_ISCILIK_TUT { get; set; }
        public Nullable<double> T_ISCILIK_KDVLI { get; set; }
        public Nullable<double> T_YP_TUT { get; set; }
        public Nullable<double> T_YP_KDVLI { get; set; }
        public Nullable<double> HASAR_TUT { get; set; }
        public Nullable<double> T_HASAR_KDVLI { get; set; }
        public Nullable<System.DateTime> IBRA_TRH { get; set; }
        public string EHLIYET_NO { get; set; }
        public string KAZA_SEKLI { get; set; }
        public string SIG_ACENTA_KOD { get; set; }
        public string UC_SAH_PLAKA { get; set; }
        public string UC_SAH_MOTOR_NO { get; set; }
        public string UC_SAH_SASE_NO { get; set; }
        public string UC_SAH_EHLIYET { get; set; }
        public string SIGORTA_ADI { get; set; }
        public string SIGORTA_TEL { get; set; }
        public string SIGORTA_FAX { get; set; }
        public string SIG_POLICE_NO { get; set; }
        public string UC_SAH_SIG_ADI { get; set; }
        public string UC_SAH_ACENTA_KOD { get; set; }
        public string UC_SAH_POLICE_NO { get; set; }
        public Nullable<System.DateTime> SIG_BAS_TRH { get; set; }
        public Nullable<System.DateTime> SIG_BIT_TRH { get; set; }
        public Nullable<double> SIG_ALNCK_TUT { get; set; }
        public string HESAP_NO { get; set; }
        public Nullable<double> SIG_AL_TUT { get; set; }
        public Nullable<double> KALAN_HASAR_TUT { get; set; }
        public string KAL_MASRAF_NEREDEN { get; set; }
        public string SIG_DOSYA_NO { get; set; }
        public string ODEME_BANKA1 { get; set; }
        public string ODEME_BANKA2 { get; set; }
        public Nullable<System.DateTime> MAHKEME_MV_TRH { get; set; }
        public string EXP_AD_SOYAD { get; set; }
        public string EXP_TEL { get; set; }
        public string EXP_FAX { get; set; }
        public string PROTON_EXP_ADI { get; set; }
        public byte[] FOTO1 { get; set; }
        public byte[] FOTO2 { get; set; }
        public byte[] FOTO3 { get; set; }
        public byte[] FOTO4 { get; set; }
        public string NOTLAR { get; set; }
        public string NOTLAR2 { get; set; }
        public string NOTLAR3 { get; set; }
        public string NOTLAR4 { get; set; }
        public string GRKITAPNO { get; set; }
        public string KAMPANYA { get; set; }
        public string KAZARAP { get; set; }
        public string ALKOLRAP { get; set; }
        public string EHLIYET { get; set; }
        public string RUHSAT { get; set; }
        public string POLICE { get; set; }
        public string RESIM { get; set; }
        public string DIGER { get; set; }
        public bool AKTARILDI { get; set; }
        public string STATU { get; set; }
        public string ODEME_TIP { get; set; }
        public string SIGORTA_TIP { get; set; }
        public Nullable<double> PAR_ISK_TUT { get; set; }
        public Nullable<double> ISC_ISK_TUT { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_USER { get; set; }
        public string PER_KOD { get; set; }
        public Nullable<byte> RUCU { get; set; }
        public Nullable<short> PER_YUZDE { get; set; }
        public Nullable<decimal> PER_TUTAR { get; set; }
        public string IKAME_VAR { get; set; }
        public Nullable<int> IKAME_GUN { get; set; }
    }
}
