//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPERISC
    {
        public string IS_EMRI_NO { get; set; }
        public string ISCILIK_KOD { get; set; }
        public string ISCILIK_AD { get; set; }
        public Nullable<double> SURE { get; set; }
        public Nullable<double> BRFIYAT { get; set; }
        public Nullable<double> KDV { get; set; }
        public Nullable<double> TOPLAM { get; set; }
        public Nullable<double> ISK_ORAN { get; set; }
        public Nullable<double> FYT_DOVIZ { get; set; }
        public string DOVIZ_KODU { get; set; }
        public Nullable<double> TL_KURDEGER { get; set; }
    }
}
