//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPERTSTATUGECMIS
    {
        public string IS_EMRI_NO { get; set; }
        public int SIRANO { get; set; }
        public string ESKISTATU { get; set; }
        public string YENISTATU { get; set; }
        public System.DateTime TARIH { get; set; }
        public Nullable<System.DateTime> SAAT { get; set; }
    }
}
