//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPERTEVRAKLAR
    {
        public string IS_EMRI_NO { get; set; }
        public int SIRANO { get; set; }
        public Nullable<int> TIP { get; set; }
        public byte[] FOTO { get; set; }
        public string CSELECT { get; set; }
        public string EVRAK_ADI { get; set; }
    }
}
