//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIS
    {
        public double FISNO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string TUR { get; set; }
        public string FISNUMARA { get; set; }
        public string BELGENO { get; set; }
        public Nullable<double> BORC { get; set; }
        public Nullable<double> ALACAK { get; set; }
        public Nullable<short> AY { get; set; }
        public Nullable<double> YEVMIYE_NO { get; set; }
        public Nullable<double> ENT_REF_NO { get; set; }
        public string ENT_TIP { get; set; }
        public string MASRAFM_KOD { get; set; }
        public Nullable<double> MIKTAR { get; set; }
        public string ACIKLAMA { get; set; }
        public string IPTAL { get; set; }
        public Nullable<byte> KONS_DISI { get; set; }
        public Nullable<byte> KONS_AKTAR { get; set; }
        public Nullable<byte> KONS_DURUM { get; set; }
        public string KONS_FIRMA { get; set; }
        public Nullable<double> KONS_FISNO { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_USER { get; set; }
        public string BELGE_TUR { get; set; }
        public Nullable<byte> ED_STATU { get; set; }
        public string ED_GUID { get; set; }
        public string ED_DEFTERID { get; set; }
        public string CUSER { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<short> SIRKETNO { get; set; }
        public Nullable<short> SUBEKODU { get; set; }
        public Nullable<short> MYIL { get; set; }
    }
}
