//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class FISAYR
    {
        public double FISNO { get; set; }
        public int SIRANO { get; set; }
        public string FISNUMARA { get; set; }
        public string HSPKODU { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<double> ALACAK { get; set; }
        public Nullable<double> BORC { get; set; }
        public string DOVIZ_KOD { get; set; }
        public Nullable<double> TL_DEGERI { get; set; }
        public Nullable<double> DVZ_ALACAK { get; set; }
        public Nullable<double> DVZ_BORC { get; set; }
        public Nullable<double> YEVMIYE_NO { get; set; }
        public string TUR { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<short> AY { get; set; }
        public Nullable<double> ENT_REF_NO { get; set; }
        public string ENT_REF_TIP { get; set; }
        public Nullable<short> HSINIF { get; set; }
        public Nullable<short> HGRUBU { get; set; }
        public Nullable<short> KEBIR { get; set; }
        public string MUAVIN { get; set; }
        public string TALI { get; set; }
        public string DETAY { get; set; }
        public string MASRAFM_KOD { get; set; }
        public Nullable<double> MIKTAR { get; set; }
        public Nullable<double> KDV { get; set; }
        public string KDVH { get; set; }
        public Nullable<double> ALACAK_RDVZ { get; set; }
        public Nullable<double> BORC_RDVZ { get; set; }
        public Nullable<double> TLDVZR_DEGERI { get; set; }
        public string ENT_REF_BN { get; set; }
        public string GRUP1_KOD { get; set; }
        public int FA_ID { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_USER { get; set; }
        public string BELGE_NO { get; set; }
        public string BELGE_TUR { get; set; }
        public Nullable<double> BORCY { get; set; }
        public Nullable<double> ALACAKY { get; set; }
        public string GRUP_KOD { get; set; }
        public string MAS_PER { get; set; }
        public string BABS_KOD { get; set; }
        public Nullable<short> SIRKETNO { get; set; }
        public Nullable<short> SUBEKODU { get; set; }
        public Nullable<short> MYIL { get; set; }
    }
}
