//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class FISGA
    {
        public double HRK_NO { get; set; }
        public int SIRA_NO { get; set; }
        public string TIP { get; set; }
        public Nullable<double> STOK_NO { get; set; }
        public string KOD { get; set; }
        public Nullable<double> MIKTAR { get; set; }
        public Nullable<double> KDV { get; set; }
        public Nullable<double> KDV_TUT { get; set; }
        public string ACIKLAMA1 { get; set; }
        public string ACIKLAMA2 { get; set; }
        public Nullable<double> BORC { get; set; }
        public Nullable<double> BORC_USD { get; set; }
        public Nullable<double> BORC_DVZ { get; set; }
        public Nullable<double> ALACAK { get; set; }
        public Nullable<double> ALACAK_USD { get; set; }
        public Nullable<double> ALACAK_DVZ { get; set; }
        public string PARA_BAZ { get; set; }
        public string DOVIZ_CINS { get; set; }
        public Nullable<double> KUR_BAZ { get; set; }
        public Nullable<double> KUR_DVZ { get; set; }
        public string KASA_KOD { get; set; }
        public Nullable<double> FIS_NO { get; set; }
        public Nullable<double> ISIN_TUTARI { get; set; }
        public Nullable<double> VERGI_TUTARI { get; set; }
        public string MUH_KARSI { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_USER { get; set; }
        public string BANKA_KOD { get; set; }
    }
}
