//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class FISRP
    {
        public string KODU { get; set; }
        public string ACIKLAMA { get; set; }
        public string ACIKLAMA1 { get; set; }
        public string KARSIHKOD { get; set; }
        public Nullable<double> BAKIYEYUZDE { get; set; }
        public Nullable<double> ALACAKYUZDE { get; set; }
        public Nullable<double> BORCYUZDE { get; set; }
    }
}
