//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class FISTK
    {
        public double HRKNO { get; set; }
        public string TIP { get; set; }
        public string OZELKOD { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<double> BRUTTUT { get; set; }
        public Nullable<double> KDVTUT { get; set; }
        public Nullable<double> NETTUT { get; set; }
        public Nullable<double> BRUT_USD { get; set; }
        public Nullable<double> KDV_USD { get; set; }
        public Nullable<double> NET_USD { get; set; }
        public Nullable<double> USDFYT { get; set; }
        public string CIKDEPO { get; set; }
        public string GIRDEPO { get; set; }
        public string ACIKLAMA1 { get; set; }
        public string ACIKLAMA2 { get; set; }
        public string ACIKLAMA3 { get; set; }
        public string KULLANICI { get; set; }
        public string HRKDURUM { get; set; }
        public string PERSON_KOD { get; set; }
        public Nullable<double> FIS_NO { get; set; }
        public bool ONAY { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_USER { get; set; }
        public string MBEL_NO { get; set; }
        public string MBEL_NO_TK { get; set; }
        public Nullable<byte> TX_STATU { get; set; }
    }
}
