//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class FISTKAYR
    {
        public double HRKNO { get; set; }
        public int SIRANO { get; set; }
        public Nullable<double> STOK_NO { get; set; }
        public string STOK_ADI { get; set; }
        public string STOK_KOD_NO { get; set; }
        public string DEPO_KODU { get; set; }
        public Nullable<double> MIKTAR { get; set; }
        public Nullable<double> KDV { get; set; }
        public string KDV_DAHIL { get; set; }
        public Nullable<double> FIYAT { get; set; }
        public Nullable<double> FYT_USD { get; set; }
        public Nullable<double> FYT_DOVIZ { get; set; }
        public string DOVIZ_KODU { get; set; }
        public string PARA_BAZ { get; set; }
        public Nullable<double> TL_KURDEGER { get; set; }
        public Nullable<double> GER_TUT { get; set; }
        public Nullable<double> GER_TUT_USD { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_USER { get; set; }
        public string SERINO { get; set; }
    }
}
