//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class FISWIZD
    {
        public int SB_NO { get; set; }
        public int SB_SIRA { get; set; }
        public string HSP_BAS { get; set; }
        public string HSP_BIT { get; set; }
        public string HSP_KARSI { get; set; }
        public Nullable<byte> HSP_TUR { get; set; }
        public string ACIKLAMA { get; set; }
    }
}
