//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class FNSTNM
    {
        public int ID { get; set; }
        public string TANIM { get; set; }
        public string DURUM { get; set; }
        public Nullable<short> TIP { get; set; }
        public Nullable<int> BASLIKNO { get; set; }
    }
}
