//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRT
    {
        public string FRT_KODU { get; set; }
        public string MODEL_KODU { get; set; }
        public string FRT_ADI { get; set; }
        public string FRT_ING_ADI { get; set; }
        public string FRT_GRP_KODU { get; set; }
        public string FRT_GRP_ADI { get; set; }
        public Nullable<double> FRT_ZAMAN { get; set; }
        public Nullable<double> BIRIM_FIYAT_TL { get; set; }
        public Nullable<double> BIRIM_FIYAT_DVZ { get; set; }
        public string DOVIZ_KODU { get; set; }
        public Nullable<double> KDV { get; set; }
        public string KLEIM_TURU { get; set; }
        public string KBMY { get; set; }
        public string MUH_S { get; set; }
        public string MUH_IADE_S { get; set; }
        public string MUH_ISK_S { get; set; }
        public string MUH_KDV_S { get; set; }
        public string MUH_A { get; set; }
        public string MUH_IADE_A { get; set; }
        public string MUH_ISK_A { get; set; }
        public string MUH_KDV_A { get; set; }
        public string ALT_GRUP { get; set; }
        public string ALTER_KOD { get; set; }
        public string LOKAS_KOD { get; set; }
        public string PREW_KOD1 { get; set; }
        public string PREW_KOD2 { get; set; }
        public string ACIKLAMA1 { get; set; }
        public string ACIKLAMA2 { get; set; }
        public string ACIKLAMA3 { get; set; }
        public string MUH_GRSAT { get; set; }
        public string MUH_GRSATISK { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_USER { get; set; }
    }
}
