//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class FYTENDA
    {
        public short TIP { get; set; }
        public short YIL { get; set; }
        public short AY { get; set; }
        public Nullable<double> ENDEX { get; set; }
        public Nullable<double> ENDEX2 { get; set; }
        public Nullable<double> KATSAYI { get; set; }
        public Nullable<double> KATSAYI2 { get; set; }
    }
}
