//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class GELGIDM
    {
        public string SIRAKOD { get; set; }
        public string ACIKLAMA { get; set; }
        public string SINIF { get; set; }
        public string UGRUP { get; set; }
        public string AGRUP { get; set; }
        public string ANA { get; set; }
        public string TUR { get; set; }
        public string TIP { get; set; }
        public string SEVIYE { get; set; }
        public Nullable<double> OCAK { get; set; }
        public Nullable<double> SUBAT { get; set; }
        public Nullable<double> MART { get; set; }
        public Nullable<double> NISAN { get; set; }
        public Nullable<double> MAYIS { get; set; }
        public Nullable<double> HAZIRAN { get; set; }
        public Nullable<double> TEMMUZ { get; set; }
        public Nullable<double> AGUSTOS { get; set; }
        public Nullable<double> EYLUL { get; set; }
        public Nullable<double> EKIM { get; set; }
        public Nullable<double> KASIM { get; set; }
        public Nullable<double> ARALIK { get; set; }
        public Nullable<int> NUM { get; set; }
        public Nullable<double> OCAKO { get; set; }
        public Nullable<double> SUBATO { get; set; }
        public Nullable<double> MARTO { get; set; }
        public Nullable<double> NISANO { get; set; }
        public Nullable<double> MAYISO { get; set; }
        public Nullable<double> HAZIRANO { get; set; }
        public Nullable<double> TEMMUZO { get; set; }
        public Nullable<double> AGUSTOSO { get; set; }
        public Nullable<double> EYLULO { get; set; }
        public Nullable<double> EKIMO { get; set; }
        public Nullable<double> KASIMO { get; set; }
        public Nullable<double> ARALIKO { get; set; }
        public Nullable<double> OCAKB { get; set; }
        public Nullable<double> SUBATB { get; set; }
        public Nullable<double> MARTB { get; set; }
        public Nullable<double> NISANB { get; set; }
        public Nullable<double> MAYISB { get; set; }
        public Nullable<double> HAZIRANB { get; set; }
        public Nullable<double> TEMMUZB { get; set; }
        public Nullable<double> AGUSTOSB { get; set; }
        public Nullable<double> EYLULB { get; set; }
        public Nullable<double> EKIMB { get; set; }
        public Nullable<double> KASIMB { get; set; }
        public Nullable<double> ARALIKB { get; set; }
        public Nullable<double> OCAKR { get; set; }
        public Nullable<double> SUBATR { get; set; }
        public Nullable<double> MARTR { get; set; }
        public Nullable<double> NISANR { get; set; }
        public Nullable<double> MAYISR { get; set; }
        public Nullable<double> HAZIRANR { get; set; }
        public Nullable<double> TEMMUZR { get; set; }
        public Nullable<double> AGUSTOSR { get; set; }
        public Nullable<double> EYLULR { get; set; }
        public Nullable<double> EKIMR { get; set; }
        public Nullable<double> KASIMR { get; set; }
        public Nullable<double> ARALIKR { get; set; }
        public Nullable<double> OCAKOA { get; set; }
        public Nullable<double> SUBATOA { get; set; }
        public Nullable<double> MARTOA { get; set; }
        public Nullable<double> NISANOA { get; set; }
        public Nullable<double> MAYISOA { get; set; }
        public Nullable<double> HAZIRANOA { get; set; }
        public Nullable<double> TEMMUZOA { get; set; }
        public Nullable<double> AGUSTOSOA { get; set; }
        public Nullable<double> EYLULOA { get; set; }
        public Nullable<double> EKIMOA { get; set; }
        public Nullable<double> KASIMOA { get; set; }
        public Nullable<double> ARALIKOA { get; set; }
        public Nullable<double> OCAKBA { get; set; }
        public Nullable<double> SUBATBA { get; set; }
        public Nullable<double> MARTBA { get; set; }
        public Nullable<double> NISANBA { get; set; }
        public Nullable<double> MAYISBA { get; set; }
        public Nullable<double> HAZIRANBA { get; set; }
        public Nullable<double> TEMMUZBA { get; set; }
        public Nullable<double> AGUSTOSBA { get; set; }
        public Nullable<double> EYLULBA { get; set; }
        public Nullable<double> EKIMBA { get; set; }
        public Nullable<double> KASIMBA { get; set; }
        public Nullable<double> ARALIKBA { get; set; }
        public Nullable<double> OCAKRA { get; set; }
        public Nullable<double> SUBATRA { get; set; }
        public Nullable<double> MARTRA { get; set; }
        public Nullable<double> NISANRA { get; set; }
        public Nullable<double> MAYISRA { get; set; }
        public Nullable<double> HAZIRANRA { get; set; }
        public Nullable<double> TEMMUZRA { get; set; }
        public Nullable<double> AGUSTOSRA { get; set; }
        public Nullable<double> EYLULRA { get; set; }
        public Nullable<double> EKIMRA { get; set; }
        public Nullable<double> KASIMRA { get; set; }
        public Nullable<double> ARALIKRA { get; set; }
        public Nullable<double> OCAKA { get; set; }
        public Nullable<double> SUBATA { get; set; }
        public Nullable<double> MARTA { get; set; }
        public Nullable<double> NISANA { get; set; }
        public Nullable<double> MAYISA { get; set; }
        public Nullable<double> HAZIRANA { get; set; }
        public Nullable<double> TEMMUZA { get; set; }
        public Nullable<double> AGUSTOSA { get; set; }
        public Nullable<double> EYLULA { get; set; }
        public Nullable<double> EKIMA { get; set; }
        public Nullable<double> KASIMA { get; set; }
        public Nullable<double> ARALIKA { get; set; }
        public string SATMODEL { get; set; }
        public Nullable<int> RAPTIP { get; set; }
        public Nullable<int> ARACGRUP_ID { get; set; }
        public Nullable<int> RENK { get; set; }
    }
}
