//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class GELGIDT
    {
        public int GG_NO { get; set; }
        public string GG_TANIM { get; set; }
        public string GG_GRUP { get; set; }
        public string GG_YZDHSP { get; set; }
        public string GG_YZDCIRO { get; set; }
    }
}
