//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class GGHESAP
    {
        public string GGKOD { get; set; }
        public string GGTUR { get; set; }
        public string GGANA { get; set; }
        public string GGACIKLAMA { get; set; }
        public string GGTIP { get; set; }
        public string GGSEVIYE { get; set; }
    }
}
