//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIDER
    {
        public double GIDER_NO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string GIDER_TUR { get; set; }
        public string GIDER_TIP { get; set; }
        public string CARI_KOD { get; set; }
        public Nullable<double> TUTAR { get; set; }
        public string ACIKLAMA { get; set; }
    }
}
