//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIDERIND
    {
        public double ISYERINO { get; set; }
        public string DEPRT_NO { get; set; }
        public double PERSNO { get; set; }
        public string IS_SICNO { get; set; }
        public string ADISOYADI { get; set; }
        public Nullable<double> P1 { get; set; }
        public Nullable<double> P2 { get; set; }
        public Nullable<double> P3 { get; set; }
        public Nullable<double> P4 { get; set; }
        public Nullable<double> P5 { get; set; }
        public Nullable<double> P6 { get; set; }
        public Nullable<double> P7 { get; set; }
        public Nullable<double> P8 { get; set; }
        public Nullable<double> P9 { get; set; }
    }
}
