//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class GT
    {
        public string G_T { get; set; }
        public Nullable<short> G { get; set; }
        public Nullable<short> I { get; set; }
        public Nullable<short> S { get; set; }
        public Nullable<short> M { get; set; }
        public Nullable<short> K { get; set; }
        public Nullable<short> TG { get; set; }
        public Nullable<short> TM { get; set; }
    }
}
