//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class HASARKOD
    {
        public string HS_KOD { get; set; }
        public string HS_AD { get; set; }
        public string HS_ENG { get; set; }
        public string HS_TIP { get; set; }
    }
}
