//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSABLOND
    {
        public int HSD_HSB_ID { get; set; }
        public string HSD_HKOD { get; set; }
        public Nullable<short> HSD_KEBIR { get; set; }
        public string HSD_MUAVIN { get; set; }
        public string HSD_TALI { get; set; }
        public string HSD_DETAY { get; set; }
        public string HSD_ACIK1 { get; set; }
        public string HSD_ACIK2 { get; set; }
        public string HSD_ACIK3 { get; set; }
        public string HSD_HAD { get; set; }
    }
}
