//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSABLON
    {
        public int HSB_ID { get; set; }
        public string HSB_TANIM { get; set; }
        public Nullable<byte> HSB_TUR { get; set; }
        public Nullable<short> HSB_SAYI1 { get; set; }
        public Nullable<short> HSB_SAYI2 { get; set; }
        public Nullable<short> HSB_ADET { get; set; }
        public string HSB_ACIK1 { get; set; }
        public string HSB_ACIK2 { get; set; }
        public string HSB_ACIK3 { get; set; }
        public Nullable<short> HSB_KEBIR { get; set; }
        public string HSB_MUAVIN { get; set; }
        public string HSB_TALI { get; set; }
        public string HSB_DETAY { get; set; }
        public Nullable<byte> HSB_ANA_HES { get; set; }
    }
}
