//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSPLAN
    {
        public string HKOD { get; set; }
        public string HESAP_ADI { get; set; }
        public Nullable<short> HSINIF { get; set; }
        public Nullable<short> HGRUBU { get; set; }
        public Nullable<short> KEBIR { get; set; }
        public string MUAVIN { get; set; }
        public string TALI { get; set; }
        public string DETAY { get; set; }
        public string ACIKLAMA { get; set; }
        public string BAKIYETIP { get; set; }
        public string BILANCOTIP { get; set; }
        public string MASRAFM_KOD { get; set; }
        public string KURFHSP_KOD { get; set; }
        public string BIRIM { get; set; }
        public byte DEP1 { get; set; }
        public byte DEP2 { get; set; }
        public byte DEP3 { get; set; }
        public byte DEP4 { get; set; }
        public byte DEP5 { get; set; }
        public string ENFARK_HSP { get; set; }
        public string EHKOD { get; set; }
        public Nullable<byte> KONS_DISI { get; set; }
        public string VERGINO { get; set; }
        public string ULKEKOD { get; set; }
        public Nullable<byte> SEVIYE { get; set; }
        public Nullable<byte> SON_SEVIYE { get; set; }
        public string BAGLI_HSP { get; set; }
    }
}
