//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEALTTIP
    {
        public string IE_TIP { get; set; }
        public string IE_ALTTIP_KOD { get; set; }
        public string IE_ALTTIP_AD { get; set; }
    }
}
