//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IELSTOK
    {
        public int DOSYA_NO { get; set; }
        public string SASE_NO { get; set; }
        public string MOTOR_NO { get; set; }
        public string MARKA_KOD { get; set; }
        public string MODEL_KOD { get; set; }
        public string TIP_KOD { get; set; }
        public Nullable<short> MODEL_YIL { get; set; }
        public string PLAKA_NO { get; set; }
        public string RENK_KOD { get; set; }
        public Nullable<System.DateTime> TESCIL_TRH { get; set; }
        public Nullable<double> KM { get; set; }
        public Nullable<double> ALIS_FYT { get; set; }
        public Nullable<double> SATIS_FYT { get; set; }
        public Nullable<double> ALIS_DOVIZ { get; set; }
        public Nullable<double> SATIS_DOVIZ { get; set; }
        public string DOVIZ_KOD { get; set; }
        public string BOYAN_PRC { get; set; }
        public string KAPORTA_DRM { get; set; }
        public string SATICI_KOD { get; set; }
        public string ALICI_KOD { get; set; }
    }
}
