//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEMTRX
    {
        public string TIP { get; set; }
        public Nullable<short> MEK { get; set; }
        public Nullable<short> BAK { get; set; }
        public Nullable<short> KAP { get; set; }
        public Nullable<short> GAR { get; set; }
        public Nullable<short> PDI { get; set; }
        public Nullable<short> DIGER { get; set; }
    }
}
