//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEPMEK
    {
        public string ISEMRINO { get; set; }
        public string ATOLYE { get; set; }
        public int SIRANO { get; set; }
        public string YAPILACAKIS { get; set; }
        public string STOLKOD { get; set; }
        public Nullable<double> TAHSURE { get; set; }
        public string PERSON_KOD { get; set; }
        public Nullable<System.DateTime> BASTRH { get; set; }
        public Nullable<System.DateTime> BITRH { get; set; }
    }
}
