//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IKI_CEZA
    {
        public double CEZAID { get; set; }
        public string SASENO { get; set; }
        public string PLAKA { get; set; }
        public Nullable<System.DateTime> CEZATARIHI { get; set; }
        public string ACIKLAMA { get; set; }
        public string CEZAYERI { get; set; }
        public string CEZASEHIR { get; set; }
        public Nullable<double> CEZATUTAR { get; set; }
        public Nullable<byte> ODENDI { get; set; }
        public Nullable<System.DateTime> ODEME_TARIHI { get; set; }
        public Nullable<double> ARAC_ID { get; set; }
    }
}
