//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IKI_ARAC_HRK
    {
        public int HAREKET_ID { get; set; }
        public string TIPI { get; set; }
        public string BELGETIPI { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<double> ARAC_ID { get; set; }
        public string PLAKA { get; set; }
        public string BELGENO { get; set; }
        public string HAREKET_TIPI { get; set; }
        public string ISLEM_TIP { get; set; }
        public Nullable<double> REF_NO { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public string LOG_USER { get; set; }
        public string LOG_SQL_USER { get; set; }
    }
}
