//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IKI_ODEPLAN
    {
        public double ISLEMNO { get; set; }
        public string ISLEM_TIP { get; set; }
        public double SIRA { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string ODE_TIP { get; set; }
        public Nullable<double> TUTAR { get; set; }
        public Nullable<System.DateTime> VADETRH { get; set; }
        public string ACIKLAMA { get; set; }
    }
}
