//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IKI_EXDET
    {
        public double DOSYA_NO { get; set; }
        public double SNO { get; set; }
        public string KONTROL { get; set; }
        public double FIYAT_DVZ { get; set; }
        public string DVZ_TUR { get; set; }
        public Nullable<double> DVZ_KUR { get; set; }
        public double FIYAT_TL { get; set; }
    }
}
