//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IKI_DONANIM_LOG
    {
        public int LOG_ID { get; set; }
        public double DONANIM_ID { get; set; }
        public double ARAC_ID { get; set; }
        public string STATU { get; set; }
        public int AKTARILDIMI { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
    }
}
