//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IKI_ARCALISM
    {
        public double ALIS_ID { get; set; }
        public string BELGE_NO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string ALIMTIPI { get; set; }
        public Nullable<System.DateTime> VADE_TRH { get; set; }
        public string CARI_KOD { get; set; }
        public string IND_DOVIZ_KOD { get; set; }
        public Nullable<double> IND_KUR { get; set; }
        public Nullable<double> TUTAR_DOVIZ { get; set; }
        public Nullable<double> TUTAR_TL { get; set; }
        public Nullable<double> DEVIRMAS_TUT_DOVIZ { get; set; }
        public Nullable<double> DEVIR_MASTUT_TL { get; set; }
        public Nullable<double> MASRAF_TUT_DOVIZ { get; set; }
        public Nullable<double> MASRAF_TUT_TL { get; set; }
        public Nullable<double> KDVTUT_DOVIZ { get; set; }
        public Nullable<double> KDVTUT_TL { get; set; }
        public Nullable<double> NETTUT_DOVIZ { get; set; }
        public Nullable<double> NETTUT_TL { get; set; }
        public string PERSONEL_KOD { get; set; }
        public string ACIKLAMA1 { get; set; }
        public string ACIKLAMA2 { get; set; }
        public Nullable<byte> CARI_ONAY { get; set; }
        public Nullable<double> CARIFISNO { get; set; }
        public Nullable<System.DateTime> VADETRH { get; set; }
        public string STOKCARI { get; set; }
        public string DEVIR_MUSODER { get; set; }
        public string MASRAF_MUS_ODER { get; set; }
        public string MASRAF_MUS_ORDER { get; set; }
        public string SATICI_ACIKLAMA { get; set; }
        public string SATICI_ADRES { get; set; }
        public string ALIS_VEKALET { get; set; }
    }
}
