//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IKI_DUYURULAR
    {
        public int DUYURU_ID { get; set; }
        public string DUYURU { get; set; }
        public Nullable<int> AKTARILDIMI { get; set; }
        public Nullable<System.DateTime> GUNCELLEME_TARIHI { get; set; }
        public Nullable<System.DateTime> AKTARIM_TARIHI { get; set; }
    }
}
