//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IKI_EXISC
    {
        public int SNO { get; set; }
        public string ANAGRUP { get; set; }
        public string ALTGRUP { get; set; }
        public string ACIKLAMA { get; set; }
    }
}
