//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IKI_PARAMETRELER
    {
        public int PARAMETRE_ID { get; set; }
        public string WEB_MODUL_URL { get; set; }
        public byte[] EXP_RAP_BASLIK_RESMI { get; set; }
        public Nullable<int> IMAGE_QUALITY { get; set; }
        public string CARIHRK_ONAY { get; set; }
        public string CEZASATIS_ENGEL { get; set; }
    }
}
