//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IKI_NOTER
    {
        public double NOTERID { get; set; }
        public string NOTERCARIKOD { get; set; }
        public string NOTERADI { get; set; }
        public Nullable<System.DateTime> NOTERTARIHI { get; set; }
        public string YEVMIYENO { get; set; }
        public Nullable<double> SATISNO { get; set; }
        public string SASENO { get; set; }
        public string PLAKA { get; set; }
        public string ACIKLAMA { get; set; }
        public string NOTER_ADRES { get; set; }
        public string NOTER_TEL { get; set; }
    }
}
