//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IKI_ASATISM
    {
        public double SATIS_ID { get; set; }
        public string TIP { get; set; }
        public string CARIKOD { get; set; }
        public Nullable<System.DateTime> FATARIH { get; set; }
        public Nullable<System.DateTime> SAAT { get; set; }
        public Nullable<System.DateTime> VADETRH { get; set; }
        public string FAT_NO { get; set; }
        public string IRS_NO { get; set; }
        public Nullable<System.DateTime> IRS_TRH { get; set; }
        public Nullable<double> KDV { get; set; }
        public string IND_DOVIZ { get; set; }
        public Nullable<double> FIS_NO { get; set; }
        public Nullable<double> YUZDE { get; set; }
        public Nullable<double> IND_KUR { get; set; }
        public Nullable<double> USD_KUR { get; set; }
        public Nullable<double> EUR_KUR { get; set; }
        public Nullable<double> BRUTTUT_TL { get; set; }
        public Nullable<double> BRUTTUT_DVZ { get; set; }
        public Nullable<double> KDVTUT_TL { get; set; }
        public Nullable<double> KDVTUT_DVZ { get; set; }
        public Nullable<double> NETTUT_TL { get; set; }
        public Nullable<double> NET_USD { get; set; }
        public Nullable<double> NET_EUR { get; set; }
        public Nullable<double> NETTUT_DVZ { get; set; }
        public Nullable<double> INDIRIM { get; set; }
        public Nullable<double> INDIR_USD { get; set; }
        public Nullable<double> INDIR_EUR { get; set; }
        public Nullable<double> INDIRIM_DVZ { get; set; }
        public Nullable<double> KALEM_ISK { get; set; }
        public Nullable<double> KALEMISKUSD { get; set; }
        public Nullable<double> KALEMISKEUR { get; set; }
        public Nullable<double> KALEMISK_DVZ { get; set; }
        public Nullable<double> IND_YUZDE { get; set; }
        public Nullable<double> INDYUZUSD { get; set; }
        public Nullable<double> INDYUZEUR { get; set; }
        public Nullable<double> INDYUZ_DVZ { get; set; }
        public Nullable<double> MALIYET_TUT { get; set; }
        public Nullable<double> MALIYET_DVZ { get; set; }
        public Nullable<double> KARZARAR { get; set; }
        public Nullable<double> KARZARAR_DVZ { get; set; }
        public Nullable<double> CARIFISNO { get; set; }
        public Nullable<short> UNITE_KODU { get; set; }
        public Nullable<short> SAT_TIP { get; set; }
        public string ACIKLAMA { get; set; }
        public string ACIKLAMA2 { get; set; }
        public Nullable<byte> CARI_ONAY { get; set; }
        public string ALICI_ACIKLAMA { get; set; }
        public string ALICI_ADRES { get; set; }
        public string SATIS_VEKALET { get; set; }
        public Nullable<byte> CARI_HRK_PLAKA { get; set; }
    }
}
