//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IKI_ARAC
    {
        public double ARAC_ID { get; set; }
        public string PLAKA { get; set; }
        public string SASE_NO { get; set; }
        public string MOTOR_NO { get; set; }
        public string MARKA { get; set; }
        public string MODEL_KOD { get; set; }
        public Nullable<short> MODEL_YIL { get; set; }
        public string RENK_KOD { get; set; }
        public string TEYP_KODU { get; set; }
        public string ANAHTAR_KODU { get; set; }
        public string SAHIP_POTMUS { get; set; }
        public string SAHIP_KOD { get; set; }
        public Nullable<double> ALIS_NO { get; set; }
        public Nullable<System.DateTime> ALIS_TRH { get; set; }
        public string ALIS_CARI { get; set; }
        public Nullable<double> SATIS_NO { get; set; }
        public Nullable<System.DateTime> SATIS_TRH { get; set; }
        public string SATIS_CARI { get; set; }
        public string OPS { get; set; }
        public Nullable<System.DateTime> OPS_TRH { get; set; }
        public string OPS_PERKOD { get; set; }
        public string OPS_CARI { get; set; }
        public string TAKAS { get; set; }
        public string ALIS_FYT_TUR { get; set; }
        public Nullable<double> ALIS_FYT_KUR { get; set; }
        public Nullable<double> ALIS_FYT_DVZ { get; set; }
        public Nullable<double> ALIS_FYT_TL { get; set; }
        public Nullable<double> ALIS_FYT_SIFIR { get; set; }
        public Nullable<double> MASRAF { get; set; }
        public Nullable<double> MIN_SATFYT { get; set; }
        public Nullable<double> MAX_SATFYT { get; set; }
        public Nullable<double> LISTE_SATFYT { get; set; }
        public Nullable<double> KM { get; set; }
        public Nullable<System.DateTime> GRBASTRH { get; set; }
        public Nullable<System.DateTime> GRBITTRH { get; set; }
        public string SG_CARI { get; set; }
        public string SG_POLICENO { get; set; }
        public Nullable<System.DateTime> SGBASTRH { get; set; }
        public Nullable<System.DateTime> SGBITTRH { get; set; }
        public string KS_CARI { get; set; }
        public string KS_POLICENO { get; set; }
        public Nullable<System.DateTime> KSBASTRH { get; set; }
        public Nullable<System.DateTime> KSBITTRH { get; set; }
        public Nullable<System.DateTime> MYBASTRH { get; set; }
        public Nullable<System.DateTime> MYBITTRH { get; set; }
        public string ACIKLAMA1 { get; set; }
        public string ACIKLAMA2 { get; set; }
        public Nullable<double> PM_NO { get; set; }
        public Nullable<System.DateTime> TESCIL_TRH { get; set; }
        public Nullable<int> W_MARKA_ID { get; set; }
        public string W_MODEL { get; set; }
        public Nullable<int> KULLANIM { get; set; }
        public Nullable<int> KASA_TIPI { get; set; }
        public Nullable<int> MOTOR_HACIM { get; set; }
        public Nullable<int> MOTOR_GUC { get; set; }
        public Nullable<int> SANZIMAN_TIPI { get; set; }
        public Nullable<int> YAKIT { get; set; }
        public Nullable<int> W_RENK_ID { get; set; }
        public Nullable<int> KACINCI_EL { get; set; }
        public Nullable<int> HASAR_DURUMU { get; set; }
        public Nullable<int> AKTARILSINMI { get; set; }
        public Nullable<int> AKTARILDIMI { get; set; }
        public string PLAKA2 { get; set; }
        public string AT_MARKA { get; set; }
        public string AT_MODELAD { get; set; }
        public string AT_RENKAD { get; set; }
        public string AT_MOTORGUC { get; set; }
        public string ALIM_YERI { get; set; }
        public string SATIS_YERI { get; set; }
    }
}
