//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IKI_AALIS
    {
        public double ALIS_ID { get; set; }
        public double ARAC_ID { get; set; }
        public string TIP { get; set; }
        public Nullable<System.DateTime> BELGE_TRH { get; set; }
        public string BELGE_NO { get; set; }
        public string CARIKOD { get; set; }
        public string PLAKA { get; set; }
        public string SASE_NO { get; set; }
        public string MOTOR_NO { get; set; }
        public string RENK_KODU { get; set; }
        public string MODEL_KOD { get; set; }
        public Nullable<short> MODEL_YIL { get; set; }
        public string TEYP_KOD { get; set; }
        public string ANAHTAR_KOD { get; set; }
        public Nullable<double> KM { get; set; }
        public Nullable<double> MASRAF { get; set; }
        public string PERSONEL_KOD { get; set; }
        public string ILK_SAHIP { get; set; }
        public string VEKALET { get; set; }
        public string BORC { get; set; }
        public string DOSYA { get; set; }
        public string YEDEK_ANAH { get; set; }
        public string ALIS_FYT_TUR { get; set; }
        public Nullable<double> ALIS_FYT_KUR { get; set; }
        public Nullable<double> ALIS_FYT_DVZ { get; set; }
        public Nullable<double> ALIS_FYT_TL { get; set; }
        public Nullable<double> ALIS_FYT_TUT { get; set; }
        public Nullable<double> KDV { get; set; }
        public Nullable<double> KDVTUT { get; set; }
        public Nullable<double> NETTUT { get; set; }
        public Nullable<double> PM_NO { get; set; }
        public string ACIKLAMA1 { get; set; }
        public string ACIKLAMA2 { get; set; }
        public string PLAKA2 { get; set; }
        public string NOTER { get; set; }
        public Nullable<double> DEVIR_MAS { get; set; }
        public Nullable<double> KDVTUT_DVZ { get; set; }
        public Nullable<double> ALIS_TUT_DVZ { get; set; }
        public Nullable<double> MASRAF_DVZ { get; set; }
        public string ARC_ACIKLAMA { get; set; }
        public string KDV_DAHIL { get; set; }
        public Nullable<double> NETTUT_DVZ { get; set; }
        public Nullable<double> DEVIR_MAS_DVZ { get; set; }
        public Nullable<double> KDVSIZ_FYT_TL { get; set; }
        public Nullable<double> KDVSIZ_FYT_DVZ { get; set; }
        public string STOKCARI { get; set; }
        public Nullable<double> CARIFISNO { get; set; }
        public string AT_MARKA { get; set; }
        public string AT_MODELAD { get; set; }
        public string AT_RENKAD { get; set; }
        public string AT_MOTORGUC { get; set; }
        public Nullable<double> SATIS_FYT { get; set; }
        public string ALIM_YERI { get; set; }
        public string SATICI { get; set; }
    }
}
