//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IKI_SATIS
    {
        public double SATIS_ID { get; set; }
        public double ARAC_ID { get; set; }
        public string TIP { get; set; }
        public Nullable<System.DateTime> BELGE_TRH { get; set; }
        public string BELGE_NO { get; set; }
        public Nullable<System.DateTime> TESLIM_TRH { get; set; }
        public string CARIKOD { get; set; }
        public string PLAKA { get; set; }
        public string SASE_NO { get; set; }
        public string RENK_KODU { get; set; }
        public string MODEL_KOD { get; set; }
        public Nullable<double> KM { get; set; }
        public Nullable<double> KASKO_BDL { get; set; }
        public Nullable<double> DEVIR_MASRAF { get; set; }
        public string DEVIR_MUST { get; set; }
        public string NASIL_ULASTI { get; set; }
        public string TAVSIYE { get; set; }
        public string PERSONEL_KOD { get; set; }
        public string SAT_FYT_TUR { get; set; }
        public Nullable<double> SAT_FYT_KUR { get; set; }
        public Nullable<double> SAT_FYT_DVZ { get; set; }
        public Nullable<double> SAT_FYT_TL { get; set; }
        public Nullable<double> ISK_ORAN { get; set; }
        public Nullable<double> ISKONTO { get; set; }
        public Nullable<double> ARATUT { get; set; }
        public Nullable<double> KDV { get; set; }
        public Nullable<double> KDVTUT { get; set; }
        public Nullable<double> NETTUT { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<double> DIGERTUT { get; set; }
        public Nullable<System.DateTime> VADE_TRH { get; set; }
        public Nullable<short> MODELYILI { get; set; }
        public Nullable<double> NETTUT_DVZ { get; set; }
        public Nullable<double> KDVTUT_DVZ { get; set; }
        public Nullable<double> KARZARAR_DVZ { get; set; }
        public Nullable<double> ARATOP { get; set; }
        public Nullable<double> BRUTTUT_DVZ { get; set; }
        public Nullable<double> KARZARAR { get; set; }
        public string SATCARI { get; set; }
        public Nullable<double> CARIFISNO { get; set; }
        public Nullable<System.DateTime> VADETRH { get; set; }
        public Nullable<byte> CARI_ONAY { get; set; }
        public Nullable<double> ARATUT_DVZ { get; set; }
        public string NOTER_CARI { get; set; }
        public string NOTER_ADI { get; set; }
        public Nullable<System.DateTime> NOTER_TARIHI { get; set; }
        public string NOTER_YEVMNO { get; set; }
        public string KDV_DAHIL { get; set; }
        public string KASKO_KODU { get; set; }
        public Nullable<double> MALIYET { get; set; }
        public string AT_MARKA { get; set; }
        public string AT_MODELAD { get; set; }
        public string AT_RENKAD { get; set; }
        public string AT_MOTORGUC { get; set; }
        public string MOTOR_NO { get; set; }
    }
}
