//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IKI_RESIM
    {
        public double RESIM_ID { get; set; }
        public byte[] RESIM { get; set; }
        public double ARAC_ID { get; set; }
        public string PLAKA { get; set; }
        public string ISLEM_TIP { get; set; }
        public string UZANTI { get; set; }
        public Nullable<double> TARIH { get; set; }
    }
}
