//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IKIELSAT
    {
        public decimal SATIS_NO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string SASE { get; set; }
        public string ALIS_CARI { get; set; }
        public string SATIS_CARI { get; set; }
        public Nullable<double> KM { get; set; }
        public string TESLIM_ALAN { get; set; }
        public string TESLIM_EDEN { get; set; }
        public string DURUM { get; set; }
        public Nullable<double> ALIS_BEDEL { get; set; }
        public Nullable<double> SATIS_BEDEL { get; set; }
        public Nullable<System.DateTime> ODE_TARIH { get; set; }
        public string ODE_BANKA { get; set; }
        public string ODE_HESAP { get; set; }
        public string ACIKLAMA { get; set; }
    }
}
