//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IKIELARC
    {
        public string SASE_NO { get; set; }
        public string MOTOR_NO { get; set; }
        public string MARKA { get; set; }
        public string MODEL_KOD { get; set; }
        public Nullable<short> MODEL_YIL { get; set; }
        public string RENK_KOD { get; set; }
        public Nullable<double> ALIS_NO { get; set; }
        public Nullable<System.DateTime> ALIS_TRH { get; set; }
        public Nullable<double> SATIS_NO { get; set; }
        public Nullable<System.DateTime> SATIS_TRH { get; set; }
        public string SATIS_CARI { get; set; }
        public string PLAKA { get; set; }
        public Nullable<double> SIP_NO { get; set; }
        public Nullable<System.DateTime> SIP_TRH { get; set; }
        public string SIP_CARI { get; set; }
        public string NOTLAR { get; set; }
        public Nullable<double> ALIS_FYT { get; set; }
        public Nullable<double> SATIS_FYT { get; set; }
        public Nullable<double> KM { get; set; }
        public string BOYANMIS_PARCA { get; set; }
        public string KAPORTA_DURUM { get; set; }
        public Nullable<double> YAKIT_TUK1 { get; set; }
        public Nullable<double> YAKIT_TUK2 { get; set; }
        public Nullable<double> YAKIT_DEPO { get; set; }
        public Nullable<double> BAGAJ_HACIM { get; set; }
    }
}
