//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IKIEXDET
    {
        public decimal DOSYA_NO { get; set; }
        public decimal SNO { get; set; }
        public bool KONTROL { get; set; }
        public double FIYAT1 { get; set; }
        public double FIYAT2 { get; set; }
    }
}
