//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPAKET
    {
        public double IPNO { get; set; }
        public string MERBAY { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string ADI { get; set; }
        public string MODEL { get; set; }
        public Nullable<short> YILI { get; set; }
        public Nullable<int> KM { get; set; }
        public Nullable<double> PARTUT { get; set; }
        public Nullable<double> ISCTUT { get; set; }
        public Nullable<double> TUTAR { get; set; }
        public string KAMP_KOD { get; set; }
        public string CGRUP { get; set; }
        public string GAR_TIP { get; set; }
        public Nullable<double> ISK_TUT { get; set; }
        public Nullable<double> KDV_TUT { get; set; }
        public Nullable<double> GER_TUT { get; set; }
        public string MOTOR { get; set; }
    }
}
