//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISCIUSTA
    {
        public string ISCI_KOD { get; set; }
        public string ISCI_ADI { get; set; }
        public string ISCI_TIP { get; set; }
        public Nullable<double> ISCI_UCRET_NET { get; set; }
        public Nullable<double> ISCI_UCRET_BRUT { get; set; }
        public string ISCI_SSK { get; set; }
        public Nullable<System.DateTime> IS_BAS_TRH { get; set; }
        public Nullable<double> IS_TEC_YIL { get; set; }
        public Nullable<System.DateTime> AYRILIS_TRH { get; set; }
        public string REFERANSI { get; set; }
        public string CALISTIGI_YERLER { get; set; }
        public string ACIKLAMA { get; set; }
        public string MADDI_DURUM { get; set; }
        public string SERVIS_KOD { get; set; }
        public byte[] RESMI { get; set; }
        public string BOLUMU { get; set; }
        public string MEZUNIYET { get; set; }
        public string MEDENI_DURUM { get; set; }
        public string ESKI_KURSLAR { get; set; }
        public Nullable<short> COCUK { get; set; }
        public string GOREVI { get; set; }
        public string DYER { get; set; }
        public Nullable<System.DateTime> DTAR { get; set; }
        public Nullable<short> LISTE_SIRA { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string ADRES1 { get; set; }
        public string SEMT { get; set; }
        public string IL { get; set; }
        public string SSK_NO { get; set; }
        public string GRUBU { get; set; }
        public string CIHAZ_ID { get; set; }
        public string CINSIYET { get; set; }
        public string BEDEN_NO { get; set; }
        public string AYAKKABI_NO { get; set; }
        public string TCKIMLIK_NO { get; set; }
        public string VKIMLIK_NO { get; set; }
        public string KANGRUBU { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> POZ_ID { get; set; }
        public string BEDEN_UST { get; set; }
        public string BEDEN_ALT { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_USER { get; set; }
        public string DURUM { get; set; }
        public Nullable<byte> ASKERLIK { get; set; }
        public Nullable<short> ASTECYIL { get; set; }
        public string CARI_KOD { get; set; }
        public Nullable<short> SUBEKODU { get; set; }
        public string YAKIT_KART_ID { get; set; }
    }
}
