//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISCILIK
    {
        public string ISEMRI_NO { get; set; }
        public string TIP { get; set; }
        public Nullable<short> SIRANO { get; set; }
        public string ARIZA_KODU { get; set; }
        public string ARIZA_ADI { get; set; }
        public string A_T { get; set; }
        public string ARIZA_GRUP { get; set; }
        public Nullable<double> SURE { get; set; }
        public Nullable<double> ISCILIK_B_FIYATI { get; set; }
        public Nullable<double> KDV { get; set; }
        public Nullable<double> KUR { get; set; }
        public string GARANTI_TIPI { get; set; }
        public string ARIZA { get; set; }
        public string CLAIM_TURU { get; set; }
        public string BOLUM_KODU { get; set; }
        public string ONARAN_KISI { get; set; }
        public Nullable<short> QTY { get; set; }
        public Nullable<double> TOPLAM { get; set; }
        public string EXP { get; set; }
        public string S { get; set; }
        public Nullable<double> FIILISURE { get; set; }
        public string YARD_PER { get; set; }
        public Nullable<double> FATURANO { get; set; }
        public Nullable<double> CLAIMNO { get; set; }
        public Nullable<double> ISK_ORAN { get; set; }
        public Nullable<double> FYT_DOVIZ { get; set; }
        public string DOVIZ_KODU { get; set; }
        public Nullable<double> TL_KURDEGER { get; set; }
        public Nullable<short> FYILI { get; set; }
        public Nullable<double> PAKETNO { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_USER { get; set; }
        public Nullable<double> YARD_PER_SURE { get; set; }
    }
}
