//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISKGRUP
    {
        public short ROW_ID { get; set; }
        public string ISKCARIGRUP { get; set; }
        public string ISKSTOKGRUP { get; set; }
        public string ODE_KOD { get; set; }
        public Nullable<byte> FIYAT_TUR { get; set; }
        public string ISLEM { get; set; }
        public Nullable<byte> ONCELIK { get; set; }
        public Nullable<double> ORAN { get; set; }
        public Nullable<double> ORAN1 { get; set; }
        public Nullable<double> ORAN2 { get; set; }
        public Nullable<double> ORAN3 { get; set; }
    }
}
