//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISKORAN
    {
        public short ISK_NO { get; set; }
        public Nullable<short> ISK_GUN { get; set; }
        public Nullable<double> ISK_ORAN { get; set; }
        public string ACIKLAMA { get; set; }
    }
}
