//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISLEMLER
    {
        public double SIRA_NO { get; set; }
        public string CIHAZ_NO { get; set; }
        public string TIP { get; set; }
        public string BELGE_NO { get; set; }
        public string STOK_KOD { get; set; }
        public Nullable<double> MIKTAR { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string RAF_YERI { get; set; }
    }
}
