//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISMTRX
    {
        public string TUR { get; set; }
        public Nullable<short> KAPORTA { get; set; }
        public Nullable<short> KAP_SURE { get; set; }
        public Nullable<short> BOYA { get; set; }
        public Nullable<short> BOY_SURE { get; set; }
        public Nullable<short> MEKANIK { get; set; }
        public Nullable<short> MEK_SURE { get; set; }
    }
}
