//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISYERI
    {
        public double ISYERINO { get; set; }
        public string ISYERISICNO { get; set; }
        public string ISYERIAD { get; set; }
        public string ISVERENAD { get; set; }
        public string ISVERENSOYAD { get; set; }
        public string TELEFON { get; set; }
        public string ADRES { get; set; }
        public string VERGIDAIRE { get; set; }
        public string VERGINO { get; set; }
        public string ARACIAD { get; set; }
        public string MUSAVIRAD { get; set; }
        public string MUSODASIC { get; set; }
        public string YEKILI { get; set; }
        public string CAY { get; set; }
        public string TS { get; set; }
        public string TD { get; set; }
        public Nullable<double> KO { get; set; }
        public Nullable<double> GCS { get; set; }
        public Nullable<double> HCG { get; set; }
        public string M { get; set; }
        public string ISKOL { get; set; }
        public string SBKOD { get; set; }
        public string SBKODESKI { get; set; }
        public string SIRANO { get; set; }
        public string ILKOD { get; set; }
        public string ILCEKOD { get; set; }
        public string ILI { get; set; }
        public string ILCESEMT { get; set; }
        public string CD { get; set; }
        public string BCM_DOSYANO { get; set; }
        public string BCM_ISKOLU { get; set; }
        public string MUHTASAR { get; set; }
        public string KIMLIKNO { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string CUSER { get; set; }
        public string MUHGRUP1_KOD { get; set; }
        public Nullable<short> SUBEKODU { get; set; }
    }
}
