//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAMPSTKM
    {
        public int KAMP_NO { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<System.DateTime> ONTARIHBAS { get; set; }
        public Nullable<System.DateTime> ONTARIHBIT { get; set; }
        public Nullable<System.DateTime> TARIHBAS { get; set; }
        public Nullable<System.DateTime> TARIHBIT { get; set; }
        public Nullable<System.DateTime> SONTARIHBAS { get; set; }
        public Nullable<System.DateTime> SONTARIHBIT { get; set; }
        public Nullable<double> KYUZDE { get; set; }
    }
}
