//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAMPANYA
    {
        public int DOC_NO { get; set; }
        public string SASE_NO { get; set; }
        public Nullable<byte> YAPILDI { get; set; }
        public string VN { get; set; }
        public string KIMLIKNO { get; set; }
    }
}
