//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAMPEXD
    {
        public double EX_NO { get; set; }
        public int BAK_ID { get; set; }
        public string ISEMRI { get; set; }
        public Nullable<double> PAKETNO { get; set; }
        public Nullable<int> KAMPNO { get; set; }
    }
}
