//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class KASAMTRX
    {
        public string HRK_TUR { get; set; }
        public Nullable<short> NAKIT { get; set; }
        public Nullable<short> CEK { get; set; }
        public Nullable<short> SENET { get; set; }
        public Nullable<short> DEKONT { get; set; }
        public Nullable<short> POS { get; set; }
    }
}
