//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDVBEY1
    {
        public short YIL { get; set; }
        public short AY { get; set; }
        public string TIP { get; set; }
        public string VERGIDAIRE1 { get; set; }
        public string ILILCE2 { get; set; }
        public string VERGIKIMLIKNO3 { get; set; }
        public string TELALAN { get; set; }
        public string TELEFON { get; set; }
        public string SOYADI4 { get; set; }
        public string ADI5 { get; set; }
        public string BHSV66 { get; set; }
        public string BHSV66KIMNO { get; set; }
        public string BHSV66ADISOY { get; set; }
        public Nullable<System.DateTime> BHSV66TARIH { get; set; }
        public string BDSM67VERGINO { get; set; }
        public string BDSM67ADSOY { get; set; }
        public Nullable<System.DateTime> BDSM67TARIH { get; set; }
        public Nullable<double> MATRAH9 { get; set; }
        public Nullable<double> MATORAN9 { get; set; }
        public Nullable<double> MATVERGI10 { get; set; }
        public Nullable<double> MATRAH11 { get; set; }
        public Nullable<double> MATORAN11 { get; set; }
        public Nullable<double> MATVERGI12 { get; set; }
        public Nullable<double> MATRAH13 { get; set; }
        public Nullable<double> MATORAN13 { get; set; }
        public Nullable<double> MATVERGI14 { get; set; }
        public Nullable<double> MATRAH15 { get; set; }
        public Nullable<double> MATORAN15 { get; set; }
        public Nullable<double> MATVERGI16 { get; set; }
        public Nullable<double> MATRAH17 { get; set; }
        public Nullable<double> MATORAN17 { get; set; }
        public Nullable<double> MATVERGI18 { get; set; }
        public Nullable<double> KDVTUT20 { get; set; }
        public Nullable<double> KDVTUT22 { get; set; }
        public Nullable<double> KDVTUT23 { get; set; }
        public Nullable<double> KDVTUT24 { get; set; }
        public Nullable<double> KDVTUT25 { get; set; }
        public Nullable<double> KDVTUT31 { get; set; }
        public Nullable<double> KDVTUT32 { get; set; }
        public Nullable<double> KDVTUT65 { get; set; }
        public Nullable<double> TUTAR33 { get; set; }
        public Nullable<double> YUKDV34 { get; set; }
        public Nullable<double> TUTAR35 { get; set; }
        public Nullable<double> YUKDV36 { get; set; }
        public Nullable<double> TUTAR37 { get; set; }
        public Nullable<double> YUKDV38 { get; set; }
        public Nullable<double> TUTAR39 { get; set; }
        public Nullable<double> YUKDV40 { get; set; }
        public Nullable<double> TUTAR41 { get; set; }
        public Nullable<double> YUKDV42 { get; set; }
        public Nullable<double> TUTAR43 { get; set; }
        public Nullable<double> YUKDV44 { get; set; }
        public Nullable<double> TUTAR45 { get; set; }
        public Nullable<double> YUKDV46 { get; set; }
        public Nullable<double> TUTAR47 { get; set; }
        public Nullable<double> YUKDV48 { get; set; }
        public Nullable<double> TUTAR49 { get; set; }
        public Nullable<double> YUKDV50 { get; set; }
        public Nullable<double> IH_BEDEL54 { get; set; }
        public Nullable<double> IH_ORAN54 { get; set; }
        public Nullable<double> IH_VERGI55 { get; set; }
        public Nullable<double> IH_BEDEL56 { get; set; }
        public Nullable<double> IH_ORAN56 { get; set; }
        public Nullable<double> IH_VERGI57 { get; set; }
        public Nullable<double> IH_BEDEL58 { get; set; }
        public Nullable<double> IH_ORAN58 { get; set; }
        public Nullable<double> IH_VERGI59 { get; set; }
        public Nullable<double> IH_BEDEL60 { get; set; }
        public Nullable<double> IH_ORAN60 { get; set; }
        public Nullable<double> IH_VERGI61 { get; set; }
        public Nullable<short> EKLEBA201 { get; set; }
        public Nullable<short> EKLEBA202 { get; set; }
        public Nullable<short> EKLEBA203 { get; set; }
        public Nullable<short> EKLEBA204 { get; set; }
        public Nullable<short> EKLEBA205 { get; set; }
        public Nullable<short> EKLEBA206 { get; set; }
        public Nullable<short> EKLEBA207 { get; set; }
        public Nullable<short> EKLEBA208 { get; set; }
        public Nullable<double> H6 { get; set; }
        public Nullable<double> H7 { get; set; }
        public Nullable<double> H8 { get; set; }
        public Nullable<double> H19 { get; set; }
        public Nullable<double> H21 { get; set; }
        public Nullable<double> H26 { get; set; }
        public Nullable<double> H27 { get; set; }
        public Nullable<double> H28 { get; set; }
        public Nullable<double> H29 { get; set; }
        public Nullable<double> H30 { get; set; }
        public Nullable<double> H51 { get; set; }
        public Nullable<double> H52 { get; set; }
        public Nullable<double> H53 { get; set; }
        public Nullable<double> H62 { get; set; }
        public Nullable<double> H63 { get; set; }
        public Nullable<double> H64 { get; set; }
        public string YAZALAN { get; set; }
        public Nullable<double> MATRAH231 { get; set; }
        public Nullable<double> MATORAN231 { get; set; }
        public Nullable<double> MATVERGI231 { get; set; }
        public Nullable<double> MATRAH232 { get; set; }
        public Nullable<double> MATORAN232 { get; set; }
        public Nullable<double> MATVERGI232 { get; set; }
        public Nullable<double> MATRAH233 { get; set; }
        public Nullable<double> MATORAN233 { get; set; }
        public Nullable<double> MATVERGI233 { get; set; }
        public Nullable<double> MATRAH234 { get; set; }
        public Nullable<double> MATORAN234 { get; set; }
        public Nullable<double> MATVERGI234 { get; set; }
        public Nullable<double> MATRAH235 { get; set; }
        public Nullable<double> MATORAN235 { get; set; }
        public Nullable<double> MATVERGI235 { get; set; }
    }
}
