//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOORFAT
    {
        public int ID { get; set; }
        public string FONTADI { get; set; }
        public string FONTSTYLE { get; set; }
        public Nullable<short> FONTSIZE { get; set; }
        public string FONTRENK { get; set; }
        public Nullable<short> SAYFAGEN { get; set; }
        public Nullable<short> SAYFAYUK { get; set; }
        public string SAYFAISIM { get; set; }
        public string PRBICIMI { get; set; }
        public Nullable<short> SAYFA_S { get; set; }
        public Nullable<short> SAYFA_U { get; set; }
        public Nullable<short> KR_S { get; set; }
        public Nullable<short> KR_U { get; set; }
        public Nullable<short> ADR1_S { get; set; }
        public Nullable<short> ADR1_U { get; set; }
        public Nullable<short> ADR2_S { get; set; }
        public Nullable<short> ADR2_U { get; set; }
        public Nullable<short> ADR3_S { get; set; }
        public Nullable<short> ADR3_U { get; set; }
        public Nullable<short> PK_S { get; set; }
        public Nullable<short> PK_U { get; set; }
        public Nullable<short> SEMT_S { get; set; }
        public Nullable<short> SEMT_U { get; set; }
        public Nullable<short> IL_S { get; set; }
        public Nullable<short> IL_U { get; set; }
        public Nullable<short> VERD_S { get; set; }
        public Nullable<short> VERD_U { get; set; }
        public Nullable<short> VERNO_S { get; set; }
        public Nullable<short> VERNO_U { get; set; }
        public Nullable<short> CARIKOD_S { get; set; }
        public Nullable<short> CARIKOD_U { get; set; }
        public Nullable<short> OZEL1_S { get; set; }
        public Nullable<short> OZEL1_U { get; set; }
        public Nullable<short> OZEL2_S { get; set; }
        public Nullable<short> OZEL2_U { get; set; }
        public Nullable<short> TRH_S { get; set; }
        public Nullable<short> TRH_U { get; set; }
        public Nullable<short> SAAT_S { get; set; }
        public Nullable<short> SAAT_U { get; set; }
        public Nullable<short> FATNO_S { get; set; }
        public Nullable<short> FATNO_U { get; set; }
        public Nullable<short> IRSNO_S { get; set; }
        public Nullable<short> IRSNO_U { get; set; }
        public Nullable<short> FSEVK_S { get; set; }
        public Nullable<short> FSEVK_U { get; set; }
        public Nullable<short> SUTB_S { get; set; }
        public Nullable<short> SUTB_U { get; set; }
        public Nullable<short> SIRA_U { get; set; }
        public Nullable<short> URUNAD_U { get; set; }
        public Nullable<short> BIRIMF_U { get; set; }
        public Nullable<short> MIK_U { get; set; }
        public Nullable<short> TUTAR_U { get; set; }
        public Nullable<short> DOVIZ_S { get; set; }
        public Nullable<short> DOVIZ_U { get; set; }
        public Nullable<short> ACIKLA_S { get; set; }
        public Nullable<short> ACIKLA_U { get; set; }
        public Nullable<short> BRUT_S { get; set; }
        public Nullable<short> BRUT_U { get; set; }
        public Nullable<short> ISK_S { get; set; }
        public Nullable<short> ISK_U { get; set; }
        public Nullable<short> ARA_S { get; set; }
        public Nullable<short> ARA_U { get; set; }
        public Nullable<short> KDV_S { get; set; }
        public Nullable<short> KDV_U { get; set; }
        public Nullable<short> TOP_S { get; set; }
        public Nullable<short> TOP_U { get; set; }
        public Nullable<short> KDVMAT_S { get; set; }
        public Nullable<short> KDVMAT_U { get; set; }
        public Nullable<short> YAZI_S { get; set; }
        public Nullable<short> YAZI_U { get; set; }
        public Nullable<short> SABIT1_S { get; set; }
        public Nullable<short> SABIT1_U { get; set; }
        public Nullable<short> SABIT2_S { get; set; }
        public Nullable<short> SABIT2_U { get; set; }
        public Nullable<short> SABIT3_S { get; set; }
        public Nullable<short> SABIT3_U { get; set; }
        public Nullable<short> SIRA_S { get; set; }
        public Nullable<short> URUNAD_S { get; set; }
        public Nullable<short> BIRIMF_S { get; set; }
        public Nullable<short> MIK_S { get; set; }
        public Nullable<short> TUTAR_S { get; set; }
        public Nullable<short> SKDV_S { get; set; }
        public Nullable<short> SKDV_U { get; set; }
        public Nullable<short> SISK_S { get; set; }
        public Nullable<short> SISK_U { get; set; }
        public Nullable<short> ALAN1_S { get; set; }
        public Nullable<short> ALAN1_U { get; set; }
        public Nullable<short> ALAN2_S { get; set; }
        public Nullable<short> ALAN2_U { get; set; }
        public Nullable<short> ALAN3_S { get; set; }
        public Nullable<short> ALAN3_U { get; set; }
        public Nullable<short> ALAN4_S { get; set; }
        public Nullable<short> ALAN4_U { get; set; }
        public Nullable<short> ALAN5_S { get; set; }
        public Nullable<short> ALAN5_U { get; set; }
        public string SABIT1 { get; set; }
        public string SABIT2 { get; set; }
        public string SABIT3 { get; set; }
        public Nullable<short> VADETRH_S { get; set; }
        public Nullable<short> VADETRH_U { get; set; }
        public Nullable<short> SISKORN_S { get; set; }
        public Nullable<short> SISKORN_U { get; set; }
        public Nullable<short> SNETTUT_S { get; set; }
        public Nullable<short> SNETTUT_U { get; set; }
        public Nullable<byte> TOPLAM_VSB { get; set; }
        public Nullable<short> ISKS_U { get; set; }
        public Nullable<short> ISKS_S { get; set; }
        public Nullable<short> KISK_U { get; set; }
        public Nullable<short> KISK_S { get; set; }
        public Nullable<short> NOT_S { get; set; }
        public Nullable<short> NOT_U { get; set; }
        public string FATFORM_ADI { get; set; }
        public Nullable<short> KDV_GEN { get; set; }
        public Nullable<short> ISK_GEN { get; set; }
        public Nullable<short> OLCU_S { get; set; }
        public Nullable<short> OLCU_U { get; set; }
        public Nullable<short> KDVO_S { get; set; }
        public Nullable<short> KDVO_U { get; set; }
        public Nullable<short> SNO_S { get; set; }
        public Nullable<short> SNO_U { get; set; }
        public Nullable<short> TEL1_S { get; set; }
        public Nullable<short> TEL1_U { get; set; }
        public Nullable<short> GSM_S { get; set; }
        public Nullable<short> GSM_U { get; set; }
        public Nullable<short> ODETIP_S { get; set; }
        public Nullable<short> ODETIP_U { get; set; }
        public Nullable<short> SEVKYER_S { get; set; }
        public Nullable<short> SEVKYER_U { get; set; }
        public Nullable<short> SEVKADRES_S { get; set; }
        public Nullable<short> SEVKADRES_U { get; set; }
        public Nullable<short> SEVKTRH_S { get; set; }
        public Nullable<short> SEVKTRH_U { get; set; }
        public Nullable<short> BASLIK_VSB { get; set; }
        public Nullable<short> GERTUT_VSB { get; set; }
    }
}
