//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOORIE
    {
        public int ID { get; set; }
        public string FONTADI { get; set; }
        public string FONTSTYLE { get; set; }
        public Nullable<short> FONTSIZE { get; set; }
        public string FONTRENK { get; set; }
        public Nullable<short> SAYFAGEN { get; set; }
        public Nullable<short> SAYFAYUK { get; set; }
        public string SAYFAISIM { get; set; }
        public string PRBICIMI { get; set; }
        public Nullable<short> SAYFA_S { get; set; }
        public Nullable<short> SAYFA_U { get; set; }
        public Nullable<short> IENO_S { get; set; }
        public Nullable<short> IENO_U { get; set; }
        public Nullable<short> IETIP_S { get; set; }
        public Nullable<short> IETIP_U { get; set; }
        public Nullable<short> KR_S { get; set; }
        public Nullable<short> KR_U { get; set; }
        public Nullable<short> ADR1_S { get; set; }
        public Nullable<short> ADR1_U { get; set; }
        public Nullable<short> ADR2_S { get; set; }
        public Nullable<short> ADR2_U { get; set; }
        public Nullable<short> ADR3_S { get; set; }
        public Nullable<short> ADR3_U { get; set; }
        public Nullable<short> PK_S { get; set; }
        public Nullable<short> PK_U { get; set; }
        public Nullable<short> SEMT_S { get; set; }
        public Nullable<short> SEMT_U { get; set; }
        public Nullable<short> IL_S { get; set; }
        public Nullable<short> IL_U { get; set; }
        public Nullable<short> VERD_S { get; set; }
        public Nullable<short> VERD_U { get; set; }
        public Nullable<short> VERNO_S { get; set; }
        public Nullable<short> VERNO_U { get; set; }
        public Nullable<short> CARIKOD_S { get; set; }
        public Nullable<short> CARIKOD_U { get; set; }
        public Nullable<short> ACTRH_S { get; set; }
        public Nullable<short> ACTRH_U { get; set; }
        public Nullable<short> KAPTRH_S { get; set; }
        public Nullable<short> KAPTRH_U { get; set; }
        public Nullable<short> PLAKA_S { get; set; }
        public Nullable<short> PLAKA_U { get; set; }
        public Nullable<short> RENK_S { get; set; }
        public Nullable<short> RENK_U { get; set; }
        public Nullable<short> SASE_S { get; set; }
        public Nullable<short> SASE_U { get; set; }
        public Nullable<short> MOTOR_S { get; set; }
        public Nullable<short> MOTOR_U { get; set; }
        public Nullable<short> MODEL_S { get; set; }
        public Nullable<short> MODEL_U { get; set; }
        public Nullable<short> MODYIL_S { get; set; }
        public Nullable<short> MODYIL_U { get; set; }
        public Nullable<short> RUHTRH_S { get; set; }
        public Nullable<short> RUHTRH_U { get; set; }
        public Nullable<short> KM_S { get; set; }
        public Nullable<short> KM_U { get; set; }
        public Nullable<short> OZEL1_S { get; set; }
        public Nullable<short> OZEL1_U { get; set; }
        public Nullable<short> OZEL2_S { get; set; }
        public Nullable<short> OZEL2_U { get; set; }
        public Nullable<short> OZEL3_S { get; set; }
        public Nullable<short> OZEL3_U { get; set; }
        public Nullable<short> TAHTRH_S { get; set; }
        public Nullable<short> TAHTRH_U { get; set; }
        public Nullable<short> TAHSAAT_S { get; set; }
        public Nullable<short> TAHSAAT_U { get; set; }
        public Nullable<short> TAHTUTAR_S { get; set; }
        public Nullable<short> TAHTUTAR_U { get; set; }
        public Nullable<short> IMZA_S { get; set; }
        public Nullable<short> IMZA_U { get; set; }
        public Nullable<short> SUTB_S { get; set; }
        public Nullable<short> SUTB_U { get; set; }
        public Nullable<short> SIRA_U { get; set; }
        public Nullable<short> URUNAD_U { get; set; }
        public Nullable<short> BIRIMF_U { get; set; }
        public Nullable<short> MIK_U { get; set; }
        public Nullable<short> TUTAR_U { get; set; }
        public Nullable<short> DOVIZ_S { get; set; }
        public Nullable<short> DOVIZ_U { get; set; }
        public Nullable<short> ACIKLA_S { get; set; }
        public Nullable<short> ACIKLA_U { get; set; }
        public Nullable<short> EMANET_S { get; set; }
        public Nullable<short> EMANET_U { get; set; }
        public Nullable<short> YAKIT_S { get; set; }
        public Nullable<short> YAKIT_U { get; set; }
        public Nullable<short> TALEP1_S { get; set; }
        public Nullable<short> TALEP1_U { get; set; }
        public Nullable<short> TALEP2_S { get; set; }
        public Nullable<short> TALEP2_U { get; set; }
        public Nullable<short> ONAYTUT_S { get; set; }
        public Nullable<short> ONAYTUT_U { get; set; }
        public Nullable<short> PERS_S { get; set; }
        public Nullable<short> PERS_U { get; set; }
        public Nullable<short> SABIT1_S { get; set; }
        public Nullable<short> SABIT1_U { get; set; }
        public string SABIT1 { get; set; }
        public Nullable<short> SABIT2_S { get; set; }
        public Nullable<short> SABIT2_U { get; set; }
        public string SABIT2 { get; set; }
        public Nullable<short> SABIT3_S { get; set; }
        public Nullable<short> SABIT3_U { get; set; }
        public string SABIT3 { get; set; }
        public Nullable<short> ALAN1_S { get; set; }
        public Nullable<short> ALAN1_U { get; set; }
        public Nullable<short> ALAN2_S { get; set; }
        public Nullable<short> ALAN2_U { get; set; }
        public Nullable<short> ALAN3_S { get; set; }
        public Nullable<short> ALAN3_U { get; set; }
        public Nullable<short> ALAN4_S { get; set; }
        public Nullable<short> ALAN4_U { get; set; }
        public Nullable<short> ALAN5_S { get; set; }
        public Nullable<short> ALAN5_U { get; set; }
        public Nullable<short> ALAN6_S { get; set; }
        public Nullable<short> ALAN6_U { get; set; }
        public Nullable<short> ALAN7_S { get; set; }
        public Nullable<short> ALAN7_U { get; set; }
        public Nullable<short> ALAN8_S { get; set; }
        public Nullable<short> ALAN8_U { get; set; }
        public Nullable<short> ALAN9_S { get; set; }
        public Nullable<short> ALAN9_U { get; set; }
        public string IEFORM_ADI { get; set; }
        public Nullable<short> IEBARKOD_S { get; set; }
        public Nullable<short> IEBARKOD_U { get; set; }
    }
}
