//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOORBYN2
    {
        public int ID { get; set; }
        public Nullable<short> SB_SX { get; set; }
        public Nullable<short> SB_UX { get; set; }
        public Nullable<short> SAAD_S { get; set; }
        public Nullable<short> SABB_S { get; set; }
        public Nullable<short> SADY_S { get; set; }
        public Nullable<short> SADT_S { get; set; }
        public Nullable<short> SAISAD_S { get; set; }
        public Nullable<short> SAADR_S { get; set; }
        public Nullable<short> SSTA_S { get; set; }
        public Nullable<short> SSTVD_S { get; set; }
        public Nullable<short> SAAD_U { get; set; }
        public Nullable<short> SABB_U { get; set; }
        public Nullable<short> SADY_U { get; set; }
        public Nullable<short> SADT_U { get; set; }
        public Nullable<short> SAISAD_U { get; set; }
        public Nullable<short> SAADR_U { get; set; }
        public Nullable<short> SSTA_U { get; set; }
        public Nullable<short> SSTVD_U { get; set; }
        public Nullable<short> SSTVN_S { get; set; }
        public Nullable<short> SSTVN_U { get; set; }
        public Nullable<short> SAVD_S { get; set; }
        public Nullable<short> SAVD_U { get; set; }
        public Nullable<short> SAVN_S { get; set; }
        public Nullable<short> SAVN_U { get; set; }
        public Nullable<short> SAGV_S { get; set; }
        public Nullable<short> SAGV_U { get; set; }
        public Nullable<short> SATV_S { get; set; }
        public Nullable<short> SATV_U { get; set; }
        public Nullable<short> SSTADR_S { get; set; }
        public Nullable<short> SSTADR_U { get; set; }
        public Nullable<short> SMD_S { get; set; }
        public Nullable<short> SSA_S { get; set; }
        public Nullable<short> SSH_S { get; set; }
        public Nullable<short> SMG_S { get; set; }
        public Nullable<short> SAG_S { get; set; }
        public Nullable<short> SMD_U { get; set; }
        public Nullable<short> SSA_U { get; set; }
        public Nullable<short> SSH_U { get; set; }
        public Nullable<short> SMG_U { get; set; }
        public Nullable<short> SAG_U { get; set; }
        public Nullable<short> SOY_S { get; set; }
        public Nullable<short> SOY_U { get; set; }
        public Nullable<short> SKS_S { get; set; }
        public Nullable<short> SKS_U { get; set; }
        public Nullable<short> SBLG_S { get; set; }
        public Nullable<short> SBLG_U { get; set; }
        public Nullable<short> SBY_S { get; set; }
        public Nullable<short> SVD_S { get; set; }
        public Nullable<short> SVN_S { get; set; }
        public Nullable<short> SBY_U { get; set; }
        public Nullable<short> SVD_U { get; set; }
        public Nullable<short> SVN_U { get; set; }
        public Nullable<short> SM_S { get; set; }
        public Nullable<short> SM_U { get; set; }
        public Nullable<short> SS_S { get; set; }
        public Nullable<short> SS_U { get; set; }
        public Nullable<short> SC_S { get; set; }
        public Nullable<short> SC_U { get; set; }
        public Nullable<short> SP_S { get; set; }
        public Nullable<short> SP_U { get; set; }
        public Nullable<short> SMRK_S { get; set; }
        public Nullable<short> SMRK_U { get; set; }
        public Nullable<short> STIP_S { get; set; }
        public Nullable<short> STIP_U { get; set; }
        public Nullable<short> SIH_S { get; set; }
        public Nullable<short> SIH_U { get; set; }
        public Nullable<short> SSL_S { get; set; }
        public Nullable<short> SSL_U { get; set; }
        public Nullable<short> SIS2_S { get; set; }
        public Nullable<short> SIS2_U { get; set; }
        public Nullable<short> SBVN1_S { get; set; }
        public Nullable<short> SBVN1_U { get; set; }
        public Nullable<short> SBVN2_S { get; set; }
        public Nullable<short> SBVN2_U { get; set; }
        public Nullable<short> SIS1_S { get; set; }
        public Nullable<short> SIS1_U { get; set; }
        public Nullable<short> SIS3_S { get; set; }
        public Nullable<short> SIS3_U { get; set; }
        public Nullable<short> SR_S { get; set; }
        public Nullable<short> SR_U { get; set; }
        public Nullable<short> SAB_S { get; set; }
        public Nullable<short> SAB_U { get; set; }
    }
}
