//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOORAFAT
    {
        public int ID { get; set; }
        public string FONTADI { get; set; }
        public string FONTSTYLE { get; set; }
        public Nullable<short> FONTSIZE { get; set; }
        public string FONTRENK { get; set; }
        public Nullable<short> SAYFAGEN { get; set; }
        public Nullable<short> SAYFAYUK { get; set; }
        public string SAYFAISIM { get; set; }
        public string PRBICIMI { get; set; }
        public Nullable<short> SAYFA_S { get; set; }
        public Nullable<short> SAYFA_U { get; set; }
        public Nullable<short> KR_S { get; set; }
        public Nullable<short> KR_U { get; set; }
        public Nullable<short> ADR1_S { get; set; }
        public Nullable<short> ADR1_U { get; set; }
        public Nullable<short> ADR2_S { get; set; }
        public Nullable<short> ADR2_U { get; set; }
        public Nullable<short> ADR3_S { get; set; }
        public Nullable<short> ADR3_U { get; set; }
        public Nullable<short> PK_S { get; set; }
        public Nullable<short> PK_U { get; set; }
        public Nullable<short> SEMT_S { get; set; }
        public Nullable<short> SEMT_U { get; set; }
        public Nullable<short> IL_S { get; set; }
        public Nullable<short> IL_U { get; set; }
        public Nullable<short> VERD_S { get; set; }
        public Nullable<short> VERD_U { get; set; }
        public Nullable<short> VERNO_S { get; set; }
        public Nullable<short> VERNO_U { get; set; }
        public Nullable<short> CARIKOD_S { get; set; }
        public Nullable<short> CARIKOD_U { get; set; }
        public Nullable<short> OZEL1_S { get; set; }
        public Nullable<short> OZEL1_U { get; set; }
        public Nullable<short> OZEL2_S { get; set; }
        public Nullable<short> OZEL2_U { get; set; }
        public Nullable<short> TRH_S { get; set; }
        public Nullable<short> TRH_U { get; set; }
        public Nullable<short> SAAT_S { get; set; }
        public Nullable<short> SAAT_U { get; set; }
        public Nullable<short> FATNO_S { get; set; }
        public Nullable<short> FATNO_U { get; set; }
        public Nullable<short> IRSNO_S { get; set; }
        public Nullable<short> IRSNO_U { get; set; }
        public Nullable<short> FSEVK_S { get; set; }
        public Nullable<short> FSEVK_U { get; set; }
        public Nullable<short> MOTOR_S { get; set; }
        public Nullable<short> MOTOR_U { get; set; }
        public Nullable<short> SASE_S { get; set; }
        public Nullable<short> SASE_U { get; set; }
        public Nullable<short> MODEL_S { get; set; }
        public Nullable<short> MODEL_U { get; set; }
        public Nullable<short> SLNDR_S { get; set; }
        public Nullable<short> SLNDR_U { get; set; }
        public Nullable<short> SLNHAC_S { get; set; }
        public Nullable<short> SLNHAC_U { get; set; }
        public Nullable<short> MOTGUC_S { get; set; }
        public Nullable<short> MOTGUC_U { get; set; }
        public Nullable<short> AGRLK_S { get; set; }
        public Nullable<short> AGRLK_U { get; set; }
        public Nullable<short> OTRYER_S { get; set; }
        public Nullable<short> OTRYER_U { get; set; }
        public Nullable<short> BNDRL_S { get; set; }
        public Nullable<short> BNDRL_U { get; set; }
        public Nullable<short> ITHMUS_S { get; set; }
        public Nullable<short> ITHMUS_U { get; set; }
        public Nullable<short> BELGE_S { get; set; }
        public Nullable<short> BELGE_U { get; set; }
        public Nullable<short> SUTB_S { get; set; }
        public Nullable<short> SUTB_U { get; set; }
        public Nullable<short> SIRA_U { get; set; }
        public Nullable<short> URUNAD_U { get; set; }
        public Nullable<short> BIRIMF_U { get; set; }
        public Nullable<short> MIK_U { get; set; }
        public Nullable<short> TUTAR_U { get; set; }
        public Nullable<short> DOVIZ_S { get; set; }
        public Nullable<short> DOVIZ_U { get; set; }
        public Nullable<short> ACIKLA_S { get; set; }
        public Nullable<short> ACIKLA_U { get; set; }
        public Nullable<short> BRUT_S { get; set; }
        public Nullable<short> BRUT_U { get; set; }
        public Nullable<short> ISK_S { get; set; }
        public Nullable<short> ISK_U { get; set; }
        public Nullable<short> ARA_S { get; set; }
        public Nullable<short> ARA_U { get; set; }
        public Nullable<short> KDV_S { get; set; }
        public Nullable<short> KDV_U { get; set; }
        public Nullable<short> TOP_S { get; set; }
        public Nullable<short> TOP_U { get; set; }
        public Nullable<short> KDVMAT_S { get; set; }
        public Nullable<short> KDVMAT_U { get; set; }
        public Nullable<short> YAZI_S { get; set; }
        public Nullable<short> YAZI_U { get; set; }
        public string SABIT1 { get; set; }
        public Nullable<short> SABIT1_S { get; set; }
        public Nullable<short> SABIT1_U { get; set; }
        public string SABIT2 { get; set; }
        public Nullable<short> SABIT2_S { get; set; }
        public Nullable<short> SABIT2_U { get; set; }
        public string SABIT3 { get; set; }
        public Nullable<short> SABIT3_S { get; set; }
        public Nullable<short> SABIT3_U { get; set; }
    }
}
