//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOORBYN
    {
        public int ID { get; set; }
        public string FONTADI { get; set; }
        public string FONTSTYLE { get; set; }
        public Nullable<short> FONTSIZE { get; set; }
        public string FONTRENK { get; set; }
        public Nullable<short> SAYFAGEN { get; set; }
        public Nullable<short> SAYFAYUK { get; set; }
        public string SAYFAISIM { get; set; }
        public string PRBICIMI { get; set; }
        public Nullable<short> SAYFA_S { get; set; }
        public Nullable<short> SAYFA_U { get; set; }
        public Nullable<short> YIL_S { get; set; }
        public Nullable<short> YIL_U { get; set; }
        public Nullable<short> VD_S { get; set; }
        public Nullable<short> VD_U { get; set; }
        public Nullable<short> VN_S { get; set; }
        public Nullable<short> VN_U { get; set; }
        public string VD_AD { get; set; }
        public Nullable<short> ALAD_S { get; set; }
        public Nullable<short> ALAD_U { get; set; }
        public Nullable<short> ALBB_S { get; set; }
        public Nullable<short> ALBB_U { get; set; }
        public Nullable<short> ALDY_S { get; set; }
        public Nullable<short> ALDY_U { get; set; }
        public Nullable<short> ALDT_S { get; set; }
        public Nullable<short> ALDT_U { get; set; }
        public Nullable<short> ALISAD_S { get; set; }
        public Nullable<short> ALISAD_U { get; set; }
        public Nullable<short> ALADR_S { get; set; }
        public Nullable<short> ALADR_U { get; set; }
        public Nullable<short> ALVD_S { get; set; }
        public Nullable<short> ALVD_U { get; set; }
        public Nullable<short> ALVN_S { get; set; }
        public Nullable<short> ALVN_U { get; set; }
        public Nullable<short> GLRVER_S { get; set; }
        public Nullable<short> GLRVER_U { get; set; }
        public Nullable<short> TSTVER_S { get; set; }
        public Nullable<short> TSTVER_U { get; set; }
        public Nullable<short> SATAD_S { get; set; }
        public Nullable<short> SATAD_U { get; set; }
        public Nullable<short> SATBB_S { get; set; }
        public Nullable<short> SATBB_U { get; set; }
        public Nullable<short> SATDY_S { get; set; }
        public Nullable<short> SATDY_U { get; set; }
        public Nullable<short> SATDT_S { get; set; }
        public Nullable<short> SATDT_U { get; set; }
        public Nullable<short> SATISAD_S { get; set; }
        public Nullable<short> SATISAD_U { get; set; }
        public Nullable<short> SATADR_S { get; set; }
        public Nullable<short> SATADR_U { get; set; }
        public Nullable<short> SATVD_S { get; set; }
        public Nullable<short> SATVD_U { get; set; }
        public Nullable<short> SATVN_S { get; set; }
        public Nullable<short> SATVN_U { get; set; }
        public Nullable<short> PLAKA_S { get; set; }
        public Nullable<short> PLAKA_U { get; set; }
        public Nullable<short> CINS_S { get; set; }
        public Nullable<short> CINS_U { get; set; }
        public Nullable<short> MARKA_S { get; set; }
        public Nullable<short> MARKA_U { get; set; }
        public Nullable<short> SASE_S { get; set; }
        public Nullable<short> SASE_U { get; set; }
        public Nullable<short> MOTOR_S { get; set; }
        public Nullable<short> MOTOR_U { get; set; }
        public Nullable<short> MODEL_S { get; set; }
        public Nullable<short> MODEL_U { get; set; }
        public Nullable<short> MODYIL_S { get; set; }
        public Nullable<short> MODYIL_U { get; set; }
        public Nullable<short> TIP_S { get; set; }
        public Nullable<short> TIP_U { get; set; }
        public Nullable<short> SLNDR_S { get; set; }
        public Nullable<short> SLNDR_U { get; set; }
        public Nullable<short> SLNHAC_S { get; set; }
        public Nullable<short> SLNHAC_U { get; set; }
        public Nullable<short> BYGR_S { get; set; }
        public Nullable<short> BYGR_U { get; set; }
        public Nullable<short> AGRLK_S { get; set; }
        public Nullable<short> AGRLK_U { get; set; }
        public Nullable<short> ISTIAB_S { get; set; }
        public Nullable<short> ISTIAB_U { get; set; }
        public Nullable<short> OTRYER_S { get; set; }
        public Nullable<short> OTRYER_U { get; set; }
        public Nullable<short> SPOR_S { get; set; }
        public Nullable<short> SPOR_U { get; set; }
        public Nullable<short> KULLN_S { get; set; }
        public Nullable<short> KULLN_U { get; set; }
        public Nullable<short> TARIFE_S { get; set; }
        public Nullable<short> TARIFE_U { get; set; }
        public Nullable<short> ALISS1_S { get; set; }
        public Nullable<short> ALISS1_U { get; set; }
        public Nullable<short> ALISS2_S { get; set; }
        public Nullable<short> ALISS2_U { get; set; }
        public Nullable<short> ALISS3_S { get; set; }
        public Nullable<short> ALISS3_U { get; set; }
        public Nullable<short> ALISS4_S { get; set; }
        public Nullable<short> ALISS4_U { get; set; }
        public Nullable<short> ALISS5_S { get; set; }
        public Nullable<short> ALISS5_U { get; set; }
        public Nullable<short> VRLNDN1_S { get; set; }
        public Nullable<short> VRLNDN1_U { get; set; }
        public Nullable<short> VRLNDN2_S { get; set; }
        public Nullable<short> VRLNDN2_U { get; set; }
        public Nullable<short> VRLNDN3_S { get; set; }
        public Nullable<short> VRLNDN3_U { get; set; }
        public Nullable<short> VRLNDN4_S { get; set; }
        public Nullable<short> VRLNDN4_U { get; set; }
        public Nullable<short> VRLNDN5_S { get; set; }
        public Nullable<short> VRLNDN5_U { get; set; }
    }
}
