//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class KORPARF
    {
        public int ID { get; set; }
        public Nullable<short> SAYFA_S { get; set; }
        public Nullable<short> SAYFA_U { get; set; }
        public Nullable<short> KR_S { get; set; }
        public Nullable<short> KR_U { get; set; }
        public Nullable<short> ADR1_S { get; set; }
        public Nullable<short> ADR1_U { get; set; }
        public Nullable<short> ADR2_S { get; set; }
        public Nullable<short> ADR2_U { get; set; }
        public Nullable<short> ADR3_S { get; set; }
        public Nullable<short> ADR3_U { get; set; }
        public Nullable<short> VERD_S { get; set; }
        public Nullable<short> VERD_U { get; set; }
        public Nullable<short> VERNO_S { get; set; }
        public Nullable<short> VERNO_U { get; set; }
        public Nullable<short> TRH_S { get; set; }
        public Nullable<short> TRH_U { get; set; }
        public Nullable<short> SUTB_S { get; set; }
        public Nullable<short> SUTB_U { get; set; }
        public Nullable<short> TOP_S { get; set; }
        public Nullable<short> TOP_U { get; set; }
        public Nullable<short> YAZI_S { get; set; }
        public Nullable<short> YAZI_U { get; set; }
        public Nullable<short> SIRA_U { get; set; }
        public Nullable<short> URUNAD_U { get; set; }
        public Nullable<short> BIRIMF_U { get; set; }
        public Nullable<short> MIK_U { get; set; }
        public Nullable<short> TUTAR_U { get; set; }
    }
}
