//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class KURDEGER
    {
        public string DOVIZ_KODU { get; set; }
        public System.DateTime TARIH { get; set; }
        public Nullable<double> TLDEGERI_ALIS { get; set; }
        public Nullable<double> TLDEGERI_SATIS { get; set; }
    }
}
