//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_TESTSRS
    {
        public int LOG_REC { get; set; }
        public Nullable<byte> LOG_STATE { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public string LOG_USER { get; set; }
        public string LOG_SQL_USER { get; set; }
        public Nullable<byte> LOG_PROC { get; set; }
    }
}
