//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_SERFAT
    {
        public double REF_NO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string ISLEM_TIP { get; set; }
        public bool AKTARILDI { get; set; }
    }
}
