//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_MESSAGE
    {
        public int LOG_ID { get; set; }
        public string REF_TIP { get; set; }
        public string REF_NO { get; set; }
        public Nullable<int> REF_SIRANO { get; set; }
        public string LOG_TYPE { get; set; }
        public string LOG_USER { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string MSG_ID { get; set; }
        public string MSG_TEXT { get; set; }
    }
}
