//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_FISAYR
    {
        public int ROW_ID { get; set; }
        public double FISNO { get; set; }
        public Nullable<int> SIRANO { get; set; }
        public Nullable<byte> ISLEM { get; set; }
        public Nullable<System.DateTime> ISLEM_TRH { get; set; }
        public string ISLEM_USR { get; set; }
        public string FISNUMARA { get; set; }
        public string HSPKODU { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<double> ALACAK { get; set; }
        public Nullable<double> BORC { get; set; }
        public string DOVIZ_KOD { get; set; }
        public Nullable<double> TL_DEGERI { get; set; }
        public Nullable<double> DVZ_ALACAK { get; set; }
        public Nullable<double> DVZ_BORC { get; set; }
        public Nullable<double> YEVMIYE_NO { get; set; }
        public string TUR { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<short> AY { get; set; }
        public Nullable<double> ENT_REF_NO { get; set; }
        public string ENT_REF_TIP { get; set; }
        public string MASRAFM_KOD { get; set; }
        public Nullable<double> MIKTAR { get; set; }
        public string ENT_REF_BN { get; set; }
        public string GRUP1_KOD { get; set; }
        public int FA_ID { get; set; }
        public string GRUP_KOD { get; set; }
        public string MAS_PER { get; set; }
    }
}
