//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_SATIS
    {
        public string LOG_TYPE { get; set; }
        public double LOG_REC { get; set; }
        public string LOG_BELTIP { get; set; }
        public string LOG_CARIKOD { get; set; }
        public short LOG_STATE { get; set; }
        public System.DateTime LOG_DATE { get; set; }
        public short LOG_PROC { get; set; }
        public string LOG_IRSNO { get; set; }
        public string LOG_FATNO { get; set; }
    }
}
