//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAKBUZTMP
    {
        public short MAK_ID { get; set; }
        public string MAK_TANIM { get; set; }
        public string HSP_GIDER { get; set; }
        public Nullable<double> HSP_KDV_ORAN { get; set; }
        public string HSP_KDV { get; set; }
        public string HSP_KASA { get; set; }
        public Nullable<double> HSP_STP_ORAN { get; set; }
        public string HSP_STP_KARSI { get; set; }
        public string HSP_STOPAJ { get; set; }
        public string MAK_ACIKLMA { get; set; }
    }
}
