//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAZERETAYLIK
    {
        public double ISYERI { get; set; }
        public string CAY { get; set; }
        public double PERSNO { get; set; }
        public System.DateTime IZINSA { get; set; }
        public string IS_SICNO { get; set; }
        public string MAZERETKOD { get; set; }
        public Nullable<double> SURE { get; set; }
        public string MESAISONU { get; set; }
        public string UCRET { get; set; }
    }
}
