//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAZERET
    {
        public string MAZERETKOD { get; set; }
        public string MAZERET1 { get; set; }
        public Nullable<System.DateTime> BASSA { get; set; }
        public Nullable<System.DateTime> BITSA { get; set; }
        public Nullable<System.DateTime> SURE { get; set; }
        public string TANIMLI { get; set; }
        public string UCRETLI { get; set; }
    }
}
