//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class MBILGFRM
    {
        public decimal MB_NO { get; set; }
        public Nullable<System.DateTime> MB_TRH { get; set; }
        public string MB_SATPER { get; set; }
        public string MB_SATTIP { get; set; }
        public string MB_SATSEKIL { get; set; }
        public string MB_ALICI { get; set; }
        public Nullable<System.DateTime> MB_FATTRH { get; set; }
        public Nullable<System.DateTime> MB_TESTRH { get; set; }
        public string MB_SASE { get; set; }
        public string MB_PLAKA { get; set; }
        public string MB_TAKMARKA { get; set; }
        public string MB_TAKMODEL { get; set; }
        public string MB_TAKRENK { get; set; }
        public Nullable<short> MB_TAKYIL { get; set; }
        public string MB_ONCEMARKA { get; set; }
        public string MB_ONCEMODEL { get; set; }
        public string MB_ONCERENK { get; set; }
        public Nullable<short> MB_ONCEYIL { get; set; }
        public string MB_AILEDEKI { get; set; }
        public string MB_KULLKISI { get; set; }
        public Nullable<short> MB_KACNMARKA { get; set; }
        public Nullable<short> MB_KACNBUMAR { get; set; }
        public string MB_ONCBAYI { get; set; }
        public string MB_KOD { get; set; }
        public string MB_AD { get; set; }
        public string MB_ADRES1 { get; set; }
        public string MB_ADRES2 { get; set; }
        public string MB_PK { get; set; }
        public string MB_ILCE { get; set; }
        public string MB_IL { get; set; }
        public string MB_TEL1 { get; set; }
        public string MB_TEL2 { get; set; }
        public string MB_EMAIL { get; set; }
        public Nullable<System.DateTime> MB_DTAR { get; set; }
        public string MB_DYER { get; set; }
        public string MB_CINSIYET { get; set; }
        public string MB_MEDDUR { get; set; }
        public string MB_ESAD { get; set; }
        public Nullable<System.DateTime> MB_EVLITAR { get; set; }
        public string MB_CCKAD1 { get; set; }
        public Nullable<System.DateTime> MB_CCKDT1 { get; set; }
        public string MB_CCKAD2 { get; set; }
        public Nullable<System.DateTime> MB_CCKDT2 { get; set; }
        public string MB_CCKAD3 { get; set; }
        public Nullable<System.DateTime> MB_CCKDT3 { get; set; }
        public string MB_SIRKET { get; set; }
        public string MB_SIRADR { get; set; }
        public string MB_SIRPK { get; set; }
        public string MB_SIRILCE { get; set; }
        public string MB_SIRIL { get; set; }
        public string MB_SIRTEL { get; set; }
        public string MB_SIRFAX { get; set; }
        public string MB_SEKTOR { get; set; }
        public string MB_FAALCINS { get; set; }
        public Nullable<short> MB_SIRPARK { get; set; }
        public string MB_SIRARAC { get; set; }
        public string MB_OGRENIM { get; set; }
        public string MB_ISDURUM { get; set; }
        public string MB_MESLEK { get; set; }
        public string MB_UNVAN { get; set; }
        public string MB_KKART { get; set; }
        public string MB_KKBANKA { get; set; }
        public Nullable<short> MB_TERCNED1 { get; set; }
        public Nullable<short> MB_TERCNED2 { get; set; }
        public Nullable<short> MB_TERCNED3 { get; set; }
        public string MB_TERDIGER { get; set; }
        public Nullable<short> MB_TVKANAL1 { get; set; }
        public Nullable<short> MB_TVKANAL2 { get; set; }
        public Nullable<short> MB_TVKANAL3 { get; set; }
        public Nullable<short> MB_GAZETE1 { get; set; }
        public Nullable<short> MB_GAZETE2 { get; set; }
        public Nullable<short> MB_GAZETE3 { get; set; }
        public Nullable<short> MB_DERGI1 { get; set; }
        public Nullable<short> MB_DERGI2 { get; set; }
        public Nullable<short> MB_DERGI3 { get; set; }
        public string MB_OZEL1 { get; set; }
        public string MB_OZEL2 { get; set; }
        public string MB_OZEL3 { get; set; }
        public string MB_OZEL4 { get; set; }
        public string MB_OZEL5 { get; set; }
        public string MB_NOT { get; set; }
        public bool MB_AKTARILDI { get; set; }
        public string MB_TEL3 { get; set; }
        public string MB_URL { get; set; }
        public string MB_YETAD { get; set; }
        public string MB_YETSOY { get; set; }
        public string MB_TEL4 { get; set; }
        public string MB_KIMLIKNO { get; set; }
        public Nullable<double> MB_PMNO { get; set; }
        public string MB_AD2 { get; set; }
    }
}
