//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOBSER
    {
        public string SASI_NO { get; set; }
        public System.DateTime TARIH { get; set; }
        public Nullable<double> KM { get; set; }
        public string MARKA { get; set; }
        public string MODEL { get; set; }
        public string ARAC_TIP { get; set; }
        public Nullable<System.DateTime> TRAFIK_CIK_TRH { get; set; }
        public string PLAKA_NO { get; set; }
        public string RENK_KOD { get; set; }
        public string CARI_KOD { get; set; }
        public string ARIZAADRES { get; set; }
        public string ARIZAADRES1 { get; set; }
        public string ARIZATELNO { get; set; }
        public string IHBARKISI { get; set; }
        public Nullable<System.DateTime> ARAMATARIH { get; set; }
        public Nullable<double> SRV_CIK_KM { get; set; }
        public Nullable<double> SRV_DON_KM { get; set; }
        public Nullable<System.DateTime> SRV_CIK_TRH { get; set; }
        public Nullable<System.DateTime> ONAR_BAS_SAAT { get; set; }
        public Nullable<System.DateTime> ONAR_BIT_SAAT { get; set; }
        public string PERSON_KOD { get; set; }
        public Nullable<double> TUTAR { get; set; }
        public Nullable<double> KDV { get; set; }
        public Nullable<double> TOPLAM { get; set; }
        public string ARIZA_NEDEI { get; set; }
        public string NOTLAR { get; set; }
        public string ISLEMPARCA { get; set; }
        public string ARIZA_KOD { get; set; }
        public string IKS_NO { get; set; }
    }
}
