//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODULOG
    {
        public string NETADDR { get; set; }
        public string NETPROT { get; set; }
        public string MODULNAME { get; set; }
        public Nullable<System.DateTime> LOGINTIME { get; set; }
        public string USERNAME { get; set; }
        public string MODULVER { get; set; }
        public Nullable<byte> LOG_TYPE { get; set; }
        public string LOG_DETAIL { get; set; }
    }
}
