//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOTOR
    {
        public string MOTOR_TIP { get; set; }
        public Nullable<short> MOTOR_HACMI { get; set; }
        public string MOTOR_SILIN_SAY { get; set; }
        public string SANZIMAN_TIPI { get; set; }
    }
}
