//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSAYFA
    {
        public string PASADI { get; set; }
        public string QUIKAD { get; set; }
        public Nullable<short> FONTSIZE { get; set; }
        public string FONTADI { get; set; }
        public string FONTRENK { get; set; }
        public Nullable<short> SAYFAGEN { get; set; }
        public Nullable<short> SAYFAYUK { get; set; }
        public string SAYFAISIM { get; set; }
        public string PRBICIMI { get; set; }
        public Nullable<short> SEC1 { get; set; }
        public Nullable<short> SEC2 { get; set; }
        public Nullable<short> SEC3 { get; set; }
        public Nullable<short> SEC4 { get; set; }
        public Nullable<short> SEC5 { get; set; }
        public Nullable<System.DateTime> TARIHBAS { get; set; }
        public Nullable<System.DateTime> TARIHSON { get; set; }
        public string KODBAS { get; set; }
        public string KODSON { get; set; }
        public Nullable<short> SAG { get; set; }
        public Nullable<short> SOL { get; set; }
        public Nullable<short> UST { get; set; }
        public Nullable<short> ALT { get; set; }
    }
}
