//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUHBAG
    {
        public int BAG_NO { get; set; }
        public string BAG_TANIM { get; set; }
        public Nullable<byte> BAG_TIP { get; set; }
        public string BAG_GRUP1 { get; set; }
        public string BAG_GRUP2 { get; set; }
        public string BAG_GRUP3 { get; set; }
        public Nullable<byte> BAG_KDV { get; set; }
        public Nullable<byte> BAG_OTV { get; set; }
        public Nullable<byte> BAG_UYGULA { get; set; }
        public string MUH_A { get; set; }
        public string MUH_S { get; set; }
        public string MUH_ISK_A { get; set; }
        public string MUH_ISK_S { get; set; }
        public string MUH_KDV_A { get; set; }
        public string MUH_KDV_S { get; set; }
        public string MUH_IADE_A { get; set; }
        public string MUH_IADE_S { get; set; }
        public string MUH_IADE_KDV_A { get; set; }
        public string MUH_IADE_KDV_S { get; set; }
        public string MUH_GRSAT { get; set; }
        public string MUH_GRSATISK { get; set; }
        public string MUH_OTV_A { get; set; }
        public string MUH_OTV_S { get; set; }
    }
}
