//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUHDEP
    {
        public byte DEP_NO { get; set; }
        public string DEP1 { get; set; }
        public string DEP2 { get; set; }
        public string DEP3 { get; set; }
        public string DEP4 { get; set; }
        public string DEP5 { get; set; }
    }
}
