//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUHKISAYOL
    {
        public int MENU_ID { get; set; }
        public Nullable<int> MENU_EKRAN { get; set; }
        public string MENU_TANIM { get; set; }
        public Nullable<int> KISAYOL_KEY { get; set; }
        public string KISAYOL_TEXT { get; set; }
    }
}
