//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUHKDVAYR
    {
        public string MUHKDV_KOD { get; set; }
        public double KDV { get; set; }
        public string MUH_KDV_A { get; set; }
        public string MUH_KDV_S { get; set; }
        public string MUH_KDV_A_IADE { get; set; }
        public string MUH_KDV_S_IADE { get; set; }
    }
}
