//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUHRAPA
    {
        public int NUM { get; set; }
        public int SIRANO { get; set; }
        public byte BS_NO { get; set; }
        public string MUHKOD { get; set; }
        public Nullable<double> SAYI { get; set; }
        public Nullable<double> ORAN { get; set; }
    }
}
