//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUHRAPM
    {
        public int NUM { get; set; }
        public int SIRANO { get; set; }
        public string SIRAKOD { get; set; }
        public string ACIKLAMA { get; set; }
        public string SINIF { get; set; }
        public string UGRUP { get; set; }
        public string AGRUP { get; set; }
        public string ANA { get; set; }
        public string TUR { get; set; }
        public string TIP { get; set; }
        public string SEVIYE { get; set; }
    }
}
