//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUHRAPBS
    {
        public byte BS_NO { get; set; }
        public string BS_AD { get; set; }
        public Nullable<short> BS_ANADP { get; set; }
        public string BS_ANAHS { get; set; }
    }
}
