//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWFISY
    {
        public short SIRKETNO { get; set; }
        public short MYIL { get; set; }
        public string TIP { get; set; }
        public Nullable<double> YEVMIYE_NO { get; set; }
        public string ORTAK_SB { get; set; }
        public Nullable<double> ORTAK_NO { get; set; }
        public string TAHSIL_SB { get; set; }
        public Nullable<double> TAHSILNO1 { get; set; }
        public string TEDIYE_SB { get; set; }
        public Nullable<double> TEDIYENO1 { get; set; }
        public string MAHSUP_SB { get; set; }
        public Nullable<double> MAHSUPNO1 { get; set; }
        public string OZEL_SB { get; set; }
        public Nullable<double> OZEL1 { get; set; }
    }
}
