//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class OQ
    {
        public short OQ_YIL { get; set; }
        public string OQ_MODEL { get; set; }
        public string OQ_RENK { get; set; }
        public Nullable<short> OQ_1 { get; set; }
        public Nullable<short> RQ_1 { get; set; }
        public Nullable<short> OQ_2 { get; set; }
        public Nullable<short> RQ_2 { get; set; }
        public Nullable<short> OQ_3 { get; set; }
        public Nullable<short> RQ_3 { get; set; }
        public Nullable<short> OQ_4 { get; set; }
        public Nullable<short> RQ_4 { get; set; }
        public Nullable<short> OQ_5 { get; set; }
        public Nullable<short> RQ_5 { get; set; }
        public Nullable<short> OQ_6 { get; set; }
        public Nullable<short> RQ_6 { get; set; }
        public Nullable<short> OQ_7 { get; set; }
        public Nullable<short> RQ_7 { get; set; }
        public Nullable<short> OQ_8 { get; set; }
        public Nullable<short> RQ_8 { get; set; }
        public Nullable<short> OQ_9 { get; set; }
        public Nullable<short> RQ_9 { get; set; }
        public Nullable<short> OQ_10 { get; set; }
        public Nullable<short> RQ_10 { get; set; }
        public Nullable<short> OQ_11 { get; set; }
        public Nullable<short> RQ_11 { get; set; }
        public Nullable<short> OQ_12 { get; set; }
        public Nullable<short> RQ_12 { get; set; }
        public Nullable<short> OQ_TOP { get; set; }
        public Nullable<short> RQ_TOP { get; set; }
    }
}
