//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class OQDET
    {
        public short OQ_YIL { get; set; }
        public short OQ_AY { get; set; }
        public string OQ_MODEL { get; set; }
        public Nullable<short> POQ { get; set; }
        public Nullable<short> TOQ { get; set; }
        public Nullable<short> TRQ { get; set; }
        public Nullable<short> OQ_R01 { get; set; }
        public Nullable<short> RQ_R01 { get; set; }
        public Nullable<short> OQ_R02 { get; set; }
        public Nullable<short> RQ_R02 { get; set; }
        public Nullable<short> OQ_R03 { get; set; }
        public Nullable<short> RQ_R03 { get; set; }
        public Nullable<short> OQ_R04 { get; set; }
        public Nullable<short> RQ_R04 { get; set; }
        public Nullable<short> OQ_R05 { get; set; }
        public Nullable<short> RQ_R05 { get; set; }
        public Nullable<short> OQ_R06 { get; set; }
        public Nullable<short> RQ_R06 { get; set; }
        public Nullable<short> OQ_R07 { get; set; }
        public Nullable<short> RQ_R07 { get; set; }
        public Nullable<short> OQ_R08 { get; set; }
        public Nullable<short> RQ_R08 { get; set; }
        public Nullable<short> OQ_R09 { get; set; }
        public Nullable<short> RQ_R09 { get; set; }
        public Nullable<short> OQ_R10 { get; set; }
        public Nullable<short> RQ_R10 { get; set; }
        public Nullable<short> OQ_R11 { get; set; }
        public Nullable<short> RQ_R11 { get; set; }
        public Nullable<short> OQ_R12 { get; set; }
        public Nullable<short> RQ_R12 { get; set; }
        public Nullable<short> OQ_R13 { get; set; }
        public Nullable<short> RQ_R13 { get; set; }
        public Nullable<short> OQ_R14 { get; set; }
        public Nullable<short> RQ_R14 { get; set; }
        public Nullable<short> OQ_R15 { get; set; }
        public Nullable<short> RQ_R15 { get; set; }
        public Nullable<short> OQ_R16 { get; set; }
        public Nullable<short> RQ_R16 { get; set; }
        public Nullable<short> OQ_R17 { get; set; }
        public Nullable<short> RQ_R17 { get; set; }
        public Nullable<short> OQ_R18 { get; set; }
        public Nullable<short> RQ_R18 { get; set; }
        public Nullable<short> OQ_R19 { get; set; }
        public Nullable<short> RQ_R19 { get; set; }
        public Nullable<short> OQ_R20 { get; set; }
        public Nullable<short> RQ_R20 { get; set; }
        public Nullable<short> OQ_R21 { get; set; }
        public Nullable<short> RQ_R21 { get; set; }
        public Nullable<short> OQ_R22 { get; set; }
        public Nullable<short> RQ_R22 { get; set; }
        public Nullable<short> OQ_R23 { get; set; }
        public Nullable<short> RQ_R23 { get; set; }
        public Nullable<short> OQ_R24 { get; set; }
        public Nullable<short> RQ_R24 { get; set; }
        public Nullable<short> OQ_R25 { get; set; }
        public Nullable<short> RQ_R25 { get; set; }
        public Nullable<short> OQ_R26 { get; set; }
        public Nullable<short> RQ_R26 { get; set; }
        public Nullable<short> OQ_R27 { get; set; }
        public Nullable<short> RQ_R27 { get; set; }
        public Nullable<short> OQ_R28 { get; set; }
        public Nullable<short> RQ_R28 { get; set; }
        public Nullable<short> OQ_R29 { get; set; }
        public Nullable<short> RQ_R29 { get; set; }
        public Nullable<short> OQ_R30 { get; set; }
        public Nullable<short> RQ_R30 { get; set; }
        public Nullable<short> OQ_R31 { get; set; }
        public Nullable<short> RQ_R31 { get; set; }
        public Nullable<short> OQ_R32 { get; set; }
        public Nullable<short> RQ_R32 { get; set; }
        public Nullable<short> OQ_R33 { get; set; }
        public Nullable<short> RQ_R33 { get; set; }
        public Nullable<short> OQ_R34 { get; set; }
        public Nullable<short> RQ_R34 { get; set; }
        public Nullable<short> OQ_R35 { get; set; }
        public Nullable<short> RQ_R35 { get; set; }
        public Nullable<short> OQ_R36 { get; set; }
        public Nullable<short> RQ_R36 { get; set; }
        public Nullable<short> OQ_R37 { get; set; }
        public Nullable<short> RQ_R37 { get; set; }
        public Nullable<short> OQ_R38 { get; set; }
        public Nullable<short> RQ_R38 { get; set; }
        public Nullable<short> OQ_R39 { get; set; }
        public Nullable<short> RQ_R39 { get; set; }
        public Nullable<short> OQ_R40 { get; set; }
        public Nullable<short> RQ_R40 { get; set; }
    }
}
