//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class OZELLIK
    {
        public int OZ_ID { get; set; }
        public string OZ_GRUP { get; set; }
        public string OZ_ADI { get; set; }
        public Nullable<byte> OZ_RENK { get; set; }
        public Nullable<short> OZ_SIRA { get; set; }
    }
}
