//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMUSER
    {
        public string PARAM_ID { get; set; }
        public string PARAM_VALUE { get; set; }
        public string PARAM_INFO { get; set; }
        public Nullable<byte> PARAM_TYPE { get; set; }
    }
}
