//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMKEY
    {
        public string KEY1 { get; set; }
        public Nullable<int> KEY2 { get; set; }
        public Nullable<int> KEY3 { get; set; }
        public Nullable<double> NUM1 { get; set; }
        public Nullable<double> NUM2 { get; set; }
        public Nullable<double> NUM3 { get; set; }
        public string TEXT1 { get; set; }
        public string TEXT2 { get; set; }
        public Nullable<System.DateTime> DATE1 { get; set; }
        public Nullable<System.DateTime> DATE2 { get; set; }
    }
}
