//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMET
    {
        public Nullable<short> GARANTI_SURE { get; set; }
        public string FATYUVARTIP { get; set; }
        public Nullable<double> YUVARSAYI { get; set; }
        public Nullable<double> ARAC_YIPRANMA_X { get; set; }
        public Nullable<double> STOK_ISKONTO { get; set; }
        public Nullable<double> ACIL_ISKONTO { get; set; }
        public Nullable<short> POQ_AYL_SAP { get; set; }
        public Nullable<short> POQ_YIL_SAP { get; set; }
        public Nullable<double> CLAIM_PRC_ISK { get; set; }
        public Nullable<double> CLAIM_ISC_ISK { get; set; }
        public Nullable<double> POQ_OQ_AY { get; set; }
        public Nullable<System.DateTime> STOK_DEVIR_TRH { get; set; }
        public Nullable<short> NEGATIF_STOK { get; set; }
        public Nullable<byte> IZIN_YPAD { get; set; }
        public Nullable<byte> IZIN_YPFYT { get; set; }
        public Nullable<byte> IZIN_ISAD { get; set; }
        public Nullable<byte> IZIN_ISFYT { get; set; }
        public Nullable<byte> IZIN_FTAD { get; set; }
        public Nullable<byte> IZIN_FTFYT { get; set; }
        public Nullable<byte> IZIN_YPISK { get; set; }
        public Nullable<byte> IZIN_ISISK { get; set; }
        public Nullable<byte> IZIN_FTISK { get; set; }
        public Nullable<byte> FTISKTIP { get; set; }
        public Nullable<short> MALIYET_UYARI { get; set; }
        public string ISCILIK_PRG_YOL { get; set; }
        public string ISC_MARK { get; set; }
        public Nullable<short> BEKLE_GUN { get; set; }
        public Nullable<System.DateTime> FAT_KILIT_TRH { get; set; }
        public Nullable<short> EKSIK_ALAN_UYARI { get; set; }
        public short DOVIZLI_BKY { get; set; }
        public string ISMR_ACIKLAMA { get; set; }
        public Nullable<double> ISCLIK_UCR_TOP { get; set; }
        public Nullable<double> CALIS_GUN { get; set; }
        public Nullable<double> GUN_CALIS_SAAT { get; set; }
        public Nullable<byte> IKI_CARIHRK { get; set; }
        public Nullable<byte> STK_MALIYET { get; set; }
        public Nullable<byte> ARCSAT_MAXISK { get; set; }
        public string IKI_CRISKKONTROL { get; set; }
        public string KAPFORM_ISK { get; set; }
        public byte DIGER01 { get; set; }
        public string CARIMSGVAR { get; set; }
        public Nullable<short> SATSIP_ACIKLAMA { get; set; }
        public Nullable<byte> MODUL_SEVK { get; set; }
        public string TAKIP_LINK { get; set; }
        public string FILE_PATH { get; set; }
        public string GR_BEDELSIZ_SIP { get; set; }
        public string GARANTI_BEDELSIZ { get; set; }
        public Nullable<byte> MALIYETFYT_YAZMA { get; set; }
        public string ISCPER_SECME { get; set; }
        public string TRFC_TRH_ZORUNLU { get; set; }
        public Nullable<double> YAKIT_KMBRM_TUTAR { get; set; }
    }
}
