//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARMTRX
    {
        public string TUR { get; set; }
        public Nullable<short> YEDEK_PARCA { get; set; }
        public Nullable<short> YAG { get; set; }
        public Nullable<short> AKSESUAR { get; set; }
        public Nullable<short> SARF { get; set; }
    }
}
