//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDIFORMU
    {
        public string SASI_NO { get; set; }
        public System.DateTime TARIH { get; set; }
        public string MOTOR_NO { get; set; }
        public Nullable<double> KM { get; set; }
        public string MARKA { get; set; }
        public string MODEL { get; set; }
        public string ARAC_TIP { get; set; }
        public string FORMNO { get; set; }
        public string RENK_KOD { get; set; }
        public string KONANAHNO { get; set; }
        public string IMTANIMKOD { get; set; }
        public string IMTANIMSIF { get; set; }
        public string RADYOTANIMKOD { get; set; }
        public string RADYOTANIMSIF { get; set; }
        public string K1_MNOSIPK { get; set; }
        public string K2_MTS { get; set; }
        public string K_ABEBAUBK { get; set; }
        public string K3_ARCRENK { get; set; }
        public string K4_KOLTIKICDOS { get; set; }
        public string K5_RADANTHOP { get; set; }
        public string K6_MERILITAL { get; set; }
        public string K7_LASTEKJANT { get; set; }
        public string K8_SUNROOF { get; set; }
        public string K9_ARCKULKIT { get; set; }
        public string K10_MODGOREDONEK { get; set; }
        public string K11_HASARINC { get; set; }
        public string K12_ARCANHTAMMI { get; set; }
        public string K13_KAPIKOLBEN { get; set; }
        public string K14_ALRMCAL { get; set; }
        public string K15_AKUYUK { get; set; }
        public string K16_ELKABLO { get; set; }
        public string K17_MOTSANSOG { get; set; }
        public string K18_MOTSANSOGCUB { get; set; }
        public string K19_DIREKHID { get; set; }
        public string K20_FRENHID { get; set; }
        public string K21_RADYOTOR { get; set; }
        public string K22_CAMYIKA { get; set; }
        public string K23_EMNKEMER { get; set; }
        public string K24_TAMTAKIM { get; set; }
        public string K25_TABANKORU { get; set; }
        public string K26_MOTORSANAKS { get; set; }
        public string KONTROL_PERSON_KOD { get; set; }
    }
}
