//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDIMAST
    {
        public string PDI_NO { get; set; }
        public string MOTOR_NO { get; set; }
        public string SASE_NO { get; set; }
        public string MODEL_KODU { get; set; }
        public string MODEL_ADI { get; set; }
        public string MODEL_SERISI { get; set; }
        public string RENK_KODU { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string LASTIK_MARKASI { get; set; }
        public string AKU_MARKASI { get; set; }
        public string ONAY_VEREN { get; set; }
        public string ANAHTAR_KNL_NO { get; set; }
        public string IMM_KNT_KOD { get; set; }
        public string TEYP_KOD { get; set; }
        public string BIJON_SIFRE { get; set; }
        public bool AKTARILDI { get; set; }
        public string PER_KOD { get; set; }
        public Nullable<double> FIILI_SURE { get; set; }
        public string IC_RENK { get; set; }
    }
}
