//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDKSOKUM
    {
        public System.DateTime TARIH { get; set; }
        public string CIHAZ_ID { get; set; }
        public System.DateTime SAATBAS { get; set; }
        public System.DateTime SAATBIT { get; set; }
        public string IENO { get; set; }
        public string TIPKOD { get; set; }
        public Nullable<double> FSURE { get; set; }
        public Nullable<int> SIRANO_BAS { get; set; }
        public Nullable<int> SIRANO_SON { get; set; }
        public Nullable<double> PERSNO { get; set; }
        public Nullable<double> GEL_GEC { get; set; }
        public Nullable<double> GEL_ERKEN { get; set; }
        public Nullable<double> GIT_GEC { get; set; }
        public Nullable<double> GIT_ERKEN { get; set; }
        public Nullable<double> ISYERI { get; set; }
        public string CAY { get; set; }
        public string UCRETLI { get; set; }
        public string TATIL { get; set; }
    }
}
