//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDKSOKU
    {
        public System.DateTime TARIH { get; set; }
        public string CIHAZ_ID { get; set; }
        public System.DateTime SAAT { get; set; }
        public string IENO { get; set; }
        public string TIPKOD { get; set; }
        public Nullable<int> SIRANO { get; set; }
        public Nullable<double> ISYERINO { get; set; }
        public string CAY { get; set; }
    }
}
