//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDKS
    {
        public double ISYERINO { get; set; }
        public string CAY { get; set; }
        public string IS_SICNO { get; set; }
        public System.DateTime TARIH { get; set; }
        public System.DateTime GIRSA { get; set; }
        public Nullable<double> KAYITNO { get; set; }
        public string ADISOYADI { get; set; }
        public string MAZERET { get; set; }
        public string UCRETLI { get; set; }
        public string GIRCIK { get; set; }
        public Nullable<double> DONME { get; set; }
        public string PDKSKART_ID { get; set; }
        public Nullable<int> PDKS_SIRANO { get; set; }
    }
}
