//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEREGIT
    {
        public string ISCI_KOD { get; set; }
        public Nullable<double> SIRA_NO { get; set; }
        public string KURS_KOD { get; set; }
        public Nullable<System.DateTime> BAS_TARIH { get; set; }
        public Nullable<System.DateTime> BIT_TARIH { get; set; }
        public string KURS_AD { get; set; }
        public Nullable<double> TOPLAM_SAAT { get; set; }
    }
}
