//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERIYOT
    {
        public string SAT_SER { get; set; }
        public string ARA_TIP { get; set; }
        public int PER_GUN { get; set; }
        public string PER_AD { get; set; }
        public Nullable<int> ANKET_ID { get; set; }
    }
}
