//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEROZGEC
    {
        public double ISYERINO { get; set; }
        public double PERSNO { get; set; }
        public string YETENEK1 { get; set; }
        public string YETENEK2 { get; set; }
        public string YABANCI_DIL { get; set; }
        public string ALISKANLIK { get; set; }
        public string REFERANS1 { get; set; }
        public string REFERANS2 { get; set; }
        public string GELIR_DUZ { get; set; }
        public string TECRUBESI { get; set; }
        public string DERNEK_VAKIF1 { get; set; }
        public string DERNEK_VAKIF2 { get; set; }
        public string OTOMOBIL { get; set; }
        public string MENKUL { get; set; }
        public string ONCESIG { get; set; }
        public string ONCEKI_ISYERI1 { get; set; }
        public string CAL1ISILI { get; set; }
        public string CAL1ISIADRESI1 { get; set; }
        public string ONCEKI_ISYERI2 { get; set; }
        public string OGRENIMDURUM { get; set; }
    }
}
