//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEROKUM
    {
        public Nullable<System.DateTime> TARIH { get; set; }
        public string CIHAZ_ID { get; set; }
        public Nullable<System.DateTime> SAATBAS { get; set; }
        public Nullable<System.DateTime> SAATBIT { get; set; }
        public string IENO { get; set; }
        public string TIPKOD { get; set; }
        public Nullable<double> FIILISURE { get; set; }
        public string ARIZA_KODU { get; set; }
        public Nullable<int> SIRANO_BAS { get; set; }
        public Nullable<int> SIRANO_SON { get; set; }
        public string PER_KOD { get; set; }
        public string IS_TIP { get; set; }
        public Nullable<double> SATILAN_SURE { get; set; }
        public int SIRANO { get; set; }
        public Nullable<short> IE_SIRANO { get; set; }
    }
}
