//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERRAPPRM
    {
        public short PRM_NO { get; set; }
        public string PRM_BASLIK { get; set; }
        public Nullable<byte> PRM_TIP { get; set; }
        public string PRM_DEGER { get; set; }
        public Nullable<byte> PRM_SIRA { get; set; }
    }
}
