//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERRAP
    {
        public short RP_YIL { get; set; }
        public short RP_AY { get; set; }
        public int ISYERINO { get; set; }
        public string SICILNO { get; set; }
        public string DEPKOD { get; set; }
        public string DEPADI { get; set; }
        public string PER_ADI { get; set; }
        public Nullable<double> TOPLAM { get; set; }
        public Nullable<double> DOVIZ_KUR { get; set; }
        public Nullable<double> TOPLAM_DVZ { get; set; }
        public Nullable<double> G1 { get; set; }
        public Nullable<double> G2 { get; set; }
        public Nullable<double> G3 { get; set; }
        public Nullable<double> G4 { get; set; }
        public Nullable<double> G5 { get; set; }
        public Nullable<double> G6 { get; set; }
        public Nullable<double> G7 { get; set; }
        public Nullable<double> G8 { get; set; }
        public Nullable<double> G9 { get; set; }
        public Nullable<double> G10 { get; set; }
        public Nullable<double> G11 { get; set; }
        public Nullable<double> G12 { get; set; }
        public Nullable<double> G13 { get; set; }
        public Nullable<double> G14 { get; set; }
        public Nullable<double> G15 { get; set; }
        public Nullable<double> G16 { get; set; }
        public Nullable<double> G17 { get; set; }
        public Nullable<double> G18 { get; set; }
        public Nullable<double> G19 { get; set; }
        public Nullable<double> G20 { get; set; }
        public Nullable<double> G21 { get; set; }
        public Nullable<double> G22 { get; set; }
        public Nullable<double> G23 { get; set; }
        public Nullable<double> G24 { get; set; }
        public Nullable<double> G25 { get; set; }
        public Nullable<double> G26 { get; set; }
        public Nullable<double> G27 { get; set; }
        public Nullable<double> G28 { get; set; }
        public Nullable<double> G29 { get; set; }
        public Nullable<double> G30 { get; set; }
        public Nullable<System.DateTime> BASLA_TRH { get; set; }
        public Nullable<short> ANADEP { get; set; }
    }
}
