//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERS_SIGPRIM
    {
        public double ISYERINO { get; set; }
        public double PERSNO { get; set; }
        public string AY { get; set; }
        public Nullable<short> YIL { get; set; }
        public short SIRANO { get; set; }
        public string TIP { get; set; }
        public Nullable<double> TUTAR { get; set; }
    }
}
