//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERS_MAAS
    {
        public double ISYERINO { get; set; }
        public double PERSNO { get; set; }
        public System.DateTime YURURTARIH { get; set; }
        public Nullable<double> BELIRLEBRUT { get; set; }
        public Nullable<double> BRUT_MAAS { get; set; }
        public Nullable<double> BRUT_UCRET { get; set; }
        public string BRUTMU { get; set; }
        public string UCRET_TIPI { get; set; }
        public string VAR_KODU { get; set; }
        public string VARISCI { get; set; }
        public string VERGIMUAF { get; set; }
        public Nullable<double> OZEL_SIG_PRM { get; set; }
        public string ASGARI_UCRETLI { get; set; }
    }
}
