//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERS_BC
    {
        public double ISYERINO { get; set; }
        public double PERSNO { get; set; }
        public System.DateTime BASLA_TRH { get; set; }
        public Nullable<System.DateTime> CIKIS_TRH { get; set; }
        public string CIKNEDENI { get; set; }
        public string ACIKLAMA { get; set; }
        public string CIKAY { get; set; }
        public string CIKYIL { get; set; }
    }
}
