//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERS_COCUK
    {
        public double ISYERINO { get; set; }
        public double PERSNO { get; set; }
        public double COCUKNO { get; set; }
        public string KIMLIKNO { get; set; }
        public string ADI { get; set; }
        public string SOYADI { get; set; }
        public Nullable<System.DateTime> DOGUM_TRH { get; set; }
        public string BABA { get; set; }
        public string ANA { get; set; }
        public string CINSIYET { get; set; }
        public string YAKINLIK { get; set; }
        public Nullable<System.DateTime> OKUL_KAYIT_TRH { get; set; }
        public string OKUL_ADI { get; set; }
        public string SINIFI { get; set; }
    }
}
