//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSMUH
    {
        public double ISYERINO { get; set; }
        public double PERSNO { get; set; }
        public string M_BRUT { get; set; }
        public string M_SSK_ISVER_PR { get; set; }
        public string M_SSK_ODE_PR { get; set; }
        public string M_DAMGAV { get; set; }
        public string M_GELIRV { get; set; }
        public string M_NET { get; set; }
        public string M_EK_KESINTI { get; set; }
        public string M_ODE_ISIZ_SG_PR { get; set; }
        public string M_ISIZ_SG_ISV_KES { get; set; }
        public string M_ODESSKP_ISVER { get; set; }
        public string M_ODESSKP_ISCI { get; set; }
        public string M_ODE_ISIZ_P_ISCI { get; set; }
        public string M_ODE_ISIZ_P_ISVER { get; set; }
        public string M_EKGELIR { get; set; }
        public string M_IHBAR { get; set; }
        public string M_KIDEM { get; set; }
        public string M_TTF_ISVER { get; set; }
        public string M_ODETAS { get; set; }
        public string M_OGI { get; set; }
        public string M_OGIDAMGAV { get; set; }
        public string M_ODEOGI { get; set; }
        public string M_FAZLAMESAI { get; set; }
        public string M_AGI { get; set; }
        public string M_AVANS { get; set; }
        public string M_EK_KESINTI2 { get; set; }
    }
}
