//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        public double ISYERINO { get; set; }
        public double PERSNO { get; set; }
        public string IS_SICNO { get; set; }
        public string SIG_SICNO { get; set; }
        public string ILKSIC { get; set; }
        public string CD { get; set; }
        public string ADI { get; set; }
        public string SOYADI { get; set; }
        public string ADRES1 { get; set; }
        public string ADRES2 { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string FAKS { get; set; }
        public string E_MAIL { get; set; }
        public string ACIL { get; set; }
        public string SIGORTALI { get; set; }
        public Nullable<System.DateTime> BASLA_TRH { get; set; }
        public Nullable<System.DateTime> CIKIS_TRH { get; set; }
        public string DEPRT_NO { get; set; }
        public string BOLUM { get; set; }
        public string MESLEGI { get; set; }
        public string SICILI { get; set; }
        public string ADSOY { get; set; }
        public string VERGIKIMLIKNO { get; set; }
        public Nullable<double> ONCYILIZIN { get; set; }
        public Nullable<double> YILICIKUMVM { get; set; }
        public Nullable<double> YILICIKUMV { get; set; }
        public Nullable<double> GYILKUMVM { get; set; }
        public Nullable<double> GYILKUMV { get; set; }
        public string PDKSKART_ID { get; set; }
        public string MESLEK_KODU { get; set; }
    }
}
