//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERS_NUF
    {
        public double ISYERINO { get; set; }
        public double PERSNO { get; set; }
        public string BABA { get; set; }
        public string ANA { get; set; }
        public Nullable<System.DateTime> DOGUM_TRH { get; set; }
        public Nullable<double> YAS { get; set; }
        public string DOGUM_YER { get; set; }
        public byte[] RESMI { get; set; }
        public string ILI { get; set; }
        public string ILCE { get; set; }
        public string HANE_NO { get; set; }
        public string CILT_NO { get; set; }
        public string SAYFA_NO { get; set; }
        public Nullable<System.DateTime> NUFUSCUZ_TRH { get; set; }
        public string NUFUSCUZ_NO { get; set; }
        public string MEDENI_HAL { get; set; }
        public string CINSIYET { get; set; }
        public string UYRUGU { get; set; }
        public string DOGYERYIL { get; set; }
        public string KOYMAH { get; set; }
        public string KIMLIKNO { get; set; }
        public string OZELDRM { get; set; }
        public string KANGRUBU { get; set; }
        public string ESKI_SOYADI { get; set; }
    }
}
