//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERS_AYR
    {
        public double ISYERINO { get; set; }
        public double PERSNO { get; set; }
        public string UCRET_TIPI { get; set; }
        public Nullable<double> VARDFARK { get; set; }
        public string SIGAORTA { get; set; }
        public string VARISCI { get; set; }
        public string OZEL_DUR_KOD { get; set; }
        public string GOREVI { get; set; }
        public string VAR_KODU { get; set; }
        public Nullable<double> BELIRLEBRUT { get; set; }
        public Nullable<double> BRUT_UCRET { get; set; }
        public Nullable<double> BRUT_MAAS { get; set; }
        public string VERGI_KODU { get; set; }
        public string SENDIKASI { get; set; }
        public string GOREVKODU { get; set; }
        public Nullable<System.DateTime> CIKIS_TRH { get; set; }
        public string CIKAY { get; set; }
        public string CIKYIL { get; set; }
        public string CIKNEDENI { get; set; }
        public string SIGTIPI { get; set; }
        public string SOSYAL_KURUM { get; set; }
        public string SENDIKA { get; set; }
        public string TAS_TES_KRT { get; set; }
        public string TAS_TES_SIC_NO { get; set; }
        public string SIGAILEFERTES1 { get; set; }
        public string SIGORAILECOCFERT2 { get; set; }
        public string SIGORAILECOCFERT3 { get; set; }
        public string BASAY { get; set; }
        public string BASYIL { get; set; }
        public string ISCIKBILSOSKUR { get; set; }
        public string ISGIRBILSOSKUR { get; set; }
        public string VERGIKIMLIKNO { get; set; }
        public string BRUTMU { get; set; }
        public string ES_CALISIYOR { get; set; }
        public string ES_GELIRIVAR { get; set; }
        public string ES_GELIRACIKLA { get; set; }
        public string AGI_VAR { get; set; }
    }
}
