//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERWORKD
    {
        public double KONT_KART_NO { get; set; }
        public short SIRA_NO { get; set; }
        public string IS_TIP { get; set; }
        public string IS_EMRI_NO { get; set; }
        public Nullable<double> SATILAN_SAAT { get; set; }
        public Nullable<System.DateTime> BAS_SAAT { get; set; }
        public Nullable<System.DateTime> BIT_SAAT { get; set; }
        public Nullable<double> FIILI_SAAT { get; set; }
        public string PER_KOD { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> SAAT { get; set; }
        public Nullable<int> DOSYA_SIRA { get; set; }
    }
}
