//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERWORKM
    {
        public double KONT_KART_NO { get; set; }
        public string PER_KOD { get; set; }
        public System.DateTime TARIH { get; set; }
        public Nullable<double> VERIMLI_SAAT { get; set; }
        public Nullable<double> CALIS_SAAT { get; set; }
        public Nullable<double> SATILAN_SAAT { get; set; }
        public bool UCRETLI_MOLA { get; set; }
        public bool AKTARILDI { get; set; }
    }
}
