//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMHAVUZT
    {
        public string PM_AD { get; set; }
        public string PM_AD2 { get; set; }
        public string PM_YETAD { get; set; }
        public string PM_YETSOY { get; set; }
        public string PM_CINSIYET { get; set; }
        public string PM_ADRES1 { get; set; }
        public string PM_ADRES2 { get; set; }
        public string PM_PK { get; set; }
        public string PM_SEMT { get; set; }
        public string PM_IL { get; set; }
        public string PM_TEL1 { get; set; }
        public string PM_TEL2 { get; set; }
        public string PM_TEL3 { get; set; }
        public string PM_TEL4 { get; set; }
        public string PM_FAKS { get; set; }
        public string PM_EMAIL { get; set; }
        public string PM_URL { get; set; }
        public string PM_SEKTOR { get; set; }
        public string PM_MESLEK { get; set; }
        public string PM_STATU { get; set; }
        public string PM_OZEL1 { get; set; }
    }
}
