//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLIKOM
    {
        public string SIGCARI_KOD { get; set; }
        public string SIG_KOD { get; set; }
        public string POL_TIP { get; set; }
        public Nullable<double> KOM_ORAN { get; set; }
        public string MUH_SIG { get; set; }
        public string MUH_VER1 { get; set; }
        public string MUH_VER2 { get; set; }
        public string MUH_KOM { get; set; }
    }
}
