//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class POQ_ANAMODEL
    {
        public short POQ_YIL { get; set; }
        public string POQ_ANAMODEL1 { get; set; }
        public Nullable<short> POQ_1 { get; set; }
        public Nullable<short> POQ_2 { get; set; }
        public Nullable<short> POQ_3 { get; set; }
        public Nullable<short> POQ_4 { get; set; }
        public Nullable<short> POQ_5 { get; set; }
        public Nullable<short> POQ_6 { get; set; }
        public Nullable<short> POQ_7 { get; set; }
        public Nullable<short> POQ_8 { get; set; }
        public Nullable<short> POQ_9 { get; set; }
        public Nullable<short> POQ_10 { get; set; }
        public Nullable<short> POQ_11 { get; set; }
        public Nullable<short> POQ_12 { get; set; }
        public Nullable<short> POQ_TOP { get; set; }
    }
}
