//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class POQLOCK
    {
        public short YIL { get; set; }
        public Nullable<bool> LOCK { get; set; }
        public Nullable<short> PO_LOCK { get; set; }
        public Nullable<short> O_LOCK { get; set; }
    }
}
