//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class POTANARA
    {
        public double PM_NO { get; set; }
        public System.DateTime TARIH { get; set; }
        public string ARANDI { get; set; }
        public string ACIKLAMA { get; set; }
        public string PER_KOD { get; set; }
        public string ARA_TIP { get; set; }
        public Nullable<System.DateTime> ARA_TRH { get; set; }
        public Nullable<System.DateTime> KAYITTRH { get; set; }
        public string KAYITUSR { get; set; }
        public Nullable<System.DateTime> DEGISTRH { get; set; }
        public string DEGISUSR { get; set; }
        public string SONUC { get; set; }
    }
}
