//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class POTANMUS
    {
        public double PM_NO { get; set; }
        public Nullable<System.DateTime> PM_TRH { get; set; }
        public string PM_PER { get; set; }
        public string PM_AD { get; set; }
        public string PM_YETAD { get; set; }
        public string PM_YETSOY { get; set; }
        public string PM_CINSIYET { get; set; }
        public string PM_MESLEK { get; set; }
        public string PM_ADRES1 { get; set; }
        public string PM_ADRES2 { get; set; }
        public string PM_PK { get; set; }
        public string PM_SEMT { get; set; }
        public string PM_IL { get; set; }
        public string PM_TEL1 { get; set; }
        public string PM_TEL2 { get; set; }
        public string PM_MODEL1 { get; set; }
        public string PM_MODEL2 { get; set; }
        public string PM_ONMARKA { get; set; }
        public string PM_ONMODEL { get; set; }
        public string PM_OZEL1 { get; set; }
        public string PM_OZEL2 { get; set; }
        public string PM_OZEL3 { get; set; }
        public Nullable<bool> PM_AKTARILDI { get; set; }
        public string PM_DURUM { get; set; }
        public string PM_IRTIBAT { get; set; }
        public string PM_ALIMSEKLI { get; set; }
        public string PM_TAKASMI { get; set; }
        public Nullable<double> PM_TAKASFYT { get; set; }
        public Nullable<double> PM_ONKM { get; set; }
        public string PM_REFERANS { get; set; }
        public string PM_NEDEN { get; set; }
        public Nullable<short> PM_ONMODYIL { get; set; }
        public Nullable<bool> PM_BILGI { get; set; }
        public string PM_TIP1 { get; set; }
        public string PM_TIP2 { get; set; }
        public Nullable<int> PM_TESTNO { get; set; }
        public string PM_DYERI { get; set; }
        public Nullable<System.DateTime> PM_DTARIH { get; set; }
        public string PM_EMAIL { get; set; }
        public string PM_URL { get; set; }
        public string PM_CARIKOD { get; set; }
        public string PM_SONDURUM { get; set; }
        public string FILOMUS { get; set; }
        public Nullable<short> MEVCUTPARK { get; set; }
        public Nullable<short> ARCDEGPERYOT { get; set; }
        public string ACIKLAMA1 { get; set; }
        public string ACIKLAMA2 { get; set; }
        public string ACIKLAMA3 { get; set; }
        public string PM_SIGORTA { get; set; }
        public string PM_ILETISIM_YOK { get; set; }
        public string PM_TEL3 { get; set; }
        public string PM_FAKS { get; set; }
        public string PM_TEL4 { get; set; }
        public string PM_STATU { get; set; }
        public string PM_SEVIYE { get; set; }
        public string PM_KIMLIKNO { get; set; }
        public string PM_AD2 { get; set; }
        public string PM_YENIMOD { get; set; }
        public string PM_TAKASDVZ { get; set; }
        public string NEREDEN { get; set; }
        public Nullable<int> PM_MERID { get; set; }
        public string PM_KULLKISI { get; set; }
        public Nullable<short> PM_KACNMARKA { get; set; }
        public Nullable<short> PM_KACNBUMAR { get; set; }
        public string PM_ONCBAYI { get; set; }
        public Nullable<System.DateTime> PM_DTAR { get; set; }
        public string PM_DYER { get; set; }
        public string PM_MEDDUR { get; set; }
        public Nullable<System.DateTime> PM_EVLITAR { get; set; }
        public string PM_CCKAD1 { get; set; }
        public Nullable<System.DateTime> PM_CCKDT1 { get; set; }
        public string PM_CCKAD2 { get; set; }
        public Nullable<System.DateTime> PM_CCKDT2 { get; set; }
        public string PM_CCKAD3 { get; set; }
        public Nullable<System.DateTime> PM_CCKDT3 { get; set; }
        public string PM_ESAD { get; set; }
        public string PM_SIRTEL { get; set; }
        public string PM_SIRFAX { get; set; }
        public string PM_SEKTOR { get; set; }
        public string PM_FAALCINS { get; set; }
        public Nullable<short> PM_SIRPARK { get; set; }
        public string PM_OGRENIM { get; set; }
        public string PM_ISDURUM { get; set; }
        public string PM_UNVAN { get; set; }
        public string PM_SIRADR { get; set; }
        public string PM_SIRPK { get; set; }
        public string PM_SIRILCE { get; set; }
        public string PM_SIRIL { get; set; }
        public string PM_SIRARAC { get; set; }
        public string PM_SIRKET { get; set; }
        public string PM_MODEL3 { get; set; }
        public string PM_MODEL4 { get; set; }
        public Nullable<short> PM_TERCNED1 { get; set; }
        public Nullable<short> PM_TERCNED2 { get; set; }
        public Nullable<short> PM_TERCNED3 { get; set; }
        public string PM_TERDIGER { get; set; }
        public Nullable<short> PM_TVKANAL1 { get; set; }
        public Nullable<short> PM_TVKANAL2 { get; set; }
        public Nullable<short> PM_TVKANAL3 { get; set; }
        public Nullable<short> PM_GAZETE1 { get; set; }
        public Nullable<short> PM_GAZETE2 { get; set; }
        public Nullable<short> PM_GAZETE3 { get; set; }
        public Nullable<short> PM_DERGI1 { get; set; }
        public Nullable<short> PM_DERGI2 { get; set; }
        public Nullable<short> PM_DERGI3 { get; set; }
        public string PM_TKSMTR { get; set; }
        public string PM_IRTIBATKISI { get; set; }
        public Nullable<short> PM_PARKOZ1 { get; set; }
        public Nullable<short> PM_PARKOZ2 { get; set; }
        public Nullable<short> PM_PARKOZ3 { get; set; }
        public Nullable<short> PM_PARKOZ4 { get; set; }
        public Nullable<short> PM_PARKOZ5 { get; set; }
        public Nullable<short> PM_PARKIRA1 { get; set; }
        public Nullable<short> PM_PARKIRA2 { get; set; }
        public Nullable<short> PM_PARKIRA3 { get; set; }
        public Nullable<short> PM_PARKIRA4 { get; set; }
        public Nullable<short> PM_PARKIRA5 { get; set; }
        public Nullable<short> PM_KAYIP1 { get; set; }
        public Nullable<short> PM_KAYIP2 { get; set; }
        public Nullable<short> PM_KAYIP3 { get; set; }
        public Nullable<short> PM_KAYIP4 { get; set; }
        public Nullable<short> PM_KAYIP5 { get; set; }
        public string PM_KAYIPNOT1 { get; set; }
        public string PM_KAYIPNOT2 { get; set; }
        public string PM_KAYIPNOT3 { get; set; }
        public string PM_KAYIPNOT4 { get; set; }
        public string PM_KAYIPNOT5 { get; set; }
        public string PM_KAYIPDIGER { get; set; }
        public Nullable<System.DateTime> PM_KAYITTRH { get; set; }
        public string PM_KAYITUSR { get; set; }
        public Nullable<System.DateTime> PM_DEGISTRH { get; set; }
        public string PM_DEGISUSR { get; set; }
        public Nullable<int> PM_RAKIP { get; set; }
        public Nullable<double> PM_MRID { get; set; }
        public string PM_ARACDEG { get; set; }
        public string PM_TAVMUS_AD { get; set; }
        public string PM_TAVMUS_SOYAD { get; set; }
        public string PM_TAVMUS_TEL { get; set; }
        public Nullable<System.DateTime> PM_TESTSURUS_TRH { get; set; }
        public string PM_TESTSURUS { get; set; }
        public string PM_TAVMUS { get; set; }
        public string PM_HOBILER { get; set; }
        public string PM_IRTIBAT_DIGER { get; set; }
        public string PM_NOT { get; set; }
    }
}
