//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIMFATD
    {
        public double SATIS_NO { get; set; }
        public short SIRA_NO { get; set; }
        public string KOM_TIP { get; set; }
        public Nullable<double> ARC_SATNO { get; set; }
        public Nullable<System.DateTime> ARC_SATRH { get; set; }
        public string ARC_SATCARI { get; set; }
        public string SASE_NO { get; set; }
        public string MODEL_KOD { get; set; }
        public string MODEL { get; set; }
        public string ONAY_KOD { get; set; }
        public Nullable<System.DateTime> ONAY_TRH { get; set; }
        public Nullable<double> KDV { get; set; }
        public Nullable<double> TUTAR { get; set; }
        public string HIZMET_KODU { get; set; }
        public string HIZMET_ADI { get; set; }
        public Nullable<double> ISKONTO { get; set; }
        public Nullable<double> MIKTAR { get; set; }
        public Nullable<double> GER_TUT { get; set; }
        public string PRIM_TIP { get; set; }
        public Nullable<byte> STATU { get; set; }
    }
}
