//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIMFAT
    {
        public double SATIS_NO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string PER_KOD { get; set; }
        public string TIP { get; set; }
        public string CARIKOD { get; set; }
        public Nullable<double> BRUTTUT { get; set; }
        public Nullable<double> YUZDE { get; set; }
        public Nullable<double> INDIRIM { get; set; }
        public Nullable<double> ARATOPLAM { get; set; }
        public Nullable<double> KDV { get; set; }
        public Nullable<double> KDVTUT { get; set; }
        public Nullable<double> NETTUT { get; set; }
        public Nullable<System.DateTime> FATARIH { get; set; }
        public Nullable<System.DateTime> SAAT { get; set; }
        public Nullable<System.DateTime> VADETRH { get; set; }
        public string FATNO { get; set; }
        public Nullable<System.DateTime> IRSTARIH { get; set; }
        public string IRS_NO { get; set; }
        public Nullable<System.DateTime> ONAYTARIH { get; set; }
        public string ONAY_NO { get; set; }
        public Nullable<double> FIS_NO { get; set; }
        public Nullable<byte> ENT_KOD { get; set; }
        public Nullable<byte> STATU { get; set; }
        public string EK1 { get; set; }
        public string EK2 { get; set; }
        public string EK3 { get; set; }
        public string ODE_KOD { get; set; }
        public Nullable<byte> ONAY_STATU { get; set; }
        public string KDVTEV { get; set; }
        public Nullable<double> KDVTEV_TUT { get; set; }
        public Nullable<short> ONAY_KISI { get; set; }
        public string PRIM_TIP { get; set; }
    }
}
