//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class QFORMU
    {
        public string SASI_NO { get; set; }
        public System.DateTime TARIH { get; set; }
        public string MOTOR_NO { get; set; }
        public Nullable<double> KM { get; set; }
        public string MARKA { get; set; }
        public string MODEL { get; set; }
        public string ARAC_TIP { get; set; }
        public Nullable<System.DateTime> TRAFIK_CIK_TRH { get; set; }
        public string ARIZALIPRCNO { get; set; }
        public string ARIZALI_PRC_IM_NO { get; set; }
        public string ISLEMKODU { get; set; }
        public string HASAR_KODU { get; set; }
        public string PRCKIRMI { get; set; }
        public string QRAPNO { get; set; }
        public string CARI_KOD { get; set; }
        public string HASARPRCAD { get; set; }
        public string MUSIKAYET { get; set; }
        public string SRVTESHIS { get; set; }
        public string PERSON_KOD { get; set; }
    }
}
