//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class RANDET
    {
        public double RAN_NO { get; set; }
        public double SIRA_NO { get; set; }
        public string TALIMAT { get; set; }
        public Nullable<double> SURE { get; set; }
        public string PER_KOD { get; set; }
    }
}
