//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class RANMAST
    {
        public double RAN_NO { get; set; }
        public Nullable<short> SIRA_NO { get; set; }
        public string CARI_KOD { get; set; }
        public string CARI_AD { get; set; }
        public string PLAKA { get; set; }
        public string SASE { get; set; }
        public string TELEFON { get; set; }
        public Nullable<System.DateTime> KYT_TARIH { get; set; }
        public Nullable<System.DateTime> RAN_TARIH { get; set; }
        public Nullable<System.DateTime> RAN_SAAT { get; set; }
        public Nullable<double> TOPLAM_SURE { get; set; }
        public string GELDI { get; set; }
        public string ACIKLAMA { get; set; }
        public string MODEL_KOD { get; set; }
        public Nullable<short> MODEL_YIL { get; set; }
        public string ISLEM_TIP { get; set; }
        public string ONAYLAYAN { get; set; }
        public string ONAY_DURUM { get; set; }
        public Nullable<System.DateTime> ONAY_TARIH { get; set; }
        public string PERSON_KOD { get; set; }
    }
}
