//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class RANPLAN
    {
        public double RAN_NO { get; set; }
        public System.DateTime BAS_TRH { get; set; }
        public string STALL { get; set; }
        public Nullable<System.DateTime> BIT_TRH { get; set; }
        public Nullable<System.DateTime> SURE_SA { get; set; }
        public string ATELYE { get; set; }
        public string PER_KOD { get; set; }
        public string ACIKLAMA { get; set; }
        public string DURUM { get; set; }
    }
}
