//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class rb_item
    {
        public int item_id { get; set; }
        public Nullable<int> folder_id { get; set; }
        public string item_name { get; set; }
        public Nullable<int> item_size { get; set; }
        public Nullable<int> item_type { get; set; }
        public Nullable<double> modified { get; set; }
        public Nullable<double> deleted { get; set; }
        public byte[] template { get; set; }
    }
}
