//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESMITAT
    {
        public System.DateTime TARIH { get; set; }
        public string RESMITATILAD { get; set; }
        public string YARIMGUN { get; set; }
        public string CAY { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string CUSER { get; set; }
    }
}
