//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIGHTS
    {
        public string LOGIN_NAME { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PASS { get; set; }
        public string SUPERVIZOR { get; set; }
        public string BEYAN { get; set; }
        public string ALIS { get; set; }
        public string SATIS { get; set; }
        public string AL_SIP { get; set; }
        public string VER_SIP { get; set; }
        public string IS_EMRI { get; set; }
        public string DISPOZ { get; set; }
        public string ARAC_AL { get; set; }
        public string ARAC_SAT { get; set; }
        public string STOK { get; set; }
        public string CARI { get; set; }
        public string MALIYET { get; set; }
        public string CLAIM { get; set; }
        public string PDI { get; set; }
        public string SER_STOK { get; set; }
        public string SEPO_STOK { get; set; }
        public string EXPER { get; set; }
        public string PERSONEL { get; set; }
        public string BARKOD { get; set; }
        public string FRTFCT { get; set; }
        public string DIALUP { get; set; }
        public string PARAM { get; set; }
        public string FAT_TANIM { get; set; }
        public string DOVIZ_KUR { get; set; }
        public string IE_AKTAR { get; set; }
        public string DIGER01 { get; set; }
        public string DIGER02 { get; set; }
        public string DIGER03 { get; set; }
        public string DIGER04 { get; set; }
        public string DIGER05 { get; set; }
        public string DIGER06 { get; set; }
        public string DIGER07 { get; set; }
        public string DIGER08 { get; set; }
        public string DIGER09 { get; set; }
        public string DIGER10 { get; set; }
        public string PERSONEL_KOD { get; set; }
        public string DIGER11 { get; set; }
        public string DIGER12 { get; set; }
        public string DIGER13 { get; set; }
        public string DIGER14 { get; set; }
        public string DIGER15 { get; set; }
        public string DIGER16 { get; set; }
        public string DIGER17 { get; set; }
        public string DIGER18 { get; set; }
        public string DIGER19 { get; set; }
        public string DIGER20 { get; set; }
        public string DIGER21 { get; set; }
        public string DIGER22 { get; set; }
        public string DIGER23 { get; set; }
        public string DIGER24 { get; set; }
        public string DIGER25 { get; set; }
        public bool DEPTRANS { get; set; }
        public string DIGER26 { get; set; }
        public string DEPO { get; set; }
        public string CHRK { get; set; }
        public string CRISK { get; set; }
        public string CARIBA { get; set; }
        public string CHODEKAPAC { get; set; }
        public string CHIZLE { get; set; }
        public string IKI_ZARAR_SAT { get; set; }
        public string IKI_EL_CARIHRK { get; set; }
        public string IKI_ELSATIS_ONAY { get; set; }
        public string IKI_CARIONAY { get; set; }
        public string ARAC_BEYAN_SIL { get; set; }
        public string IKI_EL_OKU { get; set; }
        public string IKI_EL_EKLE { get; set; }
        public string IKI_EL_DEGIS { get; set; }
        public string IKI_EL_SIL { get; set; }
        public string IE_ACKAPA { get; set; }
        public string ARC_GECMISSRG { get; set; }
        public string IEFATURA { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_USER { get; set; }
        public Nullable<double> MAX_ISK_PRC { get; set; }
        public Nullable<double> MAX_ISK_ISC { get; set; }
        public string TEKLIF { get; set; }
        public Nullable<int> STOK_ADI { get; set; }
        public Nullable<int> FRT_ADI { get; set; }
        public Nullable<int> STOK_FIYAT { get; set; }
        public Nullable<int> FRT_FIYAT { get; set; }
        public Nullable<int> YETKI_GRUP { get; set; }
        public string PASIF { get; set; }
        public string DIGER27 { get; set; }
        public string DIGER28 { get; set; }
    }
}
