//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATIS
    {
        public double SATIS_NO { get; set; }
        public string CARIKOD { get; set; }
        public Nullable<double> BRUTTUT { get; set; }
        public string TIP { get; set; }
        public Nullable<double> INDIRIM { get; set; }
        public Nullable<double> YUZDE { get; set; }
        public Nullable<double> INR_YUZD { get; set; }
        public Nullable<double> MASRAF { get; set; }
        public Nullable<double> KDVTUT { get; set; }
        public Nullable<double> NETTUT { get; set; }
        public Nullable<System.DateTime> FATARIH { get; set; }
        public Nullable<System.DateTime> SAAT { get; set; }
        public Nullable<System.DateTime> VADETRH { get; set; }
        public string FATIRSNO { get; set; }
        public Nullable<double> USD_KUR { get; set; }
        public Nullable<double> USD_TUTAR { get; set; }
        public string ODEME_SEKLI { get; set; }
        public Nullable<double> FIS_NO { get; set; }
        public string ODE_KOD { get; set; }
        public Nullable<System.DateTime> IRSTARIH { get; set; }
        public string IRS_NO { get; set; }
        public Nullable<double> TEKLIF_NO { get; set; }
        public Nullable<double> GER_TUT_DVZ { get; set; }
        public Nullable<byte> STATU { get; set; }
        public string KDVTEV { get; set; }
        public Nullable<double> KDVTEV_TUT { get; set; }
        public Nullable<byte> ENT_KOD { get; set; }
        public string EK1 { get; set; }
        public string EK2 { get; set; }
        public string EK3 { get; set; }
        public byte AKTARILDI { get; set; }
        public string DOVIZ_KODU { get; set; }
        public Nullable<double> TL_KURDEGER { get; set; }
        public Nullable<double> NETTUT_DVZ { get; set; }
        public Nullable<double> BRUTTUT_DVZ { get; set; }
        public Nullable<double> INR_YUZD_DVZ { get; set; }
        public Nullable<double> KDVTUT_DVZ { get; set; }
        public Nullable<double> KDVTEV_TUT_DVZ { get; set; }
        public string PER_KOD { get; set; }
        public string ODE_TIP { get; set; }
        public Nullable<double> TOP_ISK { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_USER { get; set; }
        public string ACIKLAMA { get; set; }
        public string SEVK_CARI { get; set; }
        public Nullable<byte> EF_STATU { get; set; }
        public string EF_GUID { get; set; }
        public string EF_POSTAKUTUSU { get; set; }
        public string EF_ORDERREFNO { get; set; }
        public string EF_MAGAZANO { get; set; }
        public string EF_TEDARIKNO { get; set; }
        public string EF_SIPARISNO { get; set; }
        public string ISTISNA_CODE { get; set; }
        public string TEVKIFAT_CODE { get; set; }
        public Nullable<byte> EXCEL_AKTAR { get; set; }
        public Nullable<System.DateTime> SEVK_TARIH { get; set; }
        public string SASE_NO { get; set; }
        public Nullable<short> SUBEKODU { get; set; }
        public Nullable<short> SUBEKODU2 { get; set; }
        public string MODEL_KOD { get; set; }
        public string PLAKA_NO { get; set; }
    }
}
