//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERRAP
    {
        public short YIL { get; set; }
        public short AY { get; set; }
        public Nullable<short> IE_MEK_ATL { get; set; }
        public Nullable<short> IE_KB_ATL { get; set; }
        public Nullable<short> IE_TPL { get; set; }
        public Nullable<short> IE_TIP_1 { get; set; }
        public Nullable<short> IE_TIP_2 { get; set; }
        public Nullable<short> IE_TIP_3 { get; set; }
        public Nullable<short> IE_TIP_4 { get; set; }
        public Nullable<short> IE_TIP_5 { get; set; }
        public Nullable<short> IE_TIP_6 { get; set; }
        public Nullable<short> IE_TIP_7 { get; set; }
        public Nullable<short> IE_TIP_8 { get; set; }
        public Nullable<double> IG_MEK_ATL { get; set; }
        public Nullable<double> IG_KB_ATL { get; set; }
        public Nullable<double> IG_GAR { get; set; }
        public Nullable<double> IG_DIGER { get; set; }
        public Nullable<double> IG_TPL { get; set; }
        public Nullable<double> PG_MEK_ATL { get; set; }
        public Nullable<double> PG_KB_ATL { get; set; }
        public Nullable<double> PG_YAG { get; set; }
        public Nullable<double> PG_GAR { get; set; }
        public Nullable<double> PG_DIGER { get; set; }
        public Nullable<double> PG_TPL { get; set; }
        public string YP_PER_KOD { get; set; }
        public Nullable<double> PA_ACIL { get; set; }
        public Nullable<double> PA_STOK { get; set; }
        public Nullable<double> PA_DIGER { get; set; }
        public Nullable<double> PA_TPL { get; set; }
        public Nullable<double> PS_IE { get; set; }
        public Nullable<double> PS_GAR { get; set; }
        public Nullable<double> PS_BANKO { get; set; }
        public Nullable<double> PS_IE_FAT { get; set; }
        public Nullable<double> PS_GAR_FAT { get; set; }
        public Nullable<double> PS_TPL { get; set; }
        public Nullable<double> PS_TPL_2 { get; set; }
        public Nullable<int> YP_STK_KALEM { get; set; }
        public Nullable<int> YP_HRK_KALEM { get; set; }
        public Nullable<double> YP_STK_ADET { get; set; }
        public Nullable<double> STK_TUT { get; set; }
        public Nullable<double> STK_MLYT { get; set; }
        public Nullable<double> ORT_STK_MIK { get; set; }
        public Nullable<double> STK_DEVIR { get; set; }
        public Nullable<double> BUL_STK_SIP { get; set; }
        public Nullable<double> BUL_ACL_SIP { get; set; }
        public Nullable<double> BUL_ORAN { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<double> YD_F1 { get; set; }
        public Nullable<double> YD_F2 { get; set; }
        public Nullable<double> YD_F3 { get; set; }
        public Nullable<int> YD_I1 { get; set; }
        public Nullable<int> YD_I2 { get; set; }
        public Nullable<int> YD_I3 { get; set; }
        public string YD_C1 { get; set; }
        public string YD_C2 { get; set; }
        public string YD_C3 { get; set; }
        public string YD_S1 { get; set; }
        public string YD_S2 { get; set; }
        public string YD_S3 { get; set; }
        public Nullable<double> GENEL_01 { get; set; }
        public Nullable<double> GENEL_02 { get; set; }
        public Nullable<double> GENEL_03 { get; set; }
        public Nullable<double> GENEL_04 { get; set; }
        public Nullable<double> GENEL_05 { get; set; }
    }
}
