//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGORTAS
    {
        public string SIR_KOD { get; set; }
        public string SIR_ADI { get; set; }
        public string SIR_CARIKOD { get; set; }
    }
}
