//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPKALEM
    {
        public short YIL { get; set; }
        public short AY { get; set; }
        public short HAFTA { get; set; }
        public Nullable<short> SIPTAV { get; set; }
        public Nullable<short> SIPSTK { get; set; }
    }
}
