//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPODE
    {
        public string SIPODE_KOD { get; set; }
        public string SIPODE_AD { get; set; }
        public Nullable<double> SIPODE_ISK1 { get; set; }
        public Nullable<double> SIPODE_ISK2 { get; set; }
        public Nullable<double> SIPODE_ISK3 { get; set; }
    }
}
