//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIRKETLER
    {
        public short SIRKETNO { get; set; }
        public string SIRKETAD { get; set; }
        public string SIRKETUNVAN { get; set; }
    }
}
