//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class SORULAR
    {
        public short SORU_ID { get; set; }
        public string SORU_TXT { get; set; }
        public Nullable<byte> SORU_GRP { get; set; }
        public Nullable<byte> SORU_TIP { get; set; }
    }
}
