//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRTELRAP
    {
        public int RAP_NO { get; set; }
        public string CARI_KOD { get; set; }
        public string CARI_AD { get; set; }
        public string TELEFON { get; set; }
        public string SASE_NO { get; set; }
        public string PLAKA_NO { get; set; }
        public string MODEL_KOD { get; set; }
        public Nullable<short> MODEL_YIL { get; set; }
        public string ISEMRI_NO { get; set; }
        public Nullable<System.DateTime> GELIS_TRH { get; set; }
        public Nullable<System.DateTime> ARAMA_TRH { get; set; }
        public string PER_KOD { get; set; }
        public string SER_1 { get; set; }
        public string SER_2 { get; set; }
        public string SER_3 { get; set; }
        public string SER_4 { get; set; }
        public string SER_5 { get; set; }
        public string SER_6 { get; set; }
        public string SER_7 { get; set; }
        public string SER_8 { get; set; }
        public string SER_9 { get; set; }
        public string GNL_1 { get; set; }
        public string GNL_2 { get; set; }
        public string GNL_3 { get; set; }
        public string GNL_4 { get; set; }
        public string GNL_5 { get; set; }
        public string GNL_6 { get; set; }
        public string GNL_7 { get; set; }
        public string GNL_8 { get; set; }
        public string GNL_9 { get; set; }
        public string PRC_1 { get; set; }
        public string PRC_2 { get; set; }
        public string PRC_3 { get; set; }
        public string PRC_4 { get; set; }
        public string PRC_5 { get; set; }
        public string PRC_6 { get; set; }
        public string PRC_7 { get; set; }
        public string PRC_8 { get; set; }
        public string PRC_9 { get; set; }
        public string ARC_1 { get; set; }
        public string ARC_2 { get; set; }
        public string ARC_3 { get; set; }
        public string ARC_4 { get; set; }
        public string ARC_5 { get; set; }
        public string ARC_6 { get; set; }
        public string ARC_7 { get; set; }
        public string ARC_8 { get; set; }
        public string ARC_9 { get; set; }
        public string ARC_10 { get; set; }
        public string ARC_11 { get; set; }
        public string ARC_12 { get; set; }
        public string ARC_13 { get; set; }
        public string ARC_14 { get; set; }
        public string ARC_15 { get; set; }
        public string ARC_16 { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<double> YDK_F1 { get; set; }
        public Nullable<double> YDK_F2 { get; set; }
        public bool AKTARILDI { get; set; }
        public Nullable<int> ANKET_ID { get; set; }
        public string GSM { get; set; }
    }
}
