//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRTELCEVAP
    {
        public int RAP_NO { get; set; }
        public short SORU_NO { get; set; }
        public Nullable<int> ANK_ID { get; set; }
        public short SORU_ID { get; set; }
        public Nullable<short> CEVAP_ID { get; set; }
        public string CEVAP_TXT { get; set; }
    }
}
