//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class STKAYMAL
    {
        public short YIL { get; set; }
        public short AY { get; set; }
        public double STOK_NO { get; set; }
        public string STOK_KOD { get; set; }
        public Nullable<double> MIKTAR { get; set; }
        public Nullable<double> MALIYET { get; set; }
        public string TIP { get; set; }
        public Nullable<double> DB_MIK { get; set; }
        public Nullable<double> DB_TUT { get; set; }
        public Nullable<double> GIR_MIK { get; set; }
        public Nullable<double> GIR_TUT { get; set; }
        public Nullable<double> CIK_MIK { get; set; }
        public Nullable<double> CIK_TUT { get; set; }
        public Nullable<double> DBD_KATS { get; set; }
        public Nullable<double> SAT_MAL { get; set; }
        public string DEPO_KODU { get; set; }
    }
}
