//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOKMIK
    {
        public double STOK_NO { get; set; }
        public string DEPO_KOD { get; set; }
        public Nullable<double> MIKTAR { get; set; }
        public Nullable<double> SAYIM_MIK { get; set; }
        public Nullable<double> SAYIM_FIILI { get; set; }
        public string RAF_YERI { get; set; }
        public Nullable<System.DateTime> UPDATE_TRH { get; set; }
    }
}
