//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class STTELRAP
    {
        public int RAP_NO { get; set; }
        public System.DateTime TARIH { get; set; }
        public string PER_KOD { get; set; }
        public Nullable<double> SATIS_NO { get; set; }
        public Nullable<System.DateTime> SATIS_TRH { get; set; }
        public string CARI_KOD { get; set; }
        public string CARI_AD { get; set; }
        public string TELEFON { get; set; }
        public string SASE_NO { get; set; }
        public string PLAKA_NO { get; set; }
        public string MODEL_KOD { get; set; }
        public Nullable<int> MODEL_YIL { get; set; }
        public Nullable<double> KM { get; set; }
        public string GORUSME_1 { get; set; }
        public string GORUSME_2 { get; set; }
        public string GORUSME_3 { get; set; }
        public string GORUSME_4 { get; set; }
        public string GORUSME_5 { get; set; }
        public string GORUSME_6 { get; set; }
        public string NEDEN_1 { get; set; }
        public string NEDEN_2 { get; set; }
        public string NEDEN_3 { get; set; }
        public string NEDEN_4 { get; set; }
        public string NEDEN_5 { get; set; }
        public string NEDEN_6 { get; set; }
        public string NEDEN_7 { get; set; }
        public string NEDEN_8 { get; set; }
        public string NEDEN_9 { get; set; }
        public string NEDEN_10 { get; set; }
        public string SORU_1 { get; set; }
        public string SORU_2 { get; set; }
        public string SORU_3 { get; set; }
        public string SORU_4 { get; set; }
        public string SORU_5 { get; set; }
        public string SORU_6 { get; set; }
        public string SORU_7 { get; set; }
        public string SORU_8 { get; set; }
        public string SORU_9 { get; set; }
        public string SORU_10 { get; set; }
        public string SORU_11 { get; set; }
        public string SORU_12 { get; set; }
        public string SORU_13 { get; set; }
        public string SORU_14 { get; set; }
        public string SORU_15 { get; set; }
        public string SORU_16 { get; set; }
        public string SORU_17 { get; set; }
        public string SORU_18 { get; set; }
        public string SORU_19 { get; set; }
        public string SORU_20 { get; set; }
        public string ACIKLAMA { get; set; }
        public bool AKTARILDI { get; set; }
        public Nullable<int> ANKET_ID { get; set; }
        public string SORU_21 { get; set; }
        public string ASONUC { get; set; }
    }
}
