//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBELER
    {
        public short SUBE_NO { get; set; }
        public string SUBE_ADI { get; set; }
        public string ALIASADI { get; set; }
        public string MERKEZMI { get; set; }
        public Nullable<short> MAL_ALACAGI_DEPO_KODU { get; set; }
        public Nullable<short> SERVIS_DEPO_KODU { get; set; }
        public string BAYI_KOD { get; set; }
        public Nullable<short> URETIME_CIKIS_DEPO { get; set; }
        public Nullable<short> URETIM_ATOLYE_DEPO { get; set; }
        public Nullable<byte> GAR_ISCISK_TIP { get; set; }
        public Nullable<double> CLAIM_ISC_ISK { get; set; }
        public Nullable<double> CLAIM_BR_FYT { get; set; }
        public string CLAIM_FYT_DVZ { get; set; }
        public Nullable<short> SIRKETNO { get; set; }
        public Nullable<double> KAR_MARJI { get; set; }
        public Nullable<double> SUBEKATSAY { get; set; }
        public Nullable<byte> SIPALYETKI { get; set; }
        public string DEFKASA { get; set; }
        public string DEFPOS { get; set; }
        public string POSTASUNUCUSU { get; set; }
        public string EMAIL { get; set; }
        public string HESAPADI { get; set; }
        public string HSPAROLA { get; set; }
        public Nullable<int> NETPORT { get; set; }
        public string CARIKOD { get; set; }
    }
}
