//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class TALEPFORM
    {
        public int FORM_NO { get; set; }
        public Nullable<short> TALEP_TIP { get; set; }
        public Nullable<short> TALEP_ALTTIP { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string CARI_KOD { get; set; }
        public Nullable<short> SUBEKODU { get; set; }
        public string PERSONEL_ID { get; set; }
        public string SASE_NO { get; set; }
        public string PLAKA { get; set; }
        public Nullable<System.DateTime> TARIH_BAS { get; set; }
        public Nullable<System.DateTime> TARIH_BIT { get; set; }
        public Nullable<decimal> KM_BAS { get; set; }
        public Nullable<decimal> KM_BIT { get; set; }
        public Nullable<decimal> TALEP_KM { get; set; }
        public Nullable<decimal> TALEP_LT { get; set; }
        public Nullable<decimal> TALEP_TUTAR { get; set; }
        public Nullable<decimal> YAKIT_MIK { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public string GIDIS_YERI { get; set; }
        public string ACIKLAMA1 { get; set; }
        public string ACIKLAMA2 { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string ONAY_PER1 { get; set; }
        public Nullable<byte> ONAY1 { get; set; }
        public Nullable<System.DateTime> ONAY_TRH1 { get; set; }
        public string ONAY_PER2 { get; set; }
        public Nullable<byte> ONAY2 { get; set; }
        public Nullable<System.DateTime> ONAY_TRH2 { get; set; }
        public string ONAY_PER3 { get; set; }
        public Nullable<byte> ONAY3 { get; set; }
        public Nullable<System.DateTime> ONAY_TRH3 { get; set; }
        public string ONAY_PER4 { get; set; }
        public Nullable<byte> ONAY4 { get; set; }
        public Nullable<System.DateTime> ONAY_TRH4 { get; set; }
        public string ONAY_PER5 { get; set; }
        public Nullable<byte> ONAY5 { get; set; }
        public Nullable<System.DateTime> ONAY_TRH5 { get; set; }
    }
}
