//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARIZPAR
    {
        public int SNO { get; set; }
        public string IZP_ARAC_TIPI { get; set; }
        public string IZP_KODU { get; set; }
        public string IZP_GRUP { get; set; }
        public string IZP_MALZEME { get; set; }
        public Nullable<double> YP_MIKTAR { get; set; }
    }
}
