//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAVERGI
    {
        public string TARIFE_KOD { get; set; }
        public short MODEL_YIL { get; set; }
        public string TARIFE_AD { get; set; }
        public Nullable<double> TAV { get; set; }
        public Nullable<double> EKTAV { get; set; }
        public Nullable<double> EKP { get; set; }
        public Nullable<double> CKF { get; set; }
        public Nullable<double> SIGORTA { get; set; }
        public Nullable<double> BANDROL { get; set; }
        public Nullable<double> TESCIL { get; set; }
        public Nullable<double> KDV { get; set; }
        public Nullable<double> DIGER1 { get; set; }
        public Nullable<double> DIGER2 { get; set; }
    }
}
