//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEKISCI
    {
        public double TEKNO { get; set; }
        public string FRT_KODU { get; set; }
        public string FRT_ADI { get; set; }
        public Nullable<double> FRT_ZAMAN { get; set; }
        public Nullable<double> ISKONTO { get; set; }
        public Nullable<double> BRMFYT { get; set; }
        public Nullable<double> KDV { get; set; }
        public Nullable<double> ISK_TUT { get; set; }
    }
}
