//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEKLIF
    {
        public double TEKNO { get; set; }
        public string CARI_KODU { get; set; }
        public Nullable<System.DateTime> TEKLIFTRH { get; set; }
        public string SASE_NO { get; set; }
        public string PLAKA_NO { get; set; }
        public string MOTOR_NO { get; set; }
        public string MODEL { get; set; }
        public Nullable<double> ISCILIK_TUT { get; set; }
        public Nullable<double> PARCA_TUT { get; set; }
        public Nullable<double> BRUT { get; set; }
        public Nullable<double> KDVTUT { get; set; }
        public Nullable<double> NETTUT { get; set; }
        public Nullable<double> YUZDE { get; set; }
        public Nullable<double> INDIRIM { get; set; }
        public string ACIKLAMA { get; set; }
        public string ACIKLAMA1 { get; set; }
        public string ACIKLAMA2 { get; set; }
        public string IE_TIP { get; set; }
        public Nullable<byte> STATU { get; set; }
        public string PER_KOD { get; set; }
        public string DURUM { get; set; }
        public Nullable<double> KM { get; set; }
        public Nullable<System.DateTime> GECERTRH { get; set; }
        public string KDVTEV { get; set; }
        public Nullable<double> KDVTEV_TUT { get; set; }
    }
}
