//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEKLIFM
    {
        public decimal TEK_NO { get; set; }
        public Nullable<System.DateTime> TEK_TRH { get; set; }
        public string TEK_ACIK { get; set; }
        public string TEK_CARIKOD { get; set; }
        public string TEK_CARIAD { get; set; }
        public string TEK_CARISAD { get; set; }
        public string TEK_TELEFON { get; set; }
        public string TEK_GSM { get; set; }
        public string TEK_SASI { get; set; }
        public string TEK_PLAKA { get; set; }
        public string TEK_MODEL { get; set; }
        public string TEK_TIP { get; set; }
        public string TEK_NOT { get; set; }
        public Nullable<double> TEK_BRUT { get; set; }
        public Nullable<double> TEK_ISKYUZ { get; set; }
        public Nullable<double> TEK_ISKTUT { get; set; }
        public Nullable<double> TEK_ARATOP { get; set; }
        public Nullable<double> TEK_KDVTUT { get; set; }
        public Nullable<double> TEK_NETTUT { get; set; }
    }
}
