//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEKLIFD
    {
        public decimal TEKD_TEKNO { get; set; }
        public int TEKD_SIRA { get; set; }
        public string TEKD_PI { get; set; }
        public string TEKD_GARANTI { get; set; }
        public string TEKD_PIKOD { get; set; }
        public string TEKD_PIAD { get; set; }
        public Nullable<double> TEKD_MIKTAR { get; set; }
        public Nullable<double> TEKD_KDV { get; set; }
        public Nullable<double> TEKD_ISK { get; set; }
        public Nullable<double> TEKD_NETTUT { get; set; }
        public Nullable<double> TEKD_KDVTUT { get; set; }
    }
}
