//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEKPARCA
    {
        public double TEKNO { get; set; }
        public string STOK_KOD_NO { get; set; }
        public string STOK_ADI_TR { get; set; }
        public string BIRIMI { get; set; }
        public Nullable<double> MIKTAR { get; set; }
        public Nullable<double> KDV { get; set; }
        public Nullable<double> ISKONTO { get; set; }
        public Nullable<double> BRFYT { get; set; }
        public Nullable<double> FYT_DOVIZ { get; set; }
        public string DOVIZ_KODU { get; set; }
        public Nullable<double> TL_KURDEGER { get; set; }
        public Nullable<double> ISK_TUT { get; set; }
        public double STOK_NO { get; set; }
    }
}
