//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESTSRS
    {
        public int TEST_NO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string PER_KOD { get; set; }
        public string TEST_SASE { get; set; }
        public string TEST_PLAKA { get; set; }
        public string TEST_MARKA { get; set; }
        public string TEST_MODEL { get; set; }
        public string TEST_TIP { get; set; }
        public Nullable<double> TEST_MESAFE { get; set; }
        public Nullable<double> TEST_SURE { get; set; }
        public Nullable<double> MUS_PMNO { get; set; }
        public string DEGER1 { get; set; }
        public string DEGER2 { get; set; }
        public string DEGER3 { get; set; }
        public string DEGER4 { get; set; }
        public string DEGER5 { get; set; }
        public string DEGER6 { get; set; }
        public string DEGER7 { get; set; }
        public string DEGER8 { get; set; }
        public string DEGER9 { get; set; }
        public string KIYAS1 { get; set; }
        public string KIYAS2 { get; set; }
        public string KIYAS3 { get; set; }
        public string KIYAS4 { get; set; }
        public string KIYAS5 { get; set; }
        public string KIYAS6 { get; set; }
        public string KIYAS7 { get; set; }
        public string KIYAS8 { get; set; }
        public string KIYAS9 { get; set; }
        public string ACIKLAMA { get; set; }
        public bool AKTARILDI { get; set; }
        public Nullable<bool> IKINCIEL { get; set; }
        public string DEGER10 { get; set; }
        public string DEGER11 { get; set; }
        public string DEGER12 { get; set; }
        public string DEGER13 { get; set; }
        public string DEGER14 { get; set; }
        public string DEGER15 { get; set; }
        public string YORUM1 { get; set; }
        public string YORUM2 { get; set; }
        public string YORUM3 { get; set; }
        public string BILGI1 { get; set; }
    }
}
