//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class VARDIYA
    {
        public double ISYERINO { get; set; }
        public string YURURLUK { get; set; }
        public string VAR_KODU { get; set; }
        public string VAR_ADI { get; set; }
        public Nullable<System.DateTime> VAR_BAS_ST { get; set; }
        public Nullable<System.DateTime> VAR_BIT_ST { get; set; }
        public Nullable<double> VAR_UCRETI { get; set; }
        public Nullable<double> VAR_ORN { get; set; }
        public Nullable<double> VAR_DEG_ZAMANI { get; set; }
    }
}
