//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class VERSIPMA
    {
        public double SIPARIS_NO { get; set; }
        public string SIP_NO_MAL { get; set; }
        public Nullable<System.DateTime> SIPARIS_TRH { get; set; }
        public string SIPARIS_TURU { get; set; }
        public string CARI_KODU { get; set; }
        public string CARI_ADI { get; set; }
        public Nullable<double> TOPLAM_TUTAR { get; set; }
        public Nullable<double> KDV_TUTAR { get; set; }
        public Nullable<double> GENEL_TOPLAM { get; set; }
        public bool AKTARILDI { get; set; }
        public Nullable<double> ISKONTO { get; set; }
        public Nullable<double> ISK_TUTAR { get; set; }
        public Nullable<double> NET_TUTAR { get; set; }
        public Nullable<bool> TED_AKTAR { get; set; }
        public Nullable<System.DateTime> TED_AKTRH { get; set; }
        public string TAM_TESLIM { get; set; }
        public string ODE_TIP { get; set; }
        public string TED_AKUSR { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_USER { get; set; }
        public Nullable<System.DateTime> GOND_TRH { get; set; }
        public string GONDEREN { get; set; }
        public string PER_KOD { get; set; }
        public Nullable<System.DateTime> SAAT { get; set; }
        public Nullable<double> CLAIMNO { get; set; }
        public string SASE_NO { get; set; }
        public string IENO { get; set; }
        public string DIST_SIPNO { get; set; }
        public string SIP_DURUM { get; set; }
        public Nullable<System.DateTime> SIP_DURUM_TRH { get; set; }
    }
}
