//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMTRX
    {
        public string WTIP { get; set; }
        public Nullable<double> C { get; set; }
        public Nullable<double> GVZ { get; set; }
        public Nullable<double> I { get; set; }
        public Nullable<double> W0 { get; set; }
        public Nullable<double> W1 { get; set; }
        public Nullable<double> W2 { get; set; }
        public Nullable<double> W3 { get; set; }
        public Nullable<double> W4 { get; set; }
        public Nullable<double> W5 { get; set; }
        public Nullable<double> W6 { get; set; }
        public Nullable<double> W7 { get; set; }
        public Nullable<double> W8 { get; set; }
        public Nullable<double> W9 { get; set; }
        public Nullable<double> W10 { get; set; }
        public Nullable<double> W11 { get; set; }
        public Nullable<double> W12 { get; set; }
        public Nullable<double> W13 { get; set; }
    }
}
