//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class YETKILER
    {
        public int YETKI_ID { get; set; }
        public string YETKI_AD { get; set; }
        public Nullable<short> YETKI_TIP { get; set; }
    }
}
