//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class YILLIKIZIN
    {
        public double ISYERINO { get; set; }
        public double PERSNO { get; set; }
        public string YIL { get; set; }
        public string ADISOYADI { get; set; }
        public string DEP_NO { get; set; }
        public Nullable<double> YILLIKHAK { get; set; }
        public Nullable<double> KULLANILAN { get; set; }
        public Nullable<double> KULLANILMAYAN { get; set; }
    }
}
