//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class YUZBIR
    {
        public string SASI_NO { get; set; }
        public System.DateTime TARIH { get; set; }
        public string MOTOR_NO { get; set; }
        public Nullable<double> KM { get; set; }
        public string MARKA { get; set; }
        public string MODEL { get; set; }
        public string ARAC_TIP { get; set; }
        public string DOSYA_NUM { get; set; }
        public string PLAKA_NO { get; set; }
        public string RENK_KOD { get; set; }
        public string GARANTIONAYNO { get; set; }
        public string TEKYILDIZGARAN { get; set; }
        public string UCYILDIZGARAN { get; set; }
        public string BESYILDIZGARAN { get; set; }
        public string GARANTIVERILMEZ { get; set; }
        public string AD1_KAPORTAPRCDURUM { get; set; }
        public string AD2_BOYAGENDURUM { get; set; }
        public string AD3_FARSISSSLAMBA { get; set; }
        public string AD4_TUMCAMCATHAS { get; set; }
        public string AD5_SILASBAGKOL { get; set; }
        public string AD6_KAPIKILMEKAN { get; set; }
        public string AD7_KAPIVEKOL { get; set; }
        public string AD8_KAPIFILAST { get; set; }
        public string AD9_BENZDEPKAP { get; set; }
        public string AD10_ONKAPGUVMANMEN { get; set; }
        public string AD11_ARKBAGJKACMEK { get; set; }
        public string AD12_STEPKRIKOBIJANH { get; set; }
        public string AD13_BAGJICAYDLAMB { get; set; }
        public string AD14_TUMLASHAVBASNC { get; set; }
        public string AD15_LASTIKDISDER { get; set; }
        public string AD16_JANTVEKAPAK { get; set; }
        public string M17_ONSASIBAG { get; set; }
        public string M18_MOTYAGKALTSEV { get; set; }
        public string M19_FRENDEBHIDYAG { get; set; }
        public string M20_HIDIREKYAGKLT { get; set; }
        public string M21_HIDIREKPOMP { get; set; }
        public string M22_YAKDEVRHAT { get; set; }
        public string M23_ATESBOBKAB { get; set; }
        public string M24_MOTORSOGSIS { get; set; }
        public string M25_MOTORSOGSUANTFR { get; set; }
        public string M26_CAMTEMSIVISEV { get; set; }
        public string M27_HAVAPOLFIL { get; set; }
        public string M28_TRIGERKAYIS { get; set; }
        public string M29_VKAYISI { get; set; }
        public string M30_GERGIBILYA { get; set; }
        public string M31_ALTERNATOR { get; set; }
        public string M32_MARSMOTORU { get; set; }
        public string M33_TURBOYAGBORU { get; set; }
        public string M34_DEVIRDAIMSU { get; set; }
        public string M35_KLIMASIST { get; set; }
        public string M36_KALORIFERSIST { get; set; }
        public string M37_AKUSUSEV { get; set; }
        public string M38_AKUBAG { get; set; }
        public string M39_ELKABLOYALITIM { get; set; }
        public string M40_ELKKABLOSASIBAG { get; set; }
        public string M41_BUJIVEKABLO { get; set; }
        public string AA42_ALTSASIBAG { get; set; }
        public string AA43_FRENSEVBORUHRTYK { get; set; }
        public string AA44_YAKTANKBORUHORTYK { get; set; }
        public string AA45_MOTORYAGKAC { get; set; }
        public string AA46_HIDIREKKUTUYK { get; set; }
        public string AA47_VITESKUTUYK { get; set; }
        public string AA48_VITESKUTUYAGSEV { get; set; }
        public string AA49_DIFRANYAGSEV { get; set; }
        public string AA50_DIFRANYAGKAC { get; set; }
        public string AA51_KARMILMAF { get; set; }
        public string AA52_AMORYAGKAC { get; set; }
        public string AA53_FRENDISKAMP { get; set; }
        public string AA54_FRENBALATA { get; set; }
        public string AA55_ABSFRENSSEN { get; set; }
        public string AA56_TEKERULBOS { get; set; }
        public string AA57_AKSMILAKSKOR { get; set; }
        public string AA58_ROTBASROTKOL { get; set; }
        public string AA59_SALINCAKLAR { get; set; }
        public string AA60_VIRAJDEMIRI { get; set; }
        public string AA61_EGZOZBORUSUSMKK { get; set; }
        public string AI62_DIRSIMITKON { get; set; }
        public string AI63_TUMSILCAL { get; set; }
        public string AI64_CAMSUPUSKURFY { get; set; }
        public string AI65_GOSPANTUMIKAZ { get; set; }
        public string AI66_FARPRKSISLAMB { get; set; }
        public string AI67_IKAZLAMB { get; set; }
        public string AI68_FRENLAMB { get; set; }
        public string AI69_GERIVITESLAMB { get; set; }
        public string AI70_ICKABAYDLAMB { get; set; }
        public string AI71_KORNA { get; set; }
        public string AI72_RADYOTEYPCD { get; set; }
        public string AI73_KALFANMOT { get; set; }
        public string AI74_CAKMAKULLUK { get; set; }
        public string AI75_HAVAKANCALK { get; set; }
        public string AI76_DIKIZAYNAKUM { get; set; }
        public string AI77_ARKACAMREZ { get; set; }
        public string AI78_CAMKUM { get; set; }
        public string AI79_KOLTUKMEKBAS { get; set; }
        public string AI80_TABHALIPASPAS { get; set; }
        public string AI81_KOLTKDOSEKAPIC { get; set; }
        public string AI82_EMNIYETKEMER { get; set; }
        public string AI83_ACTAVMEK { get; set; }
        public string AI84_GUNESSIPER { get; set; }
        public string AI85_TORPIDOGOZ { get; set; }
        public string TS86_DEBRYJBALATA { get; set; }
        public string TS87_DEBRYJGAZFRPED { get; set; }
        public string TS88_DIREKSISCALBOS { get; set; }
        public string TS89_AKSAKTAR { get; set; }
        public string TS90_TEKERULMAN { get; set; }
        public string TS91_KAPIFILRUZGSES { get; set; }
        public string TS92_TEKERBALANS { get; set; }
        public string TS93_MOTORGENPERF { get; set; }
        public string TS94_OTODUZSANZVITES { get; set; }
        public string TS95_FRENSISODPERF { get; set; }
        public string TS96_ELFRENPERF { get; set; }
        public string TS97_SUSPANSIS { get; set; }
        public string TS98_YOLBILGISAYARI { get; set; }
        public string TS99_HIZDEVIRSHARYBG { get; set; }
        public string TS100_SOGUTFANCAL { get; set; }
        public string TS101_KALORIKLIMAPER { get; set; }
        public string IS_EMRI_NO { get; set; }
        public string CARI_KOD { get; set; }
        public string KONTROL_PERSON_KOD { get; set; }
        public string YETKILI_PERSON_KOD { get; set; }
        public Nullable<short> FYILI { get; set; }
    }
}
