//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZATSARAC
    {
        public string PLAKA_NO { get; set; }
        public string SINIF { get; set; }
        public string MARKA { get; set; }
        public string MODEL { get; set; }
        public Nullable<int> MODEL_YIL { get; set; }
        public string PER_ADI { get; set; }
        public string PER_KOD { get; set; }
        public string PER_TEL { get; set; }
        public string SASE_NO { get; set; }
        public string MODEL_KOD { get; set; }
        public string CIHAZ_ID { get; set; }
        public string CARI_KOD { get; set; }
        public Nullable<short> SUBEKODU { get; set; }
        public string NOTLAR { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string UPD_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    }
}
