//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproje.Models.Pitstop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZIMMET
    {
        public int ZIM_NO { get; set; }
        public string CARI_KOD { get; set; }
        public Nullable<short> SUBEKODU { get; set; }
        public string PER_KOD { get; set; }
        public string SASE_NO { get; set; }
        public Nullable<System.DateTime> BAS_TRH { get; set; }
        public Nullable<System.DateTime> BIT_TRH { get; set; }
        public Nullable<byte> STATU { get; set; }
        public string ACIKLAMA { get; set; }
        public string EKIPMANLAR { get; set; }
        public string INS_USER { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string PLAKA { get; set; }
    }
}
